import Phaser from 'phaser';
import { BG_COLOR, NEON, NEON_CSS } from '../config/colors';
import { ENEMY_DEFS } from '../config/enemies';
import { GAME_WIDTH } from '../config/game-config';
import { createButton } from '../ui/ButtonFactory';
import { SaveManager } from '../managers/SaveManager';
import { enableDragScroll } from '../utils/DragScroll';

const ENEMY_NAMES: Record<string, string> = {
  basic: '기본형',
  fast: '돌격형',
  tank: '중장갑',
  special: '특수형',
  splitter: '분열체',
  chaser: '추적자',
  shooter: '사수',
  swarm: '군체',
  guardian: '수호형',
  sniper_enemy: '저격수',
  teleporter: '전이체',
  boss: '수호자',
  boss_circle: '회전자',
  boss_burst: '돌격자',
};

const BEHAVIOR_LABELS: Record<string, string> = {
  march: '직진',
  dash: '돌진',
  slow_march: '느린 전진',
  zigzag: '지그재그',
  split_on_death: '분열',
  chase: '추적',
  slow_chase: '느린 추적',
  boss_chase: '보스 추적',
  boss_circle: '선회',
  boss_burst: '돌파',
  shoot: '원거리',
  teleport: '순간이동',
};

/** Map enemy shape to the texture key generated by TextureFactory */
const SHAPE_TO_TEXTURE: Record<string, string> = {
  circle: 'enemy_circle',
  triangle: 'enemy_triangle',
  rect: 'enemy_rect',
  diamond: 'enemy_diamond',
  hexagon: 'enemy_hexagon',
};

/** Per-enemy-id texture overrides — pixel art sprites */
const ID_TEXTURES: Record<string, string> = {
  // T1
  basic: 't1_moth',
  fast: 't1_rat',
  special: 't1_butterfly',
  swarm: 't1_ant',
  chaser: 't1_cat',
  shooter: 't1_jelly',
  // T2
  tank: 'opt_t2_ape',
  splitter: 'opt_t2_kite',
  guardian: 'opt_t2_lion',
  sniper_enemy: 'opt_t2_koi',
  teleporter: 'opt_t2_pango',
};

/** Boss textures — use _large for codex clarity */
const BOSS_TEXTURES: Record<string, string> = {
  boss: 'boss_aero_large',
  boss_circle: 'boss_hydra_large',
  boss_burst: 'boss_blaze_large',
  // Stage 4~6 (activate when def added to enemies.ts):
  // boss_terra_def: 'boss_terra_large',
  // boss_lumen_def: 'boss_lumen_large',
  // boss_umbra_def: 'boss_umbra_large',
  // Final boss:
  // boss_harvester_def: 'boss_harvester_large',
};

const COLOR_MAP: Record<string, number> = {
  ENEMY_BASIC: NEON.ENEMY_BASIC,
  ENEMY_FAST: NEON.ENEMY_FAST,
  ENEMY_TANK: NEON.ENEMY_TANK,
  ENEMY_SPECIAL: NEON.ENEMY_SPECIAL,
  ENEMY_ELITE: NEON.ENEMY_ELITE,
};

/** Resolve texture key with PNG existence fallback */
function resolveTexKey(scene: Phaser.Scene, defId: string, defShape: string): string {
  const bossTex = BOSS_TEXTURES[defId];
  const idTex = ID_TEXTURES[defId];
  const shapeTex = SHAPE_TO_TEXTURE[defShape] ?? 'enemy_circle';
  if (bossTex && scene.textures.exists(bossTex)) return bossTex;
  if (idTex && scene.textures.exists(idTex)) return idTex;
  return shapeTex;
}

export class EnemyCodexScene extends Phaser.Scene {
  constructor() {
    super({ key: 'EnemyCodexScene' });
  }

  create(): void {
    this.cameras.main.setBackgroundColor(BG_COLOR);
    this.cameras.main.fadeIn(300);
    const cx = GAME_WIDTH / 2;

    const discovered = SaveManager.getDiscovered();
    const allDefs = Object.values(ENEMY_DEFS);
    const unlockedCount = allDefs.filter(d => discovered.enemies.includes(d.id)).length;

    // Title
    this.add
      .text(cx, 50, '적 도감', {
        fontSize: '38px',
        color: NEON_CSS.UI_ACCENT,
        fontFamily: 'monospace',
        fontStyle: 'bold',
      })
      .setOrigin(0.5);

    // Discovery counter
    this.add
      .text(cx, 86, `${unlockedCount} / ${allDefs.length} 해금`, {
        fontSize: '22px',
        color: NEON_CSS.UI_DIM,
        fontFamily: 'monospace',
      })
      .setOrigin(0.5);
    const normals = allDefs.filter(d => !d.id.startsWith('boss'));
    const bosses = allDefs.filter(d => d.id.startsWith('boss'));

    const cardW = 330;
    const cardH = 100;
    const gap = 10;
    const startY = 120;
    const col1X = cx - cardW / 2 - gap / 2;
    const col2X = cx + cardW / 2 + gap / 2;

    // Normal enemies (2 columns)
    const normalRows = Math.ceil(normals.length / 2);
    normals.forEach((def, i) => {
      const col = i % 2;
      const row = Math.floor(i / 2);
      const x = col === 0 ? col1X : col2X;
      const y = startY + row * (cardH + gap) + cardH / 2;
      const unlocked = discovered.enemies.includes(def.id);
      this.createEnemyCard(x, y, cardW, cardH, def, false, unlocked);
    });

    // Boss separator
    const bossStartY = startY + normalRows * (cardH + gap) + 16;
    this.add
      .text(cx, bossStartY, '--- 보스 ---', {
        fontSize: '24px',
        color: NEON_CSS.GOLD,
        fontFamily: 'monospace',
        fontStyle: 'bold',
      })
      .setOrigin(0.5);

    // Boss enemies (full width cards)
    const bossCardW = 680;
    const bossListY = bossStartY + 36;
    bosses.forEach((def, i) => {
      const y = bossListY + i * (cardH + gap) + cardH / 2;
      const unlocked = discovered.enemies.includes(def.id);
      this.createEnemyCard(cx, y, bossCardW, cardH, def, true, unlocked);
    });

    // Back button
    const lastBossY = bossListY + (bosses.length - 1) * (cardH + gap) + cardH / 2;
    const btnY = lastBossY + cardH / 2 + 30;
    createButton(this, {
      x: cx, y: btnY, width: 220, height: 52,
      label: '돌아가기', fontSize: '26px',
      variant: 'secondary',
      onClick: () => this.scene.start('MainMenuScene'),
    });

    // Enable drag scroll if content overflows
    const totalHeight = btnY + 50;
    if (totalHeight > 1280) {
      enableDragScroll(this, totalHeight);
    }
  }

  private createEnemyCard(
    x: number, y: number, w: number, h: number,
    def: typeof ENEMY_DEFS[string],
    isBoss: boolean,
    unlocked: boolean,
  ): void {
    const borderColor = isBoss ? NEON.ENEMY_ELITE : NEON.UI_BORDER;

    // Card bg
    this.add
      .rectangle(x, y, w, h, NEON.UI_PANEL, unlocked ? 0.9 : 0.4)
      .setStrokeStyle(1, unlocked ? borderColor : NEON.UI_PANEL);

    const spriteX = x - w / 2 + 36;
    const textL = x - w / 2 + 72;
    const textR = x + w / 2 - 12;
    const pad = 16;

    if (!unlocked) {
      // Locked — silhouette sprite + "???"
      const texKey = resolveTexKey(this, def.id, def.shape);
      const silhouette = this.add.sprite(spriteX, y, texKey);
      silhouette.setTint(0x111111);
      silhouette.setAlpha(0.4);
      const silTexW = silhouette.texture.getSourceImage().width;
      silhouette.setScale(silTexW > 0 ? (isBoss ? 96 : 56) / silTexW : 1);

      this.add
        .text(x + 20, y, '???', {
          fontSize: '28px',
          color: NEON_CSS.UI_DIM,
          fontFamily: 'monospace',
          fontStyle: 'bold',
        })
        .setOrigin(0.5)
        .setAlpha(0.5);
      return;
    }

    // Enemy sprite preview
    const texKey = resolveTexKey(this, def.id, def.shape);
    const tintColor = COLOR_MAP[def.colorKey] ?? NEON.ENEMY_BASIC;
    const sprite = this.add.sprite(spriteX, y, texKey);
    const sprTexW = sprite.texture.getSourceImage().width;
    sprite.setScale(sprTexW > 0 ? (isBoss ? 96 : 56) / sprTexW : 1);

    // Name — top-left of text area
    const name = ENEMY_NAMES[def.id] ?? def.id;
    const nameColor = isBoss ? NEON_CSS.GOLD : NEON_CSS.UI_TEXT;
    this.add
      .text(textL, y - pad, name, {
        fontSize: '22px',
        color: nameColor,
        fontFamily: 'monospace',
        fontStyle: 'bold',
      })
      .setOrigin(0, 0.5);

    // Stats — below name
    this.add
      .text(textL, y + pad, `HP ${def.baseHp}  ATK ${def.baseDamage}  SPD ${def.baseSpeed}`, {
        fontSize: '18px',
        color: NEON_CSS.UI_DIM,
        fontFamily: 'monospace',
      })
      .setOrigin(0, 0.5);

    // Behavior label — top-right
    const behaviorLabel = BEHAVIOR_LABELS[def.behavior] ?? def.behavior;
    this.add
      .text(textR, y - pad, behaviorLabel, {
        fontSize: '18px',
        color: NEON_CSS.UI_DIM,
        fontFamily: 'monospace',
      })
      .setOrigin(1, 0.5);

    // XP value — bottom-right
    this.add
      .text(textR, y + pad, `XP ${def.xpValue}`, {
        fontSize: '18px',
        color: NEON_CSS.XP_BAR,
        fontFamily: 'monospace',
      })
      .setOrigin(1, 0.5);
  }

}
