import Phaser from 'phaser';
import { BG_COLOR, NEON, NEON_CSS } from '../config/colors';
import { ENEMY_DEFS } from '../config/enemies';
import { GAME_WIDTH } from '../config/game-config';

const ENEMY_NAMES: Record<string, string> = {
  basic: '기본형',
  fast: '돌격형',
  tank: '중장갑',
  special: '특수형',
  splitter: '분열체',
  chaser: '추적자',
  boss: '수호자',
  boss_circle: '회전자',
  boss_burst: '돌격자',
};

const BEHAVIOR_LABELS: Record<string, string> = {
  march: '직진',
  dash: '돌진',
  slow_march: '느린 전진',
  zigzag: '지그재그',
  split_on_death: '분열',
  chase: '추적',
  slow_chase: '느린 추적',
  boss_chase: '보스 추적',
  boss_circle: '선회',
  boss_burst: '돌파',
};

/** Map enemy shape to the texture key generated by TextureFactory */
const SHAPE_TO_TEXTURE: Record<string, string> = {
  circle: 'enemy_circle',
  triangle: 'enemy_triangle',
  rect: 'enemy_rect',
  diamond: 'enemy_diamond',
  hexagon: 'enemy_hexagon',
};

const BOSS_TEXTURES: Record<string, string> = {
  boss: 'boss_hex',
  boss_circle: 'boss_diamond',
  boss_burst: 'boss_rect',
};

const COLOR_MAP: Record<string, number> = {
  ENEMY_BASIC: NEON.ENEMY_BASIC,
  ENEMY_FAST: NEON.ENEMY_FAST,
  ENEMY_TANK: NEON.ENEMY_TANK,
  ENEMY_SPECIAL: NEON.ENEMY_SPECIAL,
  ENEMY_ELITE: NEON.ENEMY_ELITE,
};

export class EnemyCodexScene extends Phaser.Scene {
  constructor() {
    super({ key: 'EnemyCodexScene' });
  }

  create(): void {
    this.cameras.main.setBackgroundColor(BG_COLOR);
    const cx = GAME_WIDTH / 2;

    // Title
    this.add
      .text(cx, 50, '적 도감', {
        fontSize: '32px',
        color: NEON_CSS.UI_ACCENT,
        fontFamily: 'monospace',
        fontStyle: 'bold',
      })
      .setOrigin(0.5);

    // Separate normal enemies and bosses
    const allDefs = Object.values(ENEMY_DEFS);
    const normals = allDefs.filter(d => !d.id.startsWith('boss'));
    const bosses = allDefs.filter(d => d.id.startsWith('boss'));

    // Scrollable container
    const container = this.add.container(0, 0);

    const cardW = 320;
    const cardH = 110;
    const gap = 12;
    const startY = 100;
    const col1X = cx - cardW / 2 - gap / 2;
    const col2X = cx + cardW / 2 + gap / 2;

    let curY = startY;

    // Normal enemies (2 columns)
    normals.forEach((def, i) => {
      const col = i % 2;
      const row = Math.floor(i / 2);
      const x = col === 0 ? col1X : col2X;
      const y = startY + row * (cardH + gap) + cardH / 2;

      this.createEnemyCard(container, x, y, cardW, cardH, def, false);
      curY = y + cardH / 2 + gap;
    });

    // Boss separator
    curY += 10;
    this.add
      .text(cx, curY, '--- 보스 ---', {
        fontSize: '20px',
        color: NEON_CSS.GOLD,
        fontFamily: 'monospace',
        fontStyle: 'bold',
      })
      .setOrigin(0.5);
    curY += 40;

    // Boss enemies (full width cards)
    const bossCardW = 680;
    bosses.forEach((def, i) => {
      const y = curY + i * (cardH + gap) + cardH / 2;
      this.createEnemyCard(container, cx, y, bossCardW, cardH, def, true);
      curY = y + cardH / 2 + gap;
    });

    // Back button
    curY += 20;
    const btnBg = this.add
      .rectangle(cx, curY, 200, 48, NEON.UI_PANEL)
      .setStrokeStyle(2, NEON.UI_BORDER);

    this.add
      .text(cx, curY, '돌아가기', {
        fontSize: '22px',
        color: NEON_CSS.UI_TEXT,
        fontFamily: 'monospace',
        fontStyle: 'bold',
      })
      .setOrigin(0.5);

    btnBg
      .setInteractive({ useHandCursor: true })
      .on('pointerover', () => btnBg.setStrokeStyle(3, NEON.UI_ACCENT))
      .on('pointerout', () => btnBg.setStrokeStyle(2, NEON.UI_BORDER))
      .on('pointerdown', () => this.scene.start('MainMenuScene'));

    // Enable drag scroll if content overflows
    const totalHeight = curY + 40;
    if (totalHeight > 1280) {
      this.enableDragScroll(totalHeight);
    }
  }

  private createEnemyCard(
    _container: Phaser.GameObjects.Container,
    x: number, y: number, w: number, h: number,
    def: typeof ENEMY_DEFS[string],
    isBoss: boolean,
  ): void {
    const borderColor = isBoss ? NEON.ENEMY_ELITE : NEON.UI_BORDER;

    // Card bg
    this.add
      .rectangle(x, y, w, h, NEON.UI_PANEL, 0.9)
      .setStrokeStyle(1, borderColor);

    // Enemy sprite preview
    const texKey = BOSS_TEXTURES[def.id] ?? SHAPE_TO_TEXTURE[def.shape] ?? 'enemy_circle';
    const tintColor = COLOR_MAP[def.colorKey] ?? NEON.ENEMY_BASIC;
    const sprite = this.add.sprite(x - w / 2 + 40, y, texKey);
    sprite.setTint(tintColor);
    if (isBoss) sprite.setScale(1.5);

    // Name
    const name = ENEMY_NAMES[def.id] ?? def.id;
    const nameColor = isBoss ? NEON_CSS.GOLD : NEON_CSS.UI_TEXT;
    this.add
      .text(x - w / 2 + 80, y - h / 2 + 12, name, {
        fontSize: '20px',
        color: nameColor,
        fontFamily: 'monospace',
        fontStyle: 'bold',
      });

    // Stats
    this.add
      .text(x - w / 2 + 80, y + 4, `HP ${def.baseHp}  ATK ${def.baseDamage}  SPD ${def.baseSpeed}`, {
        fontSize: '14px',
        color: NEON_CSS.UI_DIM,
        fontFamily: 'monospace',
      });

    // Behavior label
    const behaviorLabel = BEHAVIOR_LABELS[def.behavior] ?? def.behavior;
    this.add
      .text(x + w / 2 - 16, y - h / 2 + 14, behaviorLabel, {
        fontSize: '14px',
        color: NEON_CSS.UI_DIM,
        fontFamily: 'monospace',
      })
      .setOrigin(1, 0);

    // XP value
    this.add
      .text(x + w / 2 - 16, y + h / 2 - 20, `XP ${def.xpValue}`, {
        fontSize: '14px',
        color: NEON_CSS.XP_BAR,
        fontFamily: 'monospace',
      })
      .setOrigin(1, 0);
  }

  private enableDragScroll(contentHeight: number): void {
    const cam = this.cameras.main;
    const maxScroll = contentHeight - 1280;

    this.input.on('pointermove', (pointer: Phaser.Input.Pointer) => {
      if (pointer.isDown) {
        cam.scrollY -= pointer.velocity.y * 0.02;
        cam.scrollY = Phaser.Math.Clamp(cam.scrollY, 0, maxScroll);
      }
    });
  }
}
