import Phaser from 'phaser';
import { BG_COLOR, NEON, NEON_CSS, TEX, CODEX } from '../config/colors';
import { ENEMY_DEFS } from '../config/enemies';
import { GAME_WIDTH, GAME_HEIGHT } from '../config/game-config';
import { createButton } from '../ui/ButtonFactory';
import { SaveManager } from '../managers/SaveManager';
import { enableDragScroll } from '../utils/DragScroll';
import { t } from '../lib/i18n';
import type { EnemyDef } from '../types/enemy';
import { resolveTexture } from '../config/atlas-manifest';
import { navigateScene } from '../utils/SceneNav';

const FIXED_FOOTER_H = 80;
const HEADER_H = 120; // title + counter + tabs

/** Map enemy shape to the texture key generated by TextureFactory */
const SHAPE_TO_TEXTURE: Record<string, string> = {
  circle: 'enemy_circle',
  triangle: 'enemy_triangle',
  rect: 'enemy_rect',
  diamond: 'enemy_diamond',
  hexagon: 'enemy_hexagon',
};

/** Per-enemy-id texture overrides — pixel art sprites */
const ID_TEXTURES: Record<string, string> = {
  basic: 't1_moth',
  fast: 't1_rat',
  special: 't1_butterfly',
  swarm: 't1_ant',
  chaser: 't1_cat',
  shooter: 't1_jelly',
  tank: 'opt_t2_ape',
  splitter: 'opt_t2_kite',
  guardian: 'opt_t2_lion',
  sniper_enemy: 'opt_t2_koi',
  teleporter: 'opt_t2_pango',
};

/** Boss textures — use _large for codex clarity */
const BOSS_TEXTURES: Record<string, string> = {
  boss: 'boss_aero_large',
  boss_circle: 'boss_hydra_large',
  boss_burst: 'boss_blaze_large',
};

/** Map enemy id to appearance chapter */
const ENEMY_CHAPTER: Record<string, number> = {
  basic: 1,
  fast: 1,
  swarm: 1,
  tank: 2,
  special: 2,
  shooter: 2,
  chaser: 3,
  splitter: 3,
  sniper_enemy: 3,
  guardian: 4,
  teleporter: 4,
  boss: 1,
  boss_circle: 2,
  boss_burst: 3,
};

type FilterTab = 'all' | 'ground' | 'air' | 'boss';

/** Resolve texture key with PNG existence fallback */
function resolveTexKey(scene: Phaser.Scene, defId: string, defShape: string): string {
  const bossTex = BOSS_TEXTURES[defId];
  const idTex = ID_TEXTURES[defId];
  const shapeTex = SHAPE_TO_TEXTURE[defShape] ?? 'enemy_circle';
  if (bossTex && (scene.textures.exists(bossTex) || resolveTexture(scene, bossTex))) return bossTex;
  if (idTex && (scene.textures.exists(idTex) || resolveTexture(scene, idTex))) return idTex;
  return shapeTex;
}

/** Get glow color based on enemy tier */
function getGlowColor(def: EnemyDef): number {
  if (def.id.startsWith('boss')) return CODEX.GLOW_BOSS;
  if (def.colorKey === 'ENEMY_TANK' || def.colorKey === 'ENEMY_ELITE') return CODEX.GLOW_T2;
  return CODEX.GLOW_T1;
}

/** Get badge color for category */
function getBadgeColor(def: EnemyDef): number {
  if (def.id.startsWith('boss')) return CODEX.BADGE_BOSS;
  return def.category === 'air' ? CODEX.BADGE_AIR : CODEX.BADGE_GROUND;
}

export class EnemyCodexScene extends Phaser.Scene {
  private cardContainer!: Phaser.GameObjects.Container;
  private detailContainer: Phaser.GameObjects.Container | null = null;
  private activeTab: FilterTab = 'all';
  private tabButtons: { tab: FilterTab; bg: Phaser.GameObjects.Rectangle; label: Phaser.GameObjects.Text }[] = [];

  constructor() {
    super({ key: 'EnemyCodexScene' });
  }

  shutdown(): void {
    this.detailContainer?.destroy();
    this.detailContainer = null;
    this.cardContainer?.destroy(true);
    this.tabButtons = [];
  }

  create(): void {
    this.cameras.main.setBackgroundColor(BG_COLOR);
    this.cameras.main.fadeIn(300);
    this.cameras.main.scrollY = 0;
    const cx = GAME_WIDTH / 2;

    const discovered = SaveManager.getDiscovered();
    const allDefs = Object.values(ENEMY_DEFS);
    const unlockedCount = allDefs.filter((d) => discovered.enemies.includes(d.id)).length;

    // ── Title (fixed header) ──
    this.add
      .text(cx, 32, t('codex.enemies_title'), {
        fontSize: '34px',
        color: NEON_CSS.UI_ACCENT,
        fontFamily: 'monospace',
        fontStyle: 'bold',
      })
      .setOrigin(0.5)
      .setScrollFactor(0)
      .setDepth(100);

    // Discovery counter
    this.add
      .text(cx, 62, t('codex.unlocked', { count: unlockedCount, total: allDefs.length }), {
        fontSize: '18px',
        color: NEON_CSS.UI_DIM,
        fontFamily: 'monospace',
      })
      .setOrigin(0.5)
      .setScrollFactor(0)
      .setDepth(100);

    // ── Category filter tabs (fixed header) ──
    this.createFilterTabs(cx);

    // ── Card container (scrollable) ──
    this.cardContainer = this.add.container(0, 0);
    this.renderCards();

    // ── Back button (fixed footer) ──
    const backBtnY = GAME_HEIGHT - FIXED_FOOTER_H / 2;
    createButton(this, {
      x: cx,
      y: backBtnY,
      width: 220,
      height: 52,
      label: t('codex.back'),
      fontSize: '26px',
      variant: 'secondary',
      onClick: () => navigateScene(this, 'EnemyCodexScene', 'MainMenuScene'),
    })
      .setScrollFactor(0)
      .setDepth(200);
  }

  /** Create the filter tab row */
  private createFilterTabs(cx: number): void {
    const tabs: { tab: FilterTab; labelKey: string }[] = [
      { tab: 'all', labelKey: 'codex.tab_all' },
      { tab: 'ground', labelKey: 'codex.tab_ground' },
      { tab: 'air', labelKey: 'codex.tab_air' },
      { tab: 'boss', labelKey: 'codex.tab_boss' },
    ];
    const tabW = 130;
    const tabH = 48;
    const tabGap = 10;
    const totalW = tabs.length * tabW + (tabs.length - 1) * tabGap;
    const startX = cx - totalW / 2 + tabW / 2;
    const tabY = 94;

    tabs.forEach((item, i) => {
      const x = startX + i * (tabW + tabGap);
      const isActive = item.tab === this.activeTab;

      const bg = this.add
        .rectangle(x, tabY, tabW, tabH, isActive ? CODEX.TAB_ACTIVE : CODEX.TAB_INACTIVE, isActive ? 0.3 : 0.2)
        .setStrokeStyle(1, isActive ? CODEX.TAB_ACTIVE : CODEX.TAB_INACTIVE, isActive ? 0.8 : 0.3)
        .setScrollFactor(0)
        .setDepth(100)
        .setInteractive({ useHandCursor: true });

      const label = this.add
        .text(x, tabY, t(item.labelKey), {
          fontSize: '16px',
          color: isActive ? NEON_CSS.UI_ACCENT : NEON_CSS.UI_DIM,
          fontFamily: 'monospace',
          fontStyle: isActive ? 'bold' : 'normal',
        })
        .setOrigin(0.5)
        .setScrollFactor(0)
        .setDepth(101);

      bg.on('pointerdown', () => {
        if (this.activeTab === item.tab) return;
        this.activeTab = item.tab;
        this.updateTabVisuals();
        this.cameras.main.scrollY = 0;
        this.renderCards();
      });

      this.tabButtons.push({ tab: item.tab, bg, label });
    });
  }

  /** Update tab highlight visuals */
  private updateTabVisuals(): void {
    this.tabButtons.forEach(({ tab, bg, label }) => {
      const isActive = tab === this.activeTab;
      bg.setFillStyle(isActive ? CODEX.TAB_ACTIVE : CODEX.TAB_INACTIVE, isActive ? 0.3 : 0.2);
      bg.setStrokeStyle(1, isActive ? CODEX.TAB_ACTIVE : CODEX.TAB_INACTIVE, isActive ? 0.8 : 0.3);
      label.setColor(isActive ? NEON_CSS.UI_ACCENT : NEON_CSS.UI_DIM);
      label.setFontStyle(isActive ? 'bold' : 'normal');
    });
  }

  /** Filter and render enemy cards */
  private renderCards(): void {
    // Clear existing cards
    this.cardContainer.removeAll(true);
    // Close any open detail panel
    if (this.detailContainer) {
      this.detailContainer.destroy();
      this.detailContainer = null;
    }

    const discovered = SaveManager.getDiscovered();
    const allDefs = Object.values(ENEMY_DEFS);
    const cx = GAME_WIDTH / 2;

    // Filter by active tab
    let filtered: EnemyDef[];
    switch (this.activeTab) {
      case 'ground':
        filtered = allDefs.filter((d) => !d.id.startsWith('boss') && d.category === 'ground');
        break;
      case 'air':
        filtered = allDefs.filter((d) => !d.id.startsWith('boss') && d.category === 'air');
        break;
      case 'boss':
        filtered = allDefs.filter((d) => d.id.startsWith('boss'));
        break;
      default:
        filtered = allDefs;
    }

    const cardW = 380;
    const cardH = 110;
    const gap = 12;
    const startY = HEADER_H + 10;

    // Layout: 2 columns for normal, full width for boss
    // In boss-only tab, use wider single column
    const isBossTab = this.activeTab === 'boss';

    if (isBossTab) {
      const bossCardW = 680;
      filtered.forEach((def, i) => {
        const y = startY + i * (cardH + gap) + cardH / 2;
        const unlocked = discovered.enemies.includes(def.id);
        this.createEnemyCard(cx, y, bossCardW, cardH, def, true, unlocked);
      });
      const totalH = startY + filtered.length * (cardH + gap) + 20;
      this.setupScroll(totalH);
    } else {
      // Separate normals and bosses for mixed tabs
      const normals = filtered.filter((d) => !d.id.startsWith('boss'));
      const bosses = filtered.filter((d) => d.id.startsWith('boss'));

      const col1X = cx - cardW / 2 - gap / 2;
      const col2X = cx + cardW / 2 + gap / 2;
      const normalRows = Math.ceil(normals.length / 2);

      normals.forEach((def, i) => {
        const col = i % 2;
        const row = Math.floor(i / 2);
        const x = col === 0 ? col1X : col2X;
        const y = startY + row * (cardH + gap) + cardH / 2;
        const unlocked = discovered.enemies.includes(def.id);
        this.createEnemyCard(x, y, cardW, cardH, def, false, unlocked);
      });

      // Boss section
      let bossStartY = startY + normalRows * (cardH + gap);
      if (bosses.length > 0 && normals.length > 0) {
        // Boss separator
        const sepY = bossStartY + 8;
        const sep = this.add
          .text(cx, sepY, t('codex.boss_separator'), {
            fontSize: '22px',
            color: NEON_CSS.GOLD,
            fontFamily: 'monospace',
            fontStyle: 'bold',
          })
          .setOrigin(0.5);
        this.cardContainer.add(sep);
        bossStartY = sepY + 28;
      }

      const bossCardW = 680;
      bosses.forEach((def, i) => {
        const y = bossStartY + i * (cardH + gap) + cardH / 2;
        const unlocked = discovered.enemies.includes(def.id);
        this.createEnemyCard(cx, y, bossCardW, cardH, def, true, unlocked);
      });

      const lastY =
        bosses.length > 0 ? bossStartY + bosses.length * (cardH + gap) : startY + normalRows * (cardH + gap);
      this.setupScroll(lastY + 20);
    }
  }

  /** Setup scroll if content overflows */
  private setupScroll(totalContentHeight: number): void {
    const scrollableHeight = GAME_HEIGHT - FIXED_FOOTER_H;
    if (totalContentHeight > scrollableHeight) {
      enableDragScroll(this, totalContentHeight, scrollableHeight);
    }
  }

  /** Create a glassmorphism enemy card */
  private createEnemyCard(
    x: number,
    y: number,
    w: number,
    h: number,
    def: EnemyDef,
    isBoss: boolean,
    unlocked: boolean,
  ): void {
    const glowColor = getGlowColor(def);
    const g = this.add.graphics();

    // Glassmorphism card background
    const hw = w / 2;
    const hh = h / 2;
    const r = 10;

    // Outer glow border (tier-based)
    if (unlocked) {
      g.lineStyle(2, glowColor, CODEX.GLASS_BORDER_ALPHA);
      g.strokeRoundedRect(x - hw, y - hh, w, h, r);
    }

    // Glass fill
    g.fillStyle(CODEX.GLASS_BG, unlocked ? CODEX.GLASS_BG_ALPHA : 0.4);
    g.fillRoundedRect(x - hw, y - hh, w, h, r);

    if (!unlocked) {
      // Subtle border for locked cards
      g.lineStyle(1, NEON.UI_BORDER, 0.3);
      g.strokeRoundedRect(x - hw, y - hh, w, h, r);
    }

    this.cardContainer.add(g);

    const spriteX = x - hw + 40;
    const textL = x - hw + 80;
    const textR = x + hw - 12;

    if (!unlocked) {
      // ── Locked: glitch silhouette ──
      this.createLockedVisual(spriteX, y, def, isBoss);
      return;
    }

    // ── Sprite with neon glow frame ──
    const texKey = resolveTexKey(this, def.id, def.shape);
    const spriteSize = isBoss ? 80 : 56;

    // Neon glow circle behind sprite
    const glowGfx = this.add.graphics();
    glowGfx.fillStyle(glowColor, 0.15);
    glowGfx.fillCircle(spriteX, y, spriteSize / 2 + 6);
    glowGfx.lineStyle(2, glowColor, 0.5);
    glowGfx.strokeCircle(spriteX, y, spriteSize / 2 + 4);
    this.cardContainer.add(glowGfx);

    const sprite = this.add.sprite(spriteX, y, texKey);
    const sprTexW = sprite.texture.getSourceImage().width;
    sprite.setScale(sprTexW > 0 ? spriteSize / sprTexW : 1);
    this.cardContainer.add(sprite);

    // ── Category badge (top-left corner of text area) ──
    const badgeColor = getBadgeColor(def);
    const badgeLabel = def.id.startsWith('boss') ? t('codex.category_boss') : t(`codex.category_${def.category}`);

    const badgeBg = this.add
      .rectangle(textL + 26, y - hh + 16, 52, 22, badgeColor, 0.25)
      .setStrokeStyle(1, badgeColor, 0.6);
    this.cardContainer.add(badgeBg);

    const badgeText = this.add
      .text(textL + 26, y - hh + 16, badgeLabel, {
        fontSize: '14px',
        color: NEON_CSS.UI_TEXT,
        fontFamily: 'monospace',
        fontStyle: 'bold',
      })
      .setOrigin(0.5);
    this.cardContainer.add(badgeText);

    // ── Name ──
    const name = t(`enemy.${def.id}`);
    const nameColor = isBoss ? NEON_CSS.GOLD : NEON_CSS.UI_TEXT;
    const nameText = this.add
      .text(textL, y - 14, name, {
        fontSize: '22px',
        color: nameColor,
        fontFamily: 'monospace',
        fontStyle: 'bold',
      })
      .setOrigin(0, 0.5);
    this.cardContainer.add(nameText);

    // ── Stats ──
    const statsText = this.add
      .text(textL, y + 10, `HP ${def.baseHp}  ATK ${def.baseDamage}  SPD ${def.baseSpeed}`, {
        fontSize: '16px',
        color: NEON_CSS.UI_DIM,
        fontFamily: 'monospace',
      })
      .setOrigin(0, 0.5);
    this.cardContainer.add(statsText);

    // ── Chapter + XP (bottom-left) ──
    const ch = ENEMY_CHAPTER[def.id] ?? 1;
    const chapterXpText = this.add
      .text(textL, y + 30, `${t('codex.chapter', { ch })}  ·  XP ${def.xpValue}`, {
        fontSize: '14px',
        color: NEON_CSS.XP_BAR,
        fontFamily: 'monospace',
      })
      .setOrigin(0, 0.5);
    this.cardContainer.add(chapterXpText);

    // ── Behavior label (right side) ──
    const behaviorLabel = t(`behavior.${def.behavior}`);
    const behaviorText = this.add
      .text(textR, y - 14, behaviorLabel, {
        fontSize: '16px',
        color: NEON_CSS.UI_DIM,
        fontFamily: 'monospace',
      })
      .setOrigin(1, 0.5);
    this.cardContainer.add(behaviorText);

    // ── Make card interactive for detail panel ──
    const hitZone = this.add.rectangle(x, y, w, h, NEON.BG_BLACK, 0).setInteractive({ useHandCursor: true });
    this.cardContainer.add(hitZone);

    hitZone.on('pointerdown', () => {
      this.showDetailPanel(def);
    });
  }

  /** Locked card: glitch silhouette effect */
  private createLockedVisual(spriteX: number, y: number, def: EnemyDef, isBoss: boolean): void {
    const texKey = resolveTexKey(this, def.id, def.shape);
    const spriteSize = isBoss ? 80 : 56;

    // Dark silhouette
    const silhouette = this.add.sprite(spriteX, y, texKey);
    silhouette.setTint(TEX.CODEX_SILHOUETTE);
    silhouette.setAlpha(0.3);
    const silTexW = silhouette.texture.getSourceImage().width;
    silhouette.setScale(silTexW > 0 ? spriteSize / silTexW : 1);
    this.cardContainer.add(silhouette);

    // Glitch scan lines over silhouette
    const glitchGfx = this.add.graphics();
    const lineCount = 4;
    for (let i = 0; i < lineCount; i++) {
      const ly = y - spriteSize / 2 + (i + 0.5) * (spriteSize / lineCount);
      const lw = 10 + Math.random() * (spriteSize - 10);
      const lx = spriteX - lw / 2 + (Math.random() - 0.5) * 8;
      glitchGfx.fillStyle(CODEX.GLITCH_LINE, 0.12 + Math.random() * 0.08);
      glitchGfx.fillRect(lx, ly, lw, 2);
    }
    this.cardContainer.add(glitchGfx);

    // Pulsing glitch tween on silhouette
    this.tweens.add({
      targets: silhouette,
      alpha: { from: 0.2, to: 0.4 },
      duration: 1200,
      yoyo: true,
      repeat: -1,
      ease: 'Sine.easeInOut',
    });
  }

  /** Show expanded detail panel on card tap */
  private showDetailPanel(def: EnemyDef): void {
    // Remove existing detail panel
    if (this.detailContainer) {
      this.detailContainer.destroy();
      this.detailContainer = null;
    }

    const cx = GAME_WIDTH / 2;
    const cy = GAME_HEIGHT / 2;
    const panelW = 500;
    const panelH = 280;
    const isBoss = def.id.startsWith('boss');

    this.detailContainer = this.add.container(0, 0).setDepth(300).setScrollFactor(0);

    // Dim overlay
    const overlay = this.add.rectangle(cx, cy, GAME_WIDTH, GAME_HEIGHT, NEON.BG_BLACK, 0.6).setInteractive();
    overlay.on('pointerdown', () => {
      if (this.detailContainer) {
        this.detailContainer.destroy();
        this.detailContainer = null;
      }
    });
    this.detailContainer.add(overlay);

    // Panel background
    const g = this.add.graphics();
    const hw = panelW / 2;
    const hh = panelH / 2;
    const r = 14;

    // Glow border
    const glowColor = getGlowColor(def);
    g.lineStyle(2, glowColor, 0.7);
    g.strokeRoundedRect(cx - hw, cy - hh, panelW, panelH, r);
    g.fillStyle(CODEX.DETAIL_BG, CODEX.DETAIL_BG_ALPHA);
    g.fillRoundedRect(cx - hw, cy - hh, panelW, panelH, r);
    this.detailContainer.add(g);

    // Large sprite
    const texKey = resolveTexKey(this, def.id, def.shape);
    const spriteSize = isBoss ? 120 : 90;
    const sprX = cx - hw + 80;

    // Glow behind sprite
    const sprGlow = this.add.graphics();
    sprGlow.fillStyle(glowColor, 0.12);
    sprGlow.fillCircle(sprX, cy - 20, spriteSize / 2 + 10);
    sprGlow.lineStyle(2, glowColor, 0.4);
    sprGlow.strokeCircle(sprX, cy - 20, spriteSize / 2 + 8);
    this.detailContainer.add(sprGlow);

    const sprite = this.add.sprite(sprX, cy - 20, texKey);
    const sprTexW = sprite.texture.getSourceImage().width;
    sprite.setScale(sprTexW > 0 ? spriteSize / sprTexW : 1);
    this.detailContainer.add(sprite);

    // Text area
    const tl = cx - hw + 160;
    const tr = cx + hw - 16;
    const maxTextW = tr - tl;

    // Name
    const nameColor = isBoss ? NEON_CSS.GOLD : NEON_CSS.UI_ACCENT;
    this.detailContainer.add(
      this.add
        .text(tl, cy - hh + 24, t(`enemy.${def.id}`), {
          fontSize: '28px',
          color: nameColor,
          fontFamily: 'monospace',
          fontStyle: 'bold',
        })
        .setOrigin(0, 0),
    );

    // Category + behavior badge
    const catLabel = def.id.startsWith('boss') ? t('codex.category_boss') : t(`codex.category_${def.category}`);
    const behaviorLabel = t(`behavior.${def.behavior}`);

    this.detailContainer.add(
      this.add
        .text(tl, cy - hh + 58, `${catLabel}  ·  ${behaviorLabel}`, {
          fontSize: '16px',
          color: NEON_CSS.UI_DIM,
          fontFamily: 'monospace',
        })
        .setOrigin(0, 0),
    );

    // Description
    const desc = t(`enemy_desc.${def.id}`);
    this.detailContainer.add(
      this.add
        .text(tl, cy - hh + 84, desc, {
          fontSize: '16px',
          color: NEON_CSS.UI_TEXT,
          fontFamily: 'monospace',
          wordWrap: { width: maxTextW },
          lineSpacing: 4,
        })
        .setOrigin(0, 0),
    );

    // Stats grid
    const statsY = cy + 30;
    const stats = [
      { label: 'HP', value: `${def.baseHp}`, color: NEON_CSS.HEALTH },
      { label: 'ATK', value: `${def.baseDamage}`, color: NEON_CSS.ENEMY_BASIC },
      { label: 'SPD', value: `${def.baseSpeed}`, color: NEON_CSS.UI_ACCENT },
      { label: 'XP', value: `${def.xpValue}`, color: NEON_CSS.XP_BAR },
    ];
    const statSpacing = maxTextW / stats.length;
    stats.forEach((s, i) => {
      const sx = tl + i * statSpacing + statSpacing / 2;
      this.detailContainer!.add(
        this.add
          .text(sx, statsY, s.label, {
            fontSize: '14px',
            color: NEON_CSS.UI_DIM,
            fontFamily: 'monospace',
          })
          .setOrigin(0.5, 0),
      );
      this.detailContainer!.add(
        this.add
          .text(sx, statsY + 18, s.value, {
            fontSize: '22px',
            color: s.color,
            fontFamily: 'monospace',
            fontStyle: 'bold',
          })
          .setOrigin(0.5, 0),
      );
    });

    // Chapter appearance
    const ch = ENEMY_CHAPTER[def.id] ?? 1;
    this.detailContainer.add(
      this.add
        .text(cx, cy + hh - 24, t('codex.chapter', { ch }), {
          fontSize: '14px',
          color: NEON_CSS.GOLD,
          fontFamily: 'monospace',
        })
        .setOrigin(0.5),
    );

    // Fade in
    this.detailContainer.setAlpha(0);
    this.tweens.add({
      targets: this.detailContainer,
      alpha: 1,
      duration: 150,
      ease: 'Power2',
    });
  }
}
