import type { EnemyDef } from '../types/enemy';

export const ENEMY_DEFS: Record<string, EnemyDef> = {
  basic: {
    id: 'basic',
    shape: 'circle',
    baseSize: 12,
    baseSpeed: 40,
    baseHp: 10,
    baseDamage: 5,
    behavior: 'march',
    xpValue: 1,
    colorKey: 'ENEMY_BASIC',
  },
  fast: {
    id: 'fast',
    shape: 'triangle',
    baseSize: 10,
    baseSpeed: 80,
    baseHp: 8,
    baseDamage: 8,
    behavior: 'dash',
    xpValue: 2,
    colorKey: 'ENEMY_FAST',
  },
  tank: {
    id: 'tank',
    shape: 'rect',
    baseSize: 18,
    baseSpeed: 20,
    baseHp: 50,
    baseDamage: 15,
    behavior: 'slow_march',
    xpValue: 3,
    colorKey: 'ENEMY_TANK',
  },
  special: {
    id: 'special',
    shape: 'diamond',
    baseSize: 14,
    baseSpeed: 50,
    baseHp: 20,
    baseDamage: 10,
    behavior: 'zigzag',
    xpValue: 3,
    colorKey: 'ENEMY_SPECIAL',
  },
  splitter: {
    id: 'splitter',
    shape: 'hexagon',
    baseSize: 16,
    baseSpeed: 30,
    baseHp: 30,
    baseDamage: 8,
    behavior: 'split_on_death',
    xpValue: 4,
    colorKey: 'ENEMY_ELITE',
  },
  chaser: {
    id: 'chaser',
    shape: 'triangle',
    baseSize: 12,
    baseSpeed: 55,
    baseHp: 15,
    baseDamage: 12,
    behavior: 'chase',
    xpValue: 3,
    colorKey: 'ENEMY_FAST',
  },
  boss: {
    id: 'boss',
    shape: 'hexagon',
    baseSize: 32,
    baseSpeed: 15,
    baseHp: 500,
    baseDamage: 30,
    behavior: 'boss_chase',
    xpValue: 100,
    colorKey: 'ENEMY_ELITE',
  },
  boss_circle: {
    id: 'boss_circle',
    shape: 'diamond',
    baseSize: 28,
    baseSpeed: 25,
    baseHp: 600,
    baseDamage: 25,
    behavior: 'boss_circle',
    xpValue: 120,
    colorKey: 'ENEMY_SPECIAL',
  },
  boss_burst: {
    id: 'boss_burst',
    shape: 'rect',
    baseSize: 36,
    baseSpeed: 12,
    baseHp: 800,
    baseDamage: 40,
    behavior: 'boss_burst',
    xpValue: 150,
    colorKey: 'ENEMY_TANK',
  },
};
