import type { WeaponDef } from '../types/weapon';

export const WEAPON_DEFS: Record<string, WeaponDef> = {
  energy_shot: {
    id: 'energy_shot',
    name: '에너지 샷',
    projectileType: 'bullet',
    targetMode: 'nearest',
    baseDamage: 10,
    cooldownMs: 800,
    projectileSpeed: 1200,
    projectileCount: 1,
    piercing: 0,
    aoeRadius: 0,
    range: 0,
    maxLevel: 5,
  },
  aura_field: {
    id: 'aura_field',
    name: '오라 필드',
    projectileType: 'aoe',
    targetMode: 'aoe',
    baseDamage: 5,
    cooldownMs: 500,
    projectileSpeed: 0,
    projectileCount: 1,
    piercing: 0,
    aoeRadius: 80,
    range: 0,
    maxLevel: 5,
  },
  laser_beam: {
    id: 'laser_beam',
    name: '레이저 빔',
    projectileType: 'laser',
    targetMode: 'nearest',
    baseDamage: 25,
    cooldownMs: 2000,
    projectileSpeed: 0,
    projectileCount: 1,
    piercing: 99,
    aoeRadius: 0,
    range: 500,
    maxLevel: 5,
  },
  orbit_guard: {
    id: 'orbit_guard',
    name: '회전 가드',
    projectileType: 'orbit',
    targetMode: 'aoe',
    baseDamage: 8,
    cooldownMs: 300,
    projectileSpeed: 0,
    projectileCount: 3,
    piercing: 99,
    aoeRadius: 0,
    range: 100,
    maxLevel: 5,
  },
  shotgun: {
    id: 'shotgun',
    name: '산탄총',
    projectileType: 'bullet',
    targetMode: 'nearest',
    baseDamage: 8,
    cooldownMs: 1200,
    projectileSpeed: 900,
    projectileCount: 5,
    piercing: 0,
    aoeRadius: 0,
    range: 250,
    maxLevel: 5,
  },
  lightning: {
    id: 'lightning',
    name: '체인 라이트닝',
    projectileType: 'chain',
    targetMode: 'nearest',
    baseDamage: 15,
    cooldownMs: 1500,
    projectileSpeed: 0,
    projectileCount: 3,   // chain count
    piercing: 0,
    aoeRadius: 0,
    range: 400,
    maxLevel: 5,
  },
  missile: {
    id: 'missile',
    name: '추적 미사일',
    projectileType: 'homing',
    targetMode: 'nearest',
    baseDamage: 30,
    cooldownMs: 2500,
    projectileSpeed: 200,
    projectileCount: 1,
    piercing: 0,
    aoeRadius: 60,
    range: 0,
    maxLevel: 5,
  },
  bomb: {
    id: 'bomb',
    name: '에너지 폭탄',
    projectileType: 'bomb',
    targetMode: 'aoe',
    baseDamage: 50,
    cooldownMs: 4000,
    projectileSpeed: 0,
    projectileCount: 1,
    piercing: 0,
    aoeRadius: 120,
    range: 0,
    maxLevel: 5,
  },
};
