// ── Tests: DodgeCalc ──

import { describe, it, expect } from "vitest";
import {
  createDodgeState,
  canDodge,
  startDodge,
  tick,
  isInvincible,
  isDashingFn,
  getDashPosition,
  getDashEndPosition,
  registerPerfectDodge,
  isPerfectDodgeWindow,
  addCharge,
  upgradeMaxCharges,
  upgradeCooldown,
  upgradeIFrames,
  getCooldownPercent,
} from "../../src/core/DodgeCalc";

// ════════════════════════════════════════════════════════════════
// § createDodgeState
// ════════════════════════════════════════════════════════════════

describe("createDodgeState", () => {
  it("creates state with default values", () => {
    const s = createDodgeState();
    expect(s.cooldownDuration).toBe(1.5);
    expect(s.iFrameDuration).toBe(0.2);
    expect(s.dashDistance).toBe(100);
    expect(s.dashSpeed).toBe(600);
    expect(s.maxCharges).toBe(2);
    expect(s.chargeRegenDuration).toBe(3.0);
  });

  it("starts with full charges", () => {
    const s = createDodgeState();
    expect(s.charges).toBe(s.maxCharges);
  });

  it("starts with no active timers", () => {
    const s = createDodgeState();
    expect(s.cooldownTimer).toBe(0);
    expect(s.iFrameTimer).toBe(0);
    expect(s.isDashing).toBe(false);
    expect(s.dashProgress).toBe(0);
  });

  it("starts with zero dodge counters", () => {
    const s = createDodgeState();
    expect(s.totalDodges).toBe(0);
    expect(s.perfectDodges).toBe(0);
  });

  it("accepts custom config", () => {
    const s = createDodgeState({
      cooldownDuration: 2.0,
      iFrameDuration: 0.3,
      dashDistance: 150,
      dashSpeed: 800,
      maxCharges: 3,
      chargeRegenDuration: 5.0,
    });
    expect(s.cooldownDuration).toBe(2.0);
    expect(s.iFrameDuration).toBe(0.3);
    expect(s.dashDistance).toBe(150);
    expect(s.dashSpeed).toBe(800);
    expect(s.maxCharges).toBe(3);
    expect(s.charges).toBe(3);
    expect(s.chargeRegenDuration).toBe(5.0);
  });

  it("accepts partial config", () => {
    const s = createDodgeState({ dashSpeed: 900 });
    expect(s.dashSpeed).toBe(900);
    expect(s.cooldownDuration).toBe(1.5); // default
  });
});

// ════════════════════════════════════════════════════════════════
// § canDodge
// ════════════════════════════════════════════════════════════════

describe("canDodge", () => {
  it("returns true when ready and has charges", () => {
    const s = createDodgeState();
    expect(canDodge(s)).toBe(true);
  });

  it("returns false when on cooldown", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(canDodge(s)).toBe(false); // cooldown just started
  });

  it("returns false when no charges remain", () => {
    let s = createDodgeState({ maxCharges: 1 });
    s = startDodge(s, 0);
    // After one dodge with maxCharges=1, charges=0
    // Even after cooldown expires, still no charges
    s = tick(s, 10); // clear cooldown
    expect(s.cooldownTimer).toBe(0);
    // charge should have regenerated by now (10s >> 3s regen)
    // So this will be true again
    expect(canDodge(s)).toBe(true);
  });

  it("returns false when charges are zero and cooldown active", () => {
    let s = createDodgeState({ maxCharges: 1 });
    s = startDodge(s, 0);
    expect(s.charges).toBe(0);
    expect(s.cooldownTimer).toBeGreaterThan(0);
    expect(canDodge(s)).toBe(false);
  });
});

// ════════════════════════════════════════════════════════════════
// § startDodge
// ════════════════════════════════════════════════════════════════

describe("startDodge", () => {
  it("sets isDashing to true", () => {
    const s = startDodge(createDodgeState(), Math.PI / 4);
    expect(s.isDashing).toBe(true);
  });

  it("stores the dash direction", () => {
    const dir = Math.PI / 3;
    const s = startDodge(createDodgeState(), dir);
    expect(s.dashDirection).toBe(dir);
  });

  it("resets dashProgress to 0", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(s.dashProgress).toBe(0);
  });

  it("consumes one charge", () => {
    const base = createDodgeState();
    const s = startDodge(base, 0);
    expect(s.charges).toBe(base.charges - 1);
  });

  it("starts cooldown timer", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(s.cooldownTimer).toBe(s.cooldownDuration);
  });

  it("starts iFrame timer", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(s.iFrameTimer).toBe(s.iFrameDuration);
  });

  it("increments totalDodges", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(s.totalDodges).toBe(1);
  });

  it("returns same state if cannot dodge", () => {
    let s = createDodgeState({ maxCharges: 1 });
    s = startDodge(s, 0); // use the one charge
    const before = s;
    const after = startDodge(s, Math.PI); // should fail
    expect(after).toBe(before); // reference equality — unchanged
  });

  it("does not mutate original state", () => {
    const original = createDodgeState();
    startDodge(original, 0);
    expect(original.charges).toBe(2);
    expect(original.isDashing).toBe(false);
  });
});

// ════════════════════════════════════════════════════════════════
// § tick
// ════════════════════════════════════════════════════════════════

describe("tick", () => {
  it("decrements cooldown timer", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 0.5);
    expect(s.cooldownTimer).toBe(1.0);
  });

  it("cooldown does not go below 0", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 100);
    expect(s.cooldownTimer).toBe(0);
  });

  it("decrements iFrame timer", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 0.1);
    expect(s.iFrameTimer).toBeCloseTo(0.1);
  });

  it("iFrame timer does not go below 0", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 10);
    expect(s.iFrameTimer).toBe(0);
  });

  it("advances dash progress", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 0.05); // 600 * 0.05 = 30px
    expect(s.dashProgress).toBeCloseTo(30);
    expect(s.isDashing).toBe(true);
  });

  it("ends dash when progress reaches distance", () => {
    let s = startDodge(createDodgeState(), 0);
    // dashDistance=100, dashSpeed=600, time = 100/600 ≈ 0.167s
    s = tick(s, 0.2);
    expect(s.isDashing).toBe(false);
    expect(s.dashProgress).toBe(100);
  });

  it("returns same state for dt <= 0", () => {
    const s = createDodgeState();
    expect(tick(s, 0)).toBe(s);
    expect(tick(s, -1)).toBe(s);
  });

  it("regenerates charges over time", () => {
    let s = createDodgeState({ maxCharges: 2, chargeRegenDuration: 3.0 });
    s = startDodge(s, 0); // charges: 2→1
    // Wait for cooldown to clear and charge to regen
    s = tick(s, 5.0); // 5s > 3s regen
    expect(s.charges).toBe(2);
  });

  it("does not exceed maxCharges during regen", () => {
    const s = createDodgeState();
    const after = tick(s, 100);
    expect(after.charges).toBe(s.maxCharges);
  });

  it("regenerates charges one at a time", () => {
    // Use a long regen so we can control timing precisely
    let s = createDodgeState({ maxCharges: 2, chargeRegenDuration: 5.0 });
    s = startDodge(s, 0); // 2→1 charge
    // Tick just enough for cooldown to clear but NOT enough for a full regen cycle
    s = tick(s, 1.6); // cooldown cleared (1.5s), regen started but not done (5s needed)
    expect(s.charges).toBe(1); // still 1 — regen hasn't completed
    // Dodge again
    s = startDodge(s, 0); // 1→0
    // Now at 0 charges. Tick 5.1s — enough for exactly 1 regen
    s = tick(s, 5.1);
    expect(s.charges).toBe(1); // regenerated 1, not 2
  });
});

// ════════════════════════════════════════════════════════════════
// § isInvincible
// ════════════════════════════════════════════════════════════════

describe("isInvincible", () => {
  it("false when not dodging", () => {
    expect(isInvincible(createDodgeState())).toBe(false);
  });

  it("true immediately after dodge", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(isInvincible(s)).toBe(true);
  });

  it("false after iFrames expire", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 0.3); // iFrame=0.2s, 0.3 > 0.2
    expect(isInvincible(s)).toBe(false);
  });

  it("true during iFrame window", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 0.1); // 0.1 < 0.2
    expect(isInvincible(s)).toBe(true);
  });
});

// ════════════════════════════════════════════════════════════════
// § isDashingFn
// ════════════════════════════════════════════════════════════════

describe("isDashingFn", () => {
  it("false when idle", () => {
    expect(isDashingFn(createDodgeState())).toBe(false);
  });

  it("true during dash", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(isDashingFn(s)).toBe(true);
  });

  it("false after dash completes", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 1.0); // well past dash duration
    expect(isDashingFn(s)).toBe(false);
  });
});

// ════════════════════════════════════════════════════════════════
// § getDashPosition
// ════════════════════════════════════════════════════════════════

describe("getDashPosition", () => {
  it("returns start position when not dashing", () => {
    const s = createDodgeState();
    const pos = getDashPosition(s, 100, 200);
    expect(pos.x).toBe(100);
    expect(pos.y).toBe(200);
  });

  it("moves right when direction is 0", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 0.05); // progress = 30px
    const pos = getDashPosition(s, 100, 200);
    expect(pos.x).toBeCloseTo(130);
    expect(pos.y).toBeCloseTo(200);
  });

  it("moves down when direction is PI/2", () => {
    let s = startDodge(createDodgeState(), Math.PI / 2);
    s = tick(s, 0.05); // progress = 30px
    const pos = getDashPosition(s, 100, 200);
    expect(pos.x).toBeCloseTo(100);
    expect(pos.y).toBeCloseTo(230);
  });

  it("moves diagonally at 45 degrees", () => {
    let s = startDodge(createDodgeState(), Math.PI / 4);
    s = tick(s, 0.05); // progress = 30px
    const pos = getDashPosition(s, 0, 0);
    const expected = 30 * Math.cos(Math.PI / 4);
    expect(pos.x).toBeCloseTo(expected);
    expect(pos.y).toBeCloseTo(expected);
  });
});

// ════════════════════════════════════════════════════════════════
// § getDashEndPosition
// ════════════════════════════════════════════════════════════════

describe("getDashEndPosition", () => {
  it("calculates end position for rightward dash", () => {
    const pos = getDashEndPosition(100, 200, 0, 100);
    expect(pos.x).toBeCloseTo(200);
    expect(pos.y).toBeCloseTo(200);
  });

  it("calculates end position for upward dash", () => {
    const pos = getDashEndPosition(100, 200, -Math.PI / 2, 50);
    expect(pos.x).toBeCloseTo(100);
    expect(pos.y).toBeCloseTo(150);
  });

  it("calculates end position for diagonal dash", () => {
    const pos = getDashEndPosition(0, 0, Math.PI / 4, 100);
    const expected = 100 * Math.cos(Math.PI / 4);
    expect(pos.x).toBeCloseTo(expected);
    expect(pos.y).toBeCloseTo(expected);
  });
});

// ════════════════════════════════════════════════════════════════
// § registerPerfectDodge
// ════════════════════════════════════════════════════════════════

describe("registerPerfectDodge", () => {
  it("increments perfectDodges counter", () => {
    const s = createDodgeState();
    const after = registerPerfectDodge(s);
    expect(after.perfectDodges).toBe(1);
  });

  it("can be called multiple times", () => {
    let s = createDodgeState();
    s = registerPerfectDodge(s);
    s = registerPerfectDodge(s);
    s = registerPerfectDodge(s);
    expect(s.perfectDodges).toBe(3);
  });

  it("does not mutate original state", () => {
    const original = createDodgeState();
    registerPerfectDodge(original);
    expect(original.perfectDodges).toBe(0);
  });
});

// ════════════════════════════════════════════════════════════════
// § isPerfectDodgeWindow
// ════════════════════════════════════════════════════════════════

describe("isPerfectDodgeWindow", () => {
  it("false when not in iFrames", () => {
    const s = createDodgeState();
    expect(isPerfectDodgeWindow(s, 10)).toBe(false);
  });

  it("true when in iFrames and enemy within 30px", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(isPerfectDodgeWindow(s, 25)).toBe(true);
  });

  it("true when enemy exactly at 30px", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(isPerfectDodgeWindow(s, 30)).toBe(true);
  });

  it("false when enemy beyond 30px", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(isPerfectDodgeWindow(s, 31)).toBe(false);
  });

  it("false after iFrames expire even if enemy close", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 0.3);
    expect(isPerfectDodgeWindow(s, 10)).toBe(false);
  });
});

// ════════════════════════════════════════════════════════════════
// § addCharge
// ════════════════════════════════════════════════════════════════

describe("addCharge", () => {
  it("adds one charge", () => {
    let s = createDodgeState();
    s = startDodge(s, 0); // 2→1
    s = addCharge(s);
    expect(s.charges).toBe(2);
  });

  it("does not exceed maxCharges", () => {
    const s = createDodgeState();
    const after = addCharge(s);
    expect(after.charges).toBe(s.maxCharges);
  });

  it("does not mutate original", () => {
    let s = createDodgeState();
    s = startDodge(s, 0);
    const chargesBefore = s.charges;
    addCharge(s);
    expect(s.charges).toBe(chargesBefore);
  });
});

// ════════════════════════════════════════════════════════════════
// § upgradeMaxCharges
// ════════════════════════════════════════════════════════════════

describe("upgradeMaxCharges", () => {
  it("increases maxCharges", () => {
    const s = upgradeMaxCharges(createDodgeState(), 4);
    expect(s.maxCharges).toBe(4);
  });

  it("grants bonus charges equal to the increase", () => {
    const base = createDodgeState(); // maxCharges=2, charges=2
    const s = upgradeMaxCharges(base, 4);
    expect(s.charges).toBe(4); // 2 + (4-2) = 4
  });

  it("returns same state if newMax <= current", () => {
    const s = createDodgeState();
    expect(upgradeMaxCharges(s, 1)).toBe(s);
    expect(upgradeMaxCharges(s, 2)).toBe(s);
  });
});

// ════════════════════════════════════════════════════════════════
// § upgradeCooldown
// ════════════════════════════════════════════════════════════════

describe("upgradeCooldown", () => {
  it("reduces cooldown duration", () => {
    const s = upgradeCooldown(createDodgeState(), 0.5);
    expect(s.cooldownDuration).toBe(1.0);
  });

  it("does not go below 0.1s", () => {
    const s = upgradeCooldown(createDodgeState(), 100);
    expect(s.cooldownDuration).toBe(0.1);
  });

  it("stacks reductions", () => {
    let s = createDodgeState();
    s = upgradeCooldown(s, 0.3);
    s = upgradeCooldown(s, 0.3);
    expect(s.cooldownDuration).toBeCloseTo(0.9);
  });
});

// ════════════════════════════════════════════════════════════════
// § upgradeIFrames
// ════════════════════════════════════════════════════════════════

describe("upgradeIFrames", () => {
  it("extends iFrame duration by bonus milliseconds", () => {
    const s = upgradeIFrames(createDodgeState(), 50);
    expect(s.iFrameDuration).toBeCloseTo(0.25); // 0.2 + 0.05
  });

  it("stacks upgrades", () => {
    let s = createDodgeState();
    s = upgradeIFrames(s, 100);
    s = upgradeIFrames(s, 100);
    expect(s.iFrameDuration).toBeCloseTo(0.4); // 0.2 + 0.1 + 0.1
  });
});

// ════════════════════════════════════════════════════════════════
// § getCooldownPercent
// ════════════════════════════════════════════════════════════════

describe("getCooldownPercent", () => {
  it("returns 0 when ready", () => {
    expect(getCooldownPercent(createDodgeState())).toBe(0);
  });

  it("returns 1 immediately after dodge", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(getCooldownPercent(s)).toBe(1);
  });

  it("returns ~0.5 halfway through cooldown", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 0.75); // half of 1.5s cooldown
    expect(getCooldownPercent(s)).toBeCloseTo(0.5);
  });

  it("returns 0 after cooldown expires", () => {
    let s = startDodge(createDodgeState(), 0);
    s = tick(s, 2.0);
    expect(getCooldownPercent(s)).toBe(0);
  });

  it("clamps to 0-1 range", () => {
    const s = createDodgeState();
    const pct = getCooldownPercent(s);
    expect(pct).toBeGreaterThanOrEqual(0);
    expect(pct).toBeLessThanOrEqual(1);
  });
});

// ════════════════════════════════════════════════════════════════
// § Dash physics integration
// ════════════════════════════════════════════════════════════════

describe("dash physics integration", () => {
  it("dash duration equals distance / speed", () => {
    const s = createDodgeState({ dashDistance: 120, dashSpeed: 600 });
    const expectedDuration = 120 / 600; // 0.2s
    let state = startDodge(s, 0);
    // Just before completion
    state = tick(state, expectedDuration - 0.001);
    expect(state.isDashing).toBe(true);
    // Just after completion
    state = tick(state, 0.01);
    expect(state.isDashing).toBe(false);
  });

  it("player cannot change direction mid-dash", () => {
    let s = startDodge(createDodgeState(), Math.PI / 4);
    s = tick(s, 0.05);
    // Attempting another dodge while dashing should fail (on cooldown)
    const after = startDodge(s, Math.PI);
    expect(after.dashDirection).toBe(Math.PI / 4); // unchanged
  });

  it("iFrames start on dodge initiation and last iFrameDuration", () => {
    const s = startDodge(createDodgeState(), 0);
    expect(s.iFrameTimer).toBe(0.2);
    const after = tick(s, 0.2);
    expect(after.iFrameTimer).toBe(0);
  });

  it("full dodge cycle: dodge → dash ends → cooldown expires → dodge again", () => {
    let s = createDodgeState();
    // First dodge
    s = startDodge(s, 0);
    expect(s.isDashing).toBe(true);
    expect(s.charges).toBe(1);

    // Wait for dash to end + cooldown to expire
    s = tick(s, 2.0);
    expect(s.isDashing).toBe(false);
    expect(s.cooldownTimer).toBe(0);

    // Second dodge should work (still has 1 charge)
    expect(canDodge(s)).toBe(true);
    s = startDodge(s, Math.PI);
    expect(s.isDashing).toBe(true);
    expect(s.totalDodges).toBe(2);
  });
});
