import Phaser from 'phaser';
import type { EnemyDef, EnemyAttackStyle, EnemyCategory } from '../types/enemy';
import { BALANCE, VISUAL } from '../config/balance';
import { NEON, BOSS_AERO_COLORS } from '../config/colors';
import { GAME_WIDTH } from '../config/game-config';
import type { SeededRandom } from '../core/SeededRandom';
import {
  calculateHpScale,
  calculateSpeedScale,
  calculateDamageScale,
  getEliteMultipliers,
  calculateEnemyHp,
  calculateEnemySpeed,
  calculateEnemyDamage,
  calculateEnemyXp,
  calculateDisplaySize,
  calculateSpriteScale,
  calculateHitRadius,
  isBossBehavior,
} from '../core/EnemyScalingCalc';
import {
  createBossPhaseState,
  shouldTransitionToPhase2,
  transitionToPhase2,
  shouldTransitionToPhase3,
  transitionToPhase3,
  tickInvulnerability,
  isInvulnerable,
  getPhase2Stats,
  type BossPhaseState,
} from '../core/BossPhaseCalc';
import { createEagleDiveState, type EagleDiveState } from '../core/BossAeroCalc';
import { getBossGlowParams, getEliteGlowParams, getStatusTint } from '../core/PostFXCalc';
import {
  calculateMarchVelocity,
  calculateSlowChaseVelocity,
  calculateZigzagVelocity,
  calculateDashVelocity,
  advanceDashState,
  calculateChaseVelocity,
  calculateSplitVelocity,
  calculateShootBehavior,
  calculateTeleportJump,
  calculateBossChaseVelocity,
  calculateBossOrbitVelocity,
  calculateBossBurstVelocity,
  advanceBurstState,
  applyFrostSlow,
  clampToWorldBounds,
} from '../core/EnemyBehaviorCalc';

/** Map enemy shape to the texture key generated by TextureFactory */
const SHAPE_TO_TEXTURE: Record<string, string> = {
  circle: 'enemy_circle',
  triangle: 'enemy_triangle',
  rect: 'enemy_rect',
  diamond: 'enemy_diamond',
  hexagon: 'enemy_hexagon',
};

/** Per-enemy-id texture overrides — pixel art sprites */
const ID_TEXTURES: Record<string, string> = {
  // T1 (48x48)
  basic: 't1_moth',
  fast: 't1_rat',
  special: 't1_butterfly',
  swarm: 't1_ant',
  chaser: 't1_cat',
  shooter: 't1_jelly',
  // T2 (72x72)
  tank: 'opt_t2_ape',
  splitter: 'opt_t2_kite',
  guardian: 'opt_t2_lion',
  sniper_enemy: 'opt_t2_koi',
  teleporter: 'opt_t2_pango',
};

/**
 * Map enemy IDs to CraftPix spritesheet animation indices.
 * The number maps to enemyN_* animation keys (e.g., enemy1_walk, enemy2_idle).
 */
const ENEMY_ANIM_MAP: Record<string, number> = {
  // T1 enemies → CraftPix business enemies 1-6
  basic: 1,
  fast: 2,
  special: 3,
  swarm: 4,
  chaser: 5,
  shooter: 6,
};

/**
 * Map boss enemy IDs to CraftPix boss spritesheet indices.
 */
const BOSS_ANIM_MAP: Record<string, number> = {
  boss: 1,
  boss_circle: 2,
  boss_burst: 3,
};

/** Enemy element assignment by ID */
const ENEMY_ELEMENT_MAP: Record<string, string> = {
  // T1
  fast: 'WIND',
  special: 'FIRE',
  chaser: 'FIRE',
  shooter: 'WIND',
  // T2
  tank: 'EARTH',
  sniper_enemy: 'LIGHT',
  splitter: 'WATER',
  guardian: 'EARTH',
  teleporter: 'LIGHT',
  // Bosses
  boss: 'DARK',
  boss_circle: 'DARK',
  boss_burst: 'DARK',
};

/** Default boss textures (fallback when stage has no specific mapping) */
const BOSS_TEXTURES_DEFAULT: Record<string, string> = {
  boss: 'boss_terra_large',
  boss_circle: 'boss_blaze_large',
  boss_burst: 'boss_harvester_large',
};

/**
 * Stage-specific boss textures — each chapter's boss gets its unique _large sprite.
 * Stage 2=Aero, 4=Hydra, 6=Blaze, 8=Terra, 10=Lumen, 12=Umbra, 14=Aero(reuse), 16=Harvester.
 */
const BOSS_STAGE_TEXTURES: Record<number, string> = {
  2: 'boss_aero_large',
  4: 'boss_hydra_large',
  6: 'boss_blaze_large',
  8: 'boss_terra_large',
  10: 'boss_lumen_large',
  12: 'boss_umbra_large',
  14: 'boss_aero_large',
  16: 'boss_harvester_large',
};

export class Enemy extends Phaser.Physics.Arcade.Sprite {
  public hp = 0;
  public maxHp = 0;
  public damage = 0;
  public speed = 0;
  public xpValue = 0;
  public defId = '';
  public isElite = false;
  public colorKey = '';
  public behavior = '';
  public isSplitChild = false;
  public knockbackImmune = false;
  public hitRadius = 20;
  public element: string | null = null;
  public direction: 'left' | 'right' = 'left'; // Hill Defense: spawn side
  public category: EnemyCategory = 'ground'; // Side-view: ground or air

  // Deterministic RNG for combat-relevant randomness (TASK-011 RT)
  public rng: SeededRandom | null = null;

  // Ultimate debuff state (freeze/stun)
  public speedMultiplier = 1;
  public frozen = false;

  // Passive debuff state
  public burnDamage = 0; // damage per burn tick (0 = no burn)
  public burnRemainingMs = 0; // ms remaining on burn
  public burnTickTimer = 0; // ms until next burn tick
  public frostRemainingMs = 0; // ms remaining on frost slow
  public frostSlowMult = 1; // speed multiplier from frost (1 = none)

  // Attack style state
  public attackStyle: EnemyAttackStyle = 'melee';
  public attackInterval: number = BALANCE.ENEMY_BEHAVIOR.defaultAttackInterval;
  public attackTimer = 0;
  public isAttackingBase = false;
  public projectileSpeed = 200;
  public isRangedStopped = false; // ranged: stopped at firing position

  // Zigzag state
  private zigzagAngle = 0;
  private zigzagDir = 1;
  private readonly zigzagSpeed = BALANCE.ENEMY_BEHAVIOR.zigzagSpeed; // horizontal oscillation px/s
  private readonly zigzagFreq = 2.5; // oscillations per second

  // Air enemy sine-wave Y oscillation
  private airSineAngle = 0;
  private airSpawnY = 0; // original Y at spawn, used as oscillation center

  // Dash state
  private dashTimer = 0;
  private readonly dashInterval = BALANCE.ENEMY_BEHAVIOR.dashInterval; // ms between dashes
  private readonly dashDuration = BALANCE.ENEMY_BEHAVIOR.dashDuration; // ms per dash burst
  private isDashing = false;

  // Knockback state
  private knockbackTimer = 0;

  // Hit flash (manual frame counter, no delayedCall)
  private flashTimer = 0;

  // Spritesheet animation state
  private animIndex = 0; // index into ENEMY_ANIM_MAP or BOSS_ANIM_MAP (0 = no anim)
  private animIsBoss = false;
  private currentAnimState: 'idle' | 'walk' | 'attack' | 'hurt' | 'death' | 'none' = 'none';

  // Boss circle state
  private circleAngle = 0;
  private circleCenterX = 0;
  private circleCenterY = 0;
  public circlePhase: 'approach' | 'orbit' = 'approach';

  // Boss burst state
  private burstTimer = 0;
  private burstPhase: 'idle' | 'charge' = 'idle';
  private burstIdleDuration: number = BALANCE.ENEMY_BEHAVIOR.burstIdleDuration; // ms pause between charges (mutable for Phase 2)
  private burstChargeDuration: number = BALANCE.ENEMY_BEHAVIOR.burstChargeDuration; // ms per charge burst (mutable for Phase 2)

  // Boss phase transition state (TASK-121)
  public bossPhaseState: BossPhaseState = createBossPhaseState();

  // Boss Aero: Eagle Dive state (TASK-048)
  public eagleDiveState: EagleDiveState = createEagleDiveState();

  // Teleport state
  private teleportTimer = 0;
  private readonly teleportInterval = BALANCE.ENEMY_BEHAVIOR.teleportInterval; // ms between teleports

  constructor(scene: Phaser.Scene, x: number, y: number) {
    super(scene, x, y, 'enemy_circle');
    // Pool handles adding to scene/physics world
  }

  activate(
    def: EnemyDef,
    x: number,
    y: number,
    minutesElapsed: number,
    elite = false,
    stageHpMult = 1,
    stageSpeedMult = 1,
    stageDamageMult = 1,
    direction: 'left' | 'right' = 'left',
    stage = 1,
  ): void {
    this.defId = def.id;
    this.isElite = elite;
    this.colorKey = def.colorKey;
    this.behavior = def.behavior;
    this.category = def.category;
    this.isSplitChild = false;

    const hpScale = calculateHpScale(minutesElapsed, BALANCE.DIFFICULTY.hpScalePerMin);
    const spdScale = calculateSpeedScale(
      minutesElapsed,
      BALANCE.DIFFICULTY.speedScalePerMin,
      BALANCE.DIFFICULTY.maxSpeedMultiplier,
    );
    const dmgScale = calculateDamageScale(minutesElapsed, BALANCE.DIFFICULTY.damageScalePerMin);

    const eliteMult = getEliteMultipliers(elite, def.knockbackImmune ?? false);
    this.knockbackImmune = eliteMult.knockbackImmune;
    const isBoss = isBossBehavior(def.behavior);

    this.hp = calculateEnemyHp(
      def.baseHp,
      hpScale,
      eliteMult.hpMult,
      stageHpMult,
      isBoss,
      BALANCE.DIFFICULTY.maxBossHp,
    );
    this.maxHp = this.hp;
    this.damage = calculateEnemyDamage(
      def.baseDamage,
      dmgScale,
      eliteMult.damageMult,
      stageDamageMult,
      isBoss,
      BALANCE.DIFFICULTY.maxBossAtk,
    );
    this.speed = calculateEnemySpeed(def.baseSpeed, spdScale, stageSpeedMult);
    this.xpValue = calculateEnemyXp(def.xpValue, eliteMult.xpMult);

    // Attack style
    this.attackStyle = def.attackStyle ?? 'melee';
    this.attackInterval = def.attackInterval ?? BALANCE.ENEMY_BEHAVIOR.defaultAttackInterval;
    this.attackTimer = 0;
    this.isAttackingBase = false;
    this.projectileSpeed = def.projectileSpeed ?? 200;
    this.isRangedStopped = false;

    // Set texture: boss (stage-aware) → ID override → shape mapping (with PNG existence fallback)
    const bossStageTex = BOSS_STAGE_TEXTURES[stage];
    const bossDefaultTex = BOSS_TEXTURES_DEFAULT[def.id];
    const idTex = ID_TEXTURES[def.id];
    const shapeTex = SHAPE_TO_TEXTURE[def.shape] ?? 'enemy_circle';
    let texKey: string;
    if (isBoss && bossStageTex && this.scene.textures.exists(bossStageTex)) {
      texKey = bossStageTex;
    } else if (bossDefaultTex && this.scene.textures.exists(bossDefaultTex)) {
      texKey = bossDefaultTex;
    } else if (idTex && this.scene.textures.exists(idTex)) {
      texKey = idTex;
    } else {
      texKey = shapeTex;
    }
    this.setTexture(texKey);

    // Size correction: scale pixel art to visible display size
    // Target: T1(48px)→96px, T2(72px)→120px, Boss _large(384px)→384px (1:1 crisp)
    const texW = this.texture.getSourceImage().width;
    if (texW > 0) {
      const displaySize = calculateDisplaySize(texW, isBoss, elite, BALANCE.STAGE.bossDisplaySize);
      const scale = calculateSpriteScale(displaySize, texW);
      this.setScale(scale);
      this.hitRadius = calculateHitRadius(displaySize, isBoss, elite, true);
    } else {
      // Fallback when no valid sprite
      if (isBoss) {
        this.setScale(2);
      } else if (elite) {
        this.setScale(2);
      } else {
        this.setScale(1);
      }
      this.hitRadius = calculateHitRadius(0, isBoss, elite, false);
    }

    this.setPosition(x, y);
    this.setActive(true);
    this.setVisible(true);
    this.direction = direction;
    // Street Defense: enemies come from right, face left toward barrier
    this.setFlipX(direction === 'right');
    const body = this.body as Phaser.Physics.Arcade.Body;
    body.enable = true;
    body.reset(x, y);

    // Update physics body circle to match hitRadius for player↔enemy overlap
    if (body) {
      body.setCircle(this.hitRadius);
      const offset = (this.displayWidth - this.hitRadius * 2) / 2;
      body.setOffset(offset, offset);
    }

    // Element assignment based on enemy type
    this.element = ENEMY_ELEMENT_MAP[def.id] ?? null;

    // Reset behavior state — use SeededRandom for combat-relevant values (TASK-011 RT)
    const rn = this.rng;
    this.zigzagAngle = (rn ? rn.next() : Math.random()) * Math.PI * 2;
    this.zigzagDir = (rn ? rn.next() : Math.random()) < 0.5 ? 1 : -1;
    this.airSineAngle = (rn ? rn.next() : Math.random()) * Math.PI * 2;
    this.airSpawnY = y;
    this.dashTimer = 0;
    this.isDashing = false;
    this.knockbackTimer = 0;
    this.speedMultiplier = 1;
    this.frozen = false;
    // Passive debuffs
    this.burnDamage = 0;
    this.burnRemainingMs = 0;
    this.burnTickTimer = 0;
    this.frostRemainingMs = 0;
    this.frostSlowMult = 1;
    // Boss circle
    this.circleAngle = 0;
    this.circleCenterX = GAME_WIDTH / 2;
    this.circleCenterY = BALANCE.ENEMY_BEHAVIOR.bossOrbitCenterY;
    this.circlePhase = 'approach';
    // Boss burst
    this.burstTimer = 0;
    this.burstPhase = 'idle';
    this.burstIdleDuration = BALANCE.ENEMY_BEHAVIOR.burstIdleDuration;
    this.burstChargeDuration = BALANCE.ENEMY_BEHAVIOR.burstChargeDuration;
    // Boss phase transition (TASK-121)
    this.bossPhaseState = createBossPhaseState();
    // Boss Aero: Eagle Dive (TASK-048)
    this.eagleDiveState = createEagleDiveState();
    // Teleport
    this.teleportTimer = 0;

    // Spritesheet animation: determine if this enemy has CraftPix animations
    this.animIsBoss = isBoss;
    this.currentAnimState = 'none';
    if (isBoss && BOSS_ANIM_MAP[def.id] !== undefined) {
      this.animIndex = BOSS_ANIM_MAP[def.id];
    } else if (ENEMY_ANIM_MAP[def.id] !== undefined) {
      this.animIndex = ENEMY_ANIM_MAP[def.id];
    } else {
      this.animIndex = 0;
    }

    // Start walk animation if available
    if (this.animIndex > 0) {
      this.tryPlayAnim('walk');
    }

    // PostFX: Boss/Elite glow (WebGL only) — driven by PostFXCalc (TASK-028)
    this.clearPostFXGlow();
    if (isBoss && this.preFX) {
      const params = getBossGlowParams(false, BALANCE.POSTFX);
      this.preFX.addGlow(
        params.color,
        params.outerStrength,
        params.innerStrength,
        false,
        params.quality,
        params.distance,
      );
    } else if (elite && this.preFX) {
      const params = getEliteGlowParams(BALANCE.POSTFX);
      this.preFX.addGlow(
        params.color,
        params.outerStrength,
        params.innerStrength,
        false,
        params.quality,
        params.distance,
      );
    }
  }

  clearPostFXGlow(): void {
    if (this.preFX) {
      this.preFX.clear();
    }
  }

  /** Upgrade glow to phase 3 (gold glow for Aero) — TASK-048 */
  applyPhase3Glow(): void {
    this.clearPostFXGlow();
    if (this.preFX) {
      // Gold glow for Phase 3 (using bossPhase2Glow parameters with gold color)
      const params = getBossGlowParams(true, BALANCE.POSTFX);
      this.preFX.addGlow(
        BOSS_AERO_COLORS.EAGLE_SILHOUETTE, // gold color for Phase 3
        params.outerStrength,
        params.innerStrength,
        false,
        params.quality,
        params.distance,
      );
    }
  }

  /** Upgrade glow to phase 2 (stronger red glow) — driven by PostFXCalc (TASK-028) */
  applyPhase2Glow(): void {
    this.clearPostFXGlow();
    if (this.preFX) {
      const params = getBossGlowParams(true, BALANCE.POSTFX);
      this.preFX.addGlow(
        params.color,
        params.outerStrength,
        params.innerStrength,
        false,
        params.quality,
        params.distance,
      );
    }
  }

  deactivate(): void {
    this.setActive(false);
    this.setVisible(false);
    // Stop any running animation
    if (this.anims && this.anims.isPlaying) {
      this.stop();
    }
    this.currentAnimState = 'none';
    this.clearPostFXGlow();
    const body = this.body as Phaser.Physics.Arcade.Body;
    body.enable = false;
    body.setVelocity(0, 0);
  }

  /**
   * Apply downward movement based on behavior.
   * Called by RunScene each frame (delta in ms).
   */
  applyKnockback(fromX: number, fromY: number): void {
    if (!this.active || this.knockbackImmune) return;
    const body = this.body as Phaser.Physics.Arcade.Body;
    const angle = Math.atan2(this.y - fromY, this.x - fromX);
    const force = BALANCE.COMBAT.knockbackForce;
    body.setVelocity(Math.cos(angle) * force, Math.sin(angle) * force);
    this.knockbackTimer = BALANCE.COMBAT.knockbackDuration;
  }

  applyMovement(delta: number, targetX?: number, targetY?: number): void {
    if (!this.active) return;
    const body = this.body as Phaser.Physics.Arcade.Body;

    // Frozen/stunned: no movement at all
    if (this.frozen || this.speedMultiplier <= 0) {
      body.setVelocity(0, 0);
      return;
    }

    // Tick frost slow + status tint — driven by PostFXCalc (TASK-028)
    if (this.frostRemainingMs > 0) {
      this.frostRemainingMs -= delta;
      this.setTint(getStatusTint('freeze', BALANCE.POSTFX).color);
      if (this.frostRemainingMs <= 0) {
        this.frostRemainingMs = 0;
        this.frostSlowMult = 1;
        this.clearTint();
      }
    }
    // Burn tint (overrides frost if both active)
    if (this.burnRemainingMs > 0) {
      this.setTint(getStatusTint('burn', BALANCE.POSTFX).color);
    } else if (this.frostRemainingMs <= 0 && this.burnRemainingMs <= 0) {
      // Clear any status tint if no active effects (unless boss phase2)
      if (!this.bossPhaseState || this.bossPhaseState.phase < 2) {
        // Don't clear boss phase2 tint
      }
    }

    // Melee enemies attacking base: stay in place
    if (this.isAttackingBase) {
      body.setVelocity(0, 0);
      return;
    }

    // During knockback, skip normal movement
    if (this.knockbackTimer > 0) {
      this.knockbackTimer -= delta;
      return;
    }

    const dt = delta / 1000; // seconds

    switch (this.behavior) {
      case 'march':
      case 'slow_march': {
        const v = calculateMarchVelocity(this.speed, this.direction);
        body.setVelocity(v.vx, v.vy);
        break;
      }
      case 'slow_chase': {
        const r = calculateSlowChaseVelocity(
          this.speed,
          this.x,
          this.y,
          targetX,
          targetY,
          this.zigzagAngle,
          this.zigzagFreq,
          dt,
        );
        this.zigzagAngle = r.newZigzagAngle;
        body.setVelocity(r.velocity.vx, r.velocity.vy);
        break;
      }
      case 'zigzag': {
        const r = calculateZigzagVelocity(
          this.speed,
          this.zigzagAngle,
          this.zigzagSpeed,
          this.zigzagDir,
          this.zigzagFreq,
          dt,
          this.direction,
        );
        this.zigzagAngle = r.newZigzagAngle;
        body.setVelocity(r.velocity.vx, r.velocity.vy);
        break;
      }
      case 'dash': {
        const newState = advanceDashState(
          { timer: this.dashTimer, isDashing: this.isDashing },
          this.dashInterval,
          this.dashDuration,
          delta,
        );
        this.dashTimer = newState.timer;
        this.isDashing = newState.isDashing;
        const v = calculateDashVelocity(this.speed, this.isDashing, this.direction);
        body.setVelocity(v.vx, v.vy);
        break;
      }
      case 'chase': {
        const v = calculateChaseVelocity(this.speed, this.x, this.y, targetX, targetY);
        body.setVelocity(v.vx, v.vy);
        break;
      }
      case 'split_on_death': {
        const v = calculateSplitVelocity(this.speed, this.direction);
        body.setVelocity(v.vx, v.vy);
        break;
      }
      case 'shoot': {
        // Ranged stop position: ~120px before barrier threshold
        // Street Defense: enemies come from right, so stop 120px right of barrier
        const rangedStopX = BALANCE.BASE.leftReachX + BALANCE.ENEMY_BEHAVIOR.rangedStopXOffset;
        const r = calculateShootBehavior(
          this.speed,
          this.y,
          BALANCE.BASE.y - 200, // street defense: ranged Y threshold above ground
          this.isRangedStopped,
          this.zigzagAngle,
          this.zigzagFreq,
          dt,
          this.direction,
          this.x,
          rangedStopX,
        );
        this.isRangedStopped = r.newIsRangedStopped;
        this.zigzagAngle = r.newZigzagAngle;
        body.setVelocity(r.velocity.vx, r.velocity.vy);
        break;
      }
      case 'teleport': {
        // Slow approach + periodic teleport forward (toward barrier on left)
        this.teleportTimer += delta;
        // Street Defense: always moving left toward barrier
        body.setVelocity(-this.speed * 0.5, 0);
        if (this.teleportTimer >= this.teleportInterval) {
          this.teleportTimer = 0;
          const rng2 = this.rng;
          const jump = calculateTeleportJump(
            this.x,
            this.y,
            GAME_WIDTH,
            BALANCE.ENEMY_BEHAVIOR.teleportJumpYMin,
            BALANCE.ENEMY_BEHAVIOR.teleportJumpYRange,
            BALANCE.ENEMY_BEHAVIOR.teleportJumpXRange,
            rng2 ? rng2.next() : Math.random(),
            rng2 ? rng2.next() : Math.random(),
          );
          // Phaser-specific position + blink effect
          this.setPosition(jump.newX, jump.newY);
          body.reset(this.x, this.y);
          this.setAlpha(0.2);
          this.scene.tweens.add({
            targets: this,
            alpha: 1,
            duration: 200,
            ease: 'Linear',
          });
        }
        break;
      }
      case 'boss_chase': {
        const trackMult = this.bossPhaseState.phase === 2 ? BALANCE.BOSS_PHASE.phase2ChaseTrackingMult * 0.02 : 0.02;
        const v = calculateBossChaseVelocity(this.speed, this.x, targetX, this.direction, targetY, this.y, trackMult);
        body.setVelocity(v.vx, v.vy);
        break;
      }
      case 'boss_circle': {
        const orbitSpd =
          this.bossPhaseState.phase === 2 ? BALANCE.BOSS_PHASE.phase2OrbitSpeed : BALANCE.ENEMY_BEHAVIOR.bossOrbitSpeed;
        const r = calculateBossOrbitVelocity(
          this.speed,
          this.x,
          this.y,
          this.circleCenterX,
          this.circleCenterY,
          this.circleAngle,
          BALANCE.ENEMY_BEHAVIOR.bossOrbitRadius,
          orbitSpd,
          this.circlePhase,
          dt,
        );
        this.circlePhase = r.newPhase;
        this.circleAngle = r.newAngle;
        body.setVelocity(r.velocity.vx, r.velocity.vy);
        break;
      }
      case 'boss_burst': {
        // Phase 3: zigzag movement instead of burst pattern
        if (this.bossPhaseState.phase === 3) {
          const r = calculateZigzagVelocity(
            this.speed,
            this.zigzagAngle,
            this.zigzagSpeed,
            this.zigzagDir,
            this.zigzagFreq,
            dt,
            this.direction,
          );
          this.zigzagAngle = r.newZigzagAngle;
          body.setVelocity(r.velocity.vx, r.velocity.vy);
        } else {
          const v = calculateBossBurstVelocity(this.speed, this.burstPhase, this.direction);
          body.setVelocity(v.vx, v.vy);
          const newBurst = advanceBurstState(
            { timer: this.burstTimer, phase: this.burstPhase },
            this.burstIdleDuration,
            this.burstChargeDuration,
            delta,
          );
          this.burstTimer = newBurst.timer;
          this.burstPhase = newBurst.phase;
        }
        break;
      }
      default: {
        if (this.direction === 'left') {
          body.setVelocity(this.speed, 0);
        } else if (this.direction === 'right') {
          body.setVelocity(-this.speed, 0);
        } else {
          body.setVelocity(0, this.speed);
        }
        break;
      }
    }

    // Side-view Y constraints based on category
    if (this.category === 'ground') {
      // Ground enemies: lock Y to spawn position (floor), no vertical movement
      body.setVelocityY(0);
      this.y = this.airSpawnY; // airSpawnY stores original spawn Y for both categories
    } else if (this.category === 'air') {
      // Air enemies: add gentle sine-wave Y oscillation around spawn height
      this.airSineAngle += 1.5 * Math.PI * (delta / 1000); // ~0.75 Hz oscillation
      const sineOffset = Math.sin(this.airSineAngle) * 30; // ±30px amplitude
      this.y = this.airSpawnY + sineOffset;
      body.setVelocityY(0); // Y controlled by position, not velocity
    }

    // Apply frost slow to final velocity
    const frosted = applyFrostSlow({ vx: body.velocity.x, vy: body.velocity.y }, this.frostSlowMult);
    body.setVelocity(frosted.vx, frosted.vy);

    // Clamp to world bounds (prevent knockback escape)
    const clamped = clampToWorldBounds(this.x, this.y, GAME_WIDTH, -100);
    this.x = clamped.x;
    this.y = clamped.y;
  }

  /** Transition to base attack mode (melee: stop moving, start periodic attacks) */
  startBaseAttack(): void {
    this.isAttackingBase = true;
    this.attackTimer = 0; // first attack fires immediately
    const body = this.body as Phaser.Physics.Arcade.Body;
    body.setVelocity(0, 0);
    // Switch to idle animation when stopped at base
    this.tryPlayAnim('idle');
  }

  /** Check if it's time for a periodic attack; resets timer if true */
  shouldAttack(delta: number): boolean {
    this.attackTimer += delta;
    if (this.attackTimer >= this.attackInterval) {
      this.attackTimer = 0;
      this.playAttackAnim();
      return true;
    }
    return false;
  }

  /** For ranged enemies: check if should fire, and tick timer */
  shouldShoot(delta: number): boolean {
    this.attackTimer += delta;
    if (this.attackTimer >= this.attackInterval) {
      this.attackTimer = 0;
      this.playAttackAnim();
      return true;
    }
    return false;
  }

  /**
   * Apply damage. Returns true if dead.
   * During phase transition invulnerability, damage is blocked (returns false).
   * Phase transition is detected but VFX is handled by RunScene via onPhaseTransition callback.
   */
  takeDamage(amount: number): boolean {
    // Block damage during phase transition invulnerability (TASK-121)
    if (isInvulnerable(this.bossPhaseState)) {
      return false;
    }

    this.hp -= amount;
    if (this.hp <= 0) {
      return true; // dead
    }

    // Check boss phase transitions (TASK-121 + TASK-048 3-phase for boss_burst)
    if (isBossBehavior(this.behavior)) {
      // Boss Aero (boss_burst): 3-phase system with separate thresholds
      const isAero = this.behavior === 'boss_burst';
      const p2Threshold = isAero ? BALANCE.BOSS_AERO.phase2Threshold : BALANCE.BOSS_PHASE.phaseThreshold;

      // Phase 1→2 transition
      if (shouldTransitionToPhase2(this.hp, this.maxHp, p2Threshold, this.bossPhaseState.hasTransitioned)) {
        this.bossPhaseState = transitionToPhase2(BALANCE.BOSS_PHASE.invulnerabilityMs);
        // Apply Phase 2 stat boosts
        const phase2Stats = getPhase2Stats(
          2,
          this.behavior,
          BALANCE.BOSS_PHASE.phase2SpeedMult,
          BALANCE.BOSS_PHASE.phase2DamageMult,
        );
        this.speed *= phase2Stats.speedMult;
        this.damage *= phase2Stats.damageMult;
        // Re-apply boss ATK cap after Phase 2 multiplier (prevents S6 P2 one-shot)
        const maxAtk = BALANCE.DIFFICULTY.maxBossAtk;
        if (this.damage > maxAtk) this.damage = maxAtk;
        // Update burst timing for boss_burst in Phase 2
        if (isAero) {
          this.burstIdleDuration = BALANCE.BOSS_PHASE.phase2BurstIdleMs;
          this.burstChargeDuration = BALANCE.BOSS_PHASE.phase2BurstChargeMs;
        }
      }

      // Phase 2→3 transition (boss_burst / Aero only)
      if (
        isAero &&
        this.bossPhaseState.phase === 2 &&
        shouldTransitionToPhase3(
          this.hp,
          this.maxHp,
          BALANCE.BOSS_AERO.phase3Threshold,
          this.bossPhaseState.hasTransitionedP3,
        )
      ) {
        this.bossPhaseState = transitionToPhase3(this.bossPhaseState, BALANCE.BOSS_PHASE.invulnerabilityMs);
        // Phase 3 maintains Phase 2 speed/damage — no additional multiplier needed
        // Movement pattern changes to zigzag (handled in applyMovement)
        // Eagle Dive activates (handled in CombatEventManager)
      }
    }

    // Hit flash — set timer, cleared in updateFlash()
    this.setTint(NEON.UI_TEXT);
    this.flashTimer = VISUAL.ANIM.hitFlashMs;
    // Play hurt animation (briefly interrupts walk, then resumes)
    this.playHurtAnim();
    return false;
  }

  /** Tick boss phase invulnerability timer. Call from RunScene each frame. */
  updateBossPhase(delta: number): void {
    if (this.bossPhaseState.invulnerabilityMs > 0) {
      this.bossPhaseState = tickInvulnerability(this.bossPhaseState, delta);
    }
  }

  /** Call from RunScene PHASE 4 to tick flash timer (avoids delayedCall allocation) */
  updateFlash(delta: number): void {
    if (this.flashTimer > 0) {
      this.flashTimer -= delta;
      if (this.flashTimer <= 0) {
        this.clearTint();
      }
    }
  }

  // === Spritesheet Animation Methods ===

  /**
   * Try to play a spritesheet animation by state name.
   * Falls back to static sprite if animation doesn't exist.
   * @returns true if animation was played successfully
   */
  private tryPlayAnim(state: 'idle' | 'walk' | 'attack' | 'hurt' | 'death'): boolean {
    if (this.animIndex === 0) return false;
    const prefix = this.animIsBoss ? 'boss' : 'enemy';
    const key = `${prefix}${this.animIndex}_${state}`;
    if (this.scene.anims.exists(key)) {
      this.play(key, true);
      this.currentAnimState = state;
      return true;
    }
    return false;
  }

  /**
   * Play hurt animation briefly, then resume walk/idle.
   * Called when enemy takes damage but doesn't die.
   */
  playHurtAnim(): void {
    if (this.animIndex === 0) return;
    if (this.tryPlayAnim('hurt')) {
      // When hurt animation completes, resume walk
      this.once(Phaser.Animations.Events.ANIMATION_COMPLETE, () => {
        if (this.active) {
          this.tryPlayAnim('walk') || this.tryPlayAnim('idle');
        }
      });
    }
  }

  /**
   * Play attack animation, then resume walk/idle.
   */
  playAttackAnim(): void {
    if (this.animIndex === 0) return;
    if (this.tryPlayAnim('attack')) {
      this.once(Phaser.Animations.Events.ANIMATION_COMPLETE, () => {
        if (this.active) {
          if (this.isAttackingBase) {
            this.tryPlayAnim('idle');
          } else {
            this.tryPlayAnim('walk') || this.tryPlayAnim('idle');
          }
        }
      });
    }
  }

  /**
   * Play death animation and call callback when done.
   * Returns true if death animation exists and will play.
   */
  playDeathAnim(onComplete: () => void): boolean {
    if (this.animIndex === 0) return false;
    if (this.tryPlayAnim('death')) {
      this.once(Phaser.Animations.Events.ANIMATION_COMPLETE, () => {
        onComplete();
      });
      return true;
    }
    return false;
  }
}
