import Phaser from 'phaser';
import type { EnemyDef } from '../types/enemy';
import { BALANCE, VISUAL } from '../config/balance';
import { GAME_WIDTH } from '../config/game-config';

/** Map enemy shape to the texture key generated by TextureFactory */
const SHAPE_TO_TEXTURE: Record<string, string> = {
  circle: 'enemy_circle',
  triangle: 'enemy_triangle',
  rect: 'enemy_rect',
  diamond: 'enemy_diamond',
  hexagon: 'enemy_hexagon',
};

/** Boss enemies get dedicated larger textures */
const BOSS_TEXTURES: Record<string, string> = {
  boss: 'boss_hex',
  boss_circle: 'boss_diamond',
  boss_burst: 'boss_rect',
};

export class Enemy extends Phaser.Physics.Arcade.Sprite {
  public hp = 0;
  public maxHp = 0;
  public damage = 0;
  public speed = 0;
  public xpValue = 0;
  public defId = '';
  public isElite = false;
  public colorKey = '';
  public behavior = '';
  public isSplitChild = false;

  // Zigzag state
  private zigzagAngle = 0;
  private zigzagDir = 1;
  private readonly zigzagSpeed = 120; // horizontal oscillation px/s
  private readonly zigzagFreq = 2.5;  // oscillations per second

  // Dash state
  private dashTimer = 0;
  private readonly dashInterval = 2000; // ms between dashes
  private readonly dashDuration = 400;  // ms per dash burst
  private isDashing = false;

  // Knockback state
  private knockbackTimer = 0;

  // Hit flash (manual frame counter, no delayedCall)
  private flashTimer = 0;

  // Boss circle state
  private circleAngle = 0;
  private circleCenterX = 0;
  private circleCenterY = 0;
  private circlePhase: 'approach' | 'orbit' = 'approach';

  // Boss burst state
  private burstTimer = 0;
  private burstPhase: 'idle' | 'charge' = 'idle';
  private readonly burstIdleDuration = 2000;  // ms pause between charges
  private readonly burstChargeDuration = 1000; // ms per charge burst

  constructor(scene: Phaser.Scene, x: number, y: number) {
    super(scene, x, y, 'enemy_circle');
    // Pool handles adding to scene/physics world
  }

  activate(def: EnemyDef, x: number, y: number, minutesElapsed: number, elite = false, stageMult = 1): void {
    this.defId = def.id;
    this.isElite = elite;
    this.colorKey = def.colorKey;
    this.behavior = def.behavior;
    this.isSplitChild = false;

    const hpScale = Math.pow(BALANCE.DIFFICULTY.hpScalePerMin, minutesElapsed);
    const spdScale = Math.min(
      Math.pow(BALANCE.DIFFICULTY.speedScalePerMin, minutesElapsed),
      BALANCE.DIFFICULTY.maxSpeedMultiplier,
    );
    const dmgScale = Math.pow(BALANCE.DIFFICULTY.damageScalePerMin, minutesElapsed);

    const eliteMult = elite ? 5 : 1;

    this.hp = Math.ceil(def.baseHp * hpScale * eliteMult * stageMult);
    this.maxHp = this.hp;
    this.damage = Math.ceil(def.baseDamage * dmgScale * (elite ? 2 : 1) * stageMult);
    this.speed = def.baseSpeed * spdScale;
    this.xpValue = def.xpValue * (elite ? 5 : 1);

    // Set texture: boss enemies get dedicated textures, others use shape mapping
    const texKey = BOSS_TEXTURES[def.id] ?? SHAPE_TO_TEXTURE[def.shape] ?? 'enemy_circle';
    this.setTexture(texKey);

    if (def.behavior === 'boss_chase' || def.behavior === 'boss_circle' || def.behavior === 'boss_burst') {
      this.setScale(2); // Boss textures are already larger (48-52px)
    } else if (elite) {
      this.setScale(2);
    } else {
      this.setScale(1);
    }

    this.setPosition(x, y);
    this.setActive(true);
    this.setVisible(true);
    const body = this.body as Phaser.Physics.Arcade.Body;
    body.enable = true;
    body.reset(x, y);

    // Reset behavior state
    this.zigzagAngle = Math.random() * Math.PI * 2;
    this.zigzagDir = Math.random() < 0.5 ? 1 : -1;
    this.dashTimer = 0;
    this.isDashing = false;
    this.knockbackTimer = 0;
    // Boss circle
    this.circleAngle = 0;
    this.circleCenterX = 360; // screen center X
    this.circleCenterY = 500; // orbit center Y
    this.circlePhase = 'approach';
    // Boss burst
    this.burstTimer = 0;
    this.burstPhase = 'idle';
  }

  deactivate(): void {
    this.setActive(false);
    this.setVisible(false);
    const body = this.body as Phaser.Physics.Arcade.Body;
    body.enable = false;
    body.setVelocity(0, 0);
  }

  /**
   * Apply downward movement based on behavior.
   * Called by RunScene each frame (delta in ms).
   */
  applyKnockback(fromX: number, fromY: number): void {
    if (!this.active) return;
    const body = this.body as Phaser.Physics.Arcade.Body;
    const angle = Math.atan2(this.y - fromY, this.x - fromX);
    const force = BALANCE.COMBAT.knockbackForce;
    body.setVelocity(Math.cos(angle) * force, Math.sin(angle) * force);
    this.knockbackTimer = BALANCE.COMBAT.knockbackDuration;
  }

  applyMovement(delta: number, targetX?: number, targetY?: number): void {
    if (!this.active) return;
    const body = this.body as Phaser.Physics.Arcade.Body;

    // During knockback, skip normal movement
    if (this.knockbackTimer > 0) {
      this.knockbackTimer -= delta;
      return;
    }

    const dt = delta / 1000; // seconds

    switch (this.behavior) {
      case 'march':
      case 'slow_march': {
        // Straight down
        body.setVelocity(0, this.speed);
        break;
      }
      case 'slow_chase': {
        // Slow pursuit with gentle wobble
        this.zigzagAngle += this.zigzagFreq * Math.PI * dt;
        const wobble = Math.sin(this.zigzagAngle) * 30;
        if (targetX != null && targetY != null) {
          const dx = targetX - this.x;
          const dy = targetY - this.y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          if (dist > 1) {
            body.setVelocity(
              (dx / dist) * this.speed * 0.6 + wobble,
              (dy / dist) * this.speed * 0.6,
            );
          }
        } else {
          body.setVelocity(wobble, this.speed * 0.6);
        }
        break;
      }
      case 'zigzag': {
        // Move down with horizontal oscillation
        this.zigzagAngle += this.zigzagFreq * Math.PI * 2 * dt;
        const vx = Math.sin(this.zigzagAngle) * this.zigzagSpeed * this.zigzagDir;
        body.setVelocity(vx, this.speed);
        break;
      }
      case 'dash': {
        // Periodic dash bursts downward (faster), slow march between
        this.dashTimer += delta;
        if (!this.isDashing && this.dashTimer >= this.dashInterval) {
          this.isDashing = true;
          this.dashTimer = 0;
        }
        if (this.isDashing && this.dashTimer >= this.dashDuration) {
          this.isDashing = false;
          this.dashTimer = 0;
        }
        const vy = this.isDashing ? this.speed * 3 : this.speed * 0.4;
        body.setVelocity(0, vy);
        break;
      }
      case 'chase': {
        // Direct pursuit toward player
        if (targetX != null && targetY != null) {
          const dx = targetX - this.x;
          const dy = targetY - this.y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          if (dist > 1) {
            body.setVelocity((dx / dist) * this.speed, (dy / dist) * this.speed);
          }
        } else {
          body.setVelocity(0, this.speed);
        }
        break;
      }
      case 'split_on_death': {
        // Slow straight march
        body.setVelocity(0, this.speed * 0.7);
        break;
      }
      case 'boss_chase': {
        // Slow descent with gradual X-axis tracking toward player
        let bvx = 0;
        if (targetX != null) {
          const dx = targetX - this.x;
          bvx = dx * 0.02 * this.speed;
        }
        body.setVelocity(bvx, this.speed);
        break;
      }
      case 'boss_circle': {
        // Phase 1: approach orbit center, Phase 2: circular orbit descending
        if (this.circlePhase === 'approach') {
          const dx = this.circleCenterX - this.x;
          const dy = this.circleCenterY - this.y;
          const dist = Math.sqrt(dx * dx + dy * dy);
          if (dist < 10) {
            this.circlePhase = 'orbit';
          } else {
            body.setVelocity((dx / dist) * this.speed * 2, (dy / dist) * this.speed * 2);
          }
        } else {
          // Orbit with slow descent
          const radius = 200;
          const orbitSpeed = 2; // rad/s
          this.circleAngle += orbitSpeed * dt;
          const targetX = this.circleCenterX + Math.cos(this.circleAngle) * radius;
          const targetY = this.circleCenterY + Math.sin(this.circleAngle) * radius;
          const dx = targetX - this.x;
          const dy = targetY - this.y;
          body.setVelocity(dx * 3, dy * 3 + this.speed * 0.3);
          // Slowly push orbit center down
          this.circleCenterY += this.speed * 0.15 * dt;
        }
        break;
      }
      case 'boss_burst': {
        // Alternates: idle (2s) → charge downward (1s at 3x speed)
        this.burstTimer += delta;
        if (this.burstPhase === 'idle') {
          body.setVelocity(0, this.speed * 0.2);
          if (this.burstTimer >= this.burstIdleDuration) {
            this.burstPhase = 'charge';
            this.burstTimer = 0;
          }
        } else {
          body.setVelocity(0, this.speed * 4);
          if (this.burstTimer >= this.burstChargeDuration) {
            this.burstPhase = 'idle';
            this.burstTimer = 0;
          }
        }
        break;
      }
      default: {
        body.setVelocity(0, this.speed);
        break;
      }
    }

    // Clamp to world bounds (prevent knockback escape)
    if (this.x < 10) this.x = 10;
    else if (this.x > GAME_WIDTH - 10) this.x = GAME_WIDTH - 10;
    if (this.y < -100) this.y = -100;
  }

  takeDamage(amount: number): boolean {
    this.hp -= amount;
    if (this.hp <= 0) {
      return true; // dead
    }
    // Hit flash — set timer, cleared in updateFlash()
    this.setTint(0xffffff);
    this.flashTimer = VISUAL.ANIM.hitFlashMs;
    return false;
  }

  /** Call from RunScene PHASE 4 to tick flash timer (avoids delayedCall allocation) */
  updateFlash(delta: number): void {
    if (this.flashTimer > 0) {
      this.flashTimer -= delta;
      if (this.flashTimer <= 0) {
        this.clearTint();
      }
    }
  }
}
