import Phaser from 'phaser';
import type { EnemyDef } from '../types/enemy';
import { BALANCE, VISUAL } from '../config/balance';

/** Map enemy shape to the texture key generated by TextureFactory */
const SHAPE_TO_TEXTURE: Record<string, string> = {
  circle: 'enemy_circle',
  triangle: 'enemy_triangle',
  rect: 'enemy_rect',
  diamond: 'enemy_diamond',
  hexagon: 'enemy_hexagon',
};

export class Enemy extends Phaser.Physics.Arcade.Sprite {
  public hp = 0;
  public maxHp = 0;
  public damage = 0;
  public speed = 0;
  public xpValue = 0;
  public defId = '';
  public isElite = false;
  public colorKey = '';
  public behavior = '';
  public isSplitChild = false;

  // Zigzag state
  private zigzagAngle = 0;
  private zigzagDir = 1;
  private readonly zigzagSpeed = 120; // horizontal oscillation px/s
  private readonly zigzagFreq = 2.5;  // oscillations per second

  // Dash state
  private dashTimer = 0;
  private readonly dashInterval = 2000; // ms between dashes
  private readonly dashDuration = 400;  // ms per dash burst
  private isDashing = false;

  // Knockback state
  private knockbackTimer = 0;

  // Hit flash (manual frame counter, no delayedCall)
  private flashTimer = 0;

  constructor(scene: Phaser.Scene, x: number, y: number) {
    super(scene, x, y, 'enemy_circle');
    // Pool handles adding to scene/physics world
  }

  activate(def: EnemyDef, x: number, y: number, minutesElapsed: number, elite = false): void {
    this.defId = def.id;
    this.isElite = elite;
    this.colorKey = def.colorKey;
    this.behavior = def.behavior;
    this.isSplitChild = false;

    const hpScale = Math.pow(BALANCE.DIFFICULTY.hpScalePerMin, minutesElapsed);
    const spdScale = Math.min(
      Math.pow(BALANCE.DIFFICULTY.speedScalePerMin, minutesElapsed),
      BALANCE.DIFFICULTY.maxSpeedMultiplier,
    );
    const dmgScale = Math.pow(BALANCE.DIFFICULTY.damageScalePerMin, minutesElapsed);

    const eliteMult = elite ? 5 : 1;

    this.hp = Math.ceil(def.baseHp * hpScale * eliteMult);
    this.maxHp = this.hp;
    this.damage = Math.ceil(def.baseDamage * dmgScale * (elite ? 2 : 1));
    this.speed = def.baseSpeed * spdScale;
    this.xpValue = def.xpValue * (elite ? 5 : 1);

    // Set texture based on enemy shape
    const texKey = SHAPE_TO_TEXTURE[def.shape] ?? 'enemy_circle';
    this.setTexture(texKey);

    if (def.behavior === 'boss_chase') {
      this.setScale(3);
    } else if (elite) {
      this.setScale(2);
    } else {
      this.setScale(1);
    }

    this.setPosition(x, y);
    this.setActive(true);
    this.setVisible(true);
    const body = this.body as Phaser.Physics.Arcade.Body;
    body.enable = true;
    body.reset(x, y);

    // Reset behavior state
    this.zigzagAngle = Math.random() * Math.PI * 2;
    this.zigzagDir = Math.random() < 0.5 ? 1 : -1;
    this.dashTimer = 0;
    this.isDashing = false;
    this.knockbackTimer = 0;
  }

  deactivate(): void {
    this.setActive(false);
    this.setVisible(false);
    const body = this.body as Phaser.Physics.Arcade.Body;
    body.enable = false;
    body.setVelocity(0, 0);
  }

  /**
   * Apply downward movement based on behavior.
   * Called by RunScene each frame (delta in ms).
   */
  applyKnockback(fromX: number, fromY: number): void {
    if (!this.active) return;
    const body = this.body as Phaser.Physics.Arcade.Body;
    const angle = Math.atan2(this.y - fromY, this.x - fromX);
    const force = BALANCE.COMBAT.knockbackForce;
    body.setVelocity(Math.cos(angle) * force, Math.sin(angle) * force);
    this.knockbackTimer = BALANCE.COMBAT.knockbackDuration;
  }

  applyMovement(delta: number): void {
    if (!this.active) return;
    const body = this.body as Phaser.Physics.Arcade.Body;

    // During knockback, skip normal movement
    if (this.knockbackTimer > 0) {
      this.knockbackTimer -= delta;
      return;
    }

    const dt = delta / 1000; // seconds

    switch (this.behavior) {
      case 'march':
      case 'slow_chase':
      case 'slow_march': {
        // Straight down
        body.setVelocity(0, this.speed);
        break;
      }
      case 'zigzag': {
        // Move down with horizontal oscillation
        this.zigzagAngle += this.zigzagFreq * Math.PI * 2 * dt;
        const vx = Math.sin(this.zigzagAngle) * this.zigzagSpeed * this.zigzagDir;
        body.setVelocity(vx, this.speed);
        break;
      }
      case 'dash':
      case 'chase': {
        // Periodic dash bursts downward (faster), slow march between
        this.dashTimer += delta;
        if (!this.isDashing && this.dashTimer >= this.dashInterval) {
          this.isDashing = true;
          this.dashTimer = 0;
        }
        if (this.isDashing && this.dashTimer >= this.dashDuration) {
          this.isDashing = false;
          this.dashTimer = 0;
        }
        const vy = this.isDashing ? this.speed * 3 : this.speed * 0.4;
        body.setVelocity(0, vy);
        break;
      }
      case 'split_on_death': {
        // Slow straight march
        body.setVelocity(0, this.speed * 0.7);
        break;
      }
      case 'boss_chase': {
        // Slow, steady, relentless march
        body.setVelocity(0, this.speed);
        break;
      }
      default: {
        body.setVelocity(0, this.speed);
        break;
      }
    }
  }

  takeDamage(amount: number): boolean {
    this.hp -= amount;
    if (this.hp <= 0) {
      return true; // dead
    }
    // Hit flash — set timer, cleared in updateFlash()
    this.setTint(0xffffff);
    this.flashTimer = VISUAL.ANIM.hitFlashMs;
    return false;
  }

  /** Call from RunScene PHASE 4 to tick flash timer (avoids delayedCall allocation) */
  updateFlash(delta: number): void {
    if (this.flashTimer > 0) {
      this.flashTimer -= delta;
      if (this.flashTimer <= 0) {
        this.clearTint();
      }
    }
  }
}
