import { HanjaCharacter } from "./types";

/**
 * 한국 이름에 자주 쓰이는 음절 → 한자 매핑
 * 사용 빈도순 정렬 — 대규모 사전
 */
export const HANJA_MAPPINGS: Record<string, HanjaCharacter[]> = {
  // ㄱ
  "가": [
    { hanja: "佳", meaning: "아름다울 가", strokes: 8 },
    { hanja: "嘉", meaning: "아름다울 가", strokes: 14 },
    { hanja: "家", meaning: "집 가", strokes: 10 },
    { hanja: "歌", meaning: "노래 가", strokes: 14 },
    { hanja: "珂", meaning: "옥 가", strokes: 9 },
    { hanja: "可", meaning: "옳을 가", strokes: 5 },
    { hanja: "暇", meaning: "겨를 가", strokes: 13 },
    { hanja: "伽", meaning: "절 가", strokes: 7 },
  ],
  "각": [
    { hanja: "覺", meaning: "깨달을 각", strokes: 20 },
    { hanja: "角", meaning: "뿔 각", strokes: 7 },
    { hanja: "閣", meaning: "다락 각", strokes: 14 },
  ],
  "간": [
    { hanja: "幹", meaning: "줄기 간", strokes: 13 },
    { hanja: "簡", meaning: "간략할 간", strokes: 18 },
    { hanja: "侃", meaning: "강직할 간", strokes: 8 },
  ],
  "강": [
    { hanja: "强", meaning: "강할 강", strokes: 11 },
    { hanja: "康", meaning: "편안할 강", strokes: 11 },
    { hanja: "鋼", meaning: "쇠 강", strokes: 16 },
    { hanja: "姜", meaning: "생강 강", strokes: 9 },
    { hanja: "剛", meaning: "굳셀 강", strokes: 10 },
    { hanja: "綱", meaning: "벼리 강", strokes: 14 },
    { hanja: "江", meaning: "강 강", strokes: 6 },
  ],
  "건": [
    { hanja: "健", meaning: "건강할 건", strokes: 11 },
    { hanja: "建", meaning: "세울 건", strokes: 9 },
    { hanja: "乾", meaning: "하늘 건", strokes: 11 },
    { hanja: "虔", meaning: "정성 건", strokes: 10 },
    { hanja: "鍵", meaning: "열쇠 건", strokes: 17 },
  ],
  "걸": [
    { hanja: "傑", meaning: "호걸 걸", strokes: 13 },
  ],
  "경": [
    { hanja: "慶", meaning: "경사 경", strokes: 15 },
    { hanja: "京", meaning: "서울 경", strokes: 8 },
    { hanja: "景", meaning: "경치 경", strokes: 12 },
    { hanja: "敬", meaning: "공경할 경", strokes: 12 },
    { hanja: "卿", meaning: "벼슬 경", strokes: 12 },
    { hanja: "鏡", meaning: "거울 경", strokes: 19 },
    { hanja: "瓊", meaning: "옥 경", strokes: 19 },
    { hanja: "耕", meaning: "밭갈 경", strokes: 10 },
    { hanja: "庚", meaning: "일곱째 경", strokes: 8 },
    { hanja: "璟", meaning: "옥빛 경", strokes: 16 },
  ],
  "계": [
    { hanja: "桂", meaning: "계수나무 계", strokes: 10 },
    { hanja: "繼", meaning: "이을 계", strokes: 20 },
    { hanja: "啓", meaning: "열 계", strokes: 11 },
    { hanja: "季", meaning: "계절 계", strokes: 8 },
  ],
  "광": [
    { hanja: "光", meaning: "빛 광", strokes: 6 },
    { hanja: "廣", meaning: "넓을 광", strokes: 15 },
    { hanja: "珖", meaning: "옥빛 광", strokes: 10 },
    { hanja: "鑛", meaning: "쇠 광", strokes: 23 },
    { hanja: "曠", meaning: "빌 광", strokes: 19 },
  ],
  "교": [
    { hanja: "敎", meaning: "가르칠 교", strokes: 11 },
    { hanja: "橋", meaning: "다리 교", strokes: 16 },
    { hanja: "巧", meaning: "공교로울 교", strokes: 5 },
  ],
  "구": [
    { hanja: "具", meaning: "갖출 구", strokes: 8 },
    { hanja: "邱", meaning: "언덕 구", strokes: 7 },
    { hanja: "九", meaning: "아홉 구", strokes: 2 },
    { hanja: "球", meaning: "공 구", strokes: 11 },
    { hanja: "龜", meaning: "거북 구", strokes: 16 },
    { hanja: "求", meaning: "구할 구", strokes: 7 },
    { hanja: "駒", meaning: "망아지 구", strokes: 15 },
  ],
  "국": [
    { hanja: "國", meaning: "나라 국", strokes: 11 },
    { hanja: "菊", meaning: "국화 국", strokes: 11 },
    { hanja: "局", meaning: "판 국", strokes: 7 },
  ],
  "군": [
    { hanja: "君", meaning: "임금 군", strokes: 7 },
    { hanja: "軍", meaning: "군사 군", strokes: 9 },
    { hanja: "群", meaning: "무리 군", strokes: 13 },
  ],
  "굉": [
    { hanja: "宏", meaning: "클 굉", strokes: 7 },
  ],
  "귀": [
    { hanja: "貴", meaning: "귀할 귀", strokes: 12 },
    { hanja: "龜", meaning: "거북 귀", strokes: 16 },
  ],
  "규": [
    { hanja: "圭", meaning: "옥홀 규", strokes: 6 },
    { hanja: "奎", meaning: "별이름 규", strokes: 9 },
    { hanja: "揆", meaning: "헤아릴 규", strokes: 12 },
    { hanja: "珪", meaning: "옥홀 규", strokes: 10 },
    { hanja: "規", meaning: "법 규", strokes: 11 },
  ],
  "균": [
    { hanja: "均", meaning: "고를 균", strokes: 7 },
    { hanja: "鈞", meaning: "무게 균", strokes: 12 },
  ],
  "극": [
    { hanja: "克", meaning: "이길 극", strokes: 7 },
    { hanja: "極", meaning: "다할 극", strokes: 13 },
  ],
  "근": [
    { hanja: "根", meaning: "뿌리 근", strokes: 10 },
    { hanja: "勤", meaning: "부지런할 근", strokes: 13 },
    { hanja: "謹", meaning: "삼갈 근", strokes: 17 },
    { hanja: "瑾", meaning: "옥 근", strokes: 15 },
    { hanja: "槿", meaning: "무궁화 근", strokes: 15 },
    { hanja: "筋", meaning: "힘줄 근", strokes: 12 },
  ],
  "금": [
    { hanja: "金", meaning: "쇠 금", strokes: 8 },
    { hanja: "琴", meaning: "거문고 금", strokes: 12 },
    { hanja: "錦", meaning: "비단 금", strokes: 16 },
    { hanja: "今", meaning: "이제 금", strokes: 4 },
    { hanja: "禁", meaning: "금할 금", strokes: 13 },
  ],
  "기": [
    { hanja: "基", meaning: "터 기", strokes: 11 },
    { hanja: "起", meaning: "일어날 기", strokes: 10 },
    { hanja: "奇", meaning: "기이할 기", strokes: 8 },
    { hanja: "琪", meaning: "옥 기", strokes: 12 },
    { hanja: "祺", meaning: "상서로울 기", strokes: 12 },
    { hanja: "紀", meaning: "벼리 기", strokes: 9 },
    { hanja: "棋", meaning: "바둑 기", strokes: 12 },
    { hanja: "期", meaning: "기약할 기", strokes: 12 },
    { hanja: "氣", meaning: "기운 기", strokes: 10 },
    { hanja: "技", meaning: "재주 기", strokes: 7 },
    { hanja: "己", meaning: "몸 기", strokes: 3 },
    { hanja: "驥", meaning: "천리마 기", strokes: 26 },
  ],
  "길": [
    { hanja: "吉", meaning: "길할 길", strokes: 6 },
    { hanja: "佶", meaning: "굳셀 길", strokes: 8 },
  ],
  // ㄴ
  "나": [
    { hanja: "娜", meaning: "고울 나", strokes: 9 },
    { hanja: "那", meaning: "어찌 나", strokes: 7 },
    { hanja: "羅", meaning: "벌릴 나", strokes: 19 },
    { hanja: "奈", meaning: "어찌 나", strokes: 8 },
  ],
  "낙": [
    { hanja: "洛", meaning: "물이름 낙", strokes: 9 },
    { hanja: "樂", meaning: "즐거울 낙", strokes: 15 },
    { hanja: "諾", meaning: "허락할 낙", strokes: 16 },
  ],
  "남": [
    { hanja: "南", meaning: "남쪽 남", strokes: 9 },
    { hanja: "楠", meaning: "녹나무 남", strokes: 13 },
    { hanja: "嵐", meaning: "남기 남", strokes: 12 },
  ],
  "녕": [
    { hanja: "寧", meaning: "편안할 녕", strokes: 14 },
  ],
  "녹": [
    { hanja: "祿", meaning: "복 녹", strokes: 12 },
    { hanja: "綠", meaning: "초록 녹", strokes: 14 },
  ],
  "눌": [
    { hanja: "訥", meaning: "더듬을 눌", strokes: 11 },
  ],
  "능": [
    { hanja: "能", meaning: "능할 능", strokes: 10 },
    { hanja: "綾", meaning: "비단 능", strokes: 14 },
  ],
  // ㄷ
  "다": [
    { hanja: "多", meaning: "많을 다", strokes: 6 },
    { hanja: "茶", meaning: "차 다", strokes: 9 },
  ],
  "단": [
    { hanja: "丹", meaning: "붉을 단", strokes: 4 },
    { hanja: "端", meaning: "바를 단", strokes: 14 },
    { hanja: "檀", meaning: "박달 단", strokes: 17 },
    { hanja: "旦", meaning: "아침 단", strokes: 5 },
    { hanja: "壇", meaning: "단 단", strokes: 16 },
    { hanja: "簞", meaning: "대그릇 단", strokes: 18 },
  ],
  "달": [
    { hanja: "達", meaning: "통달할 달", strokes: 12 },
    { hanja: "鉢", meaning: "바리때 달", strokes: 13 },
  ],
  "담": [
    { hanja: "澹", meaning: "맑을 담", strokes: 16 },
    { hanja: "潭", meaning: "못 담", strokes: 15 },
    { hanja: "淡", meaning: "맑을 담", strokes: 11 },
    { hanja: "膽", meaning: "쓸개 담", strokes: 17 },
  ],
  "대": [
    { hanja: "大", meaning: "큰 대", strokes: 3 },
    { hanja: "代", meaning: "대신할 대", strokes: 5 },
    { hanja: "戴", meaning: "일 대", strokes: 17 },
    { hanja: "臺", meaning: "대 대", strokes: 14 },
    { hanja: "岱", meaning: "태산 대", strokes: 8 },
  ],
  "덕": [
    { hanja: "德", meaning: "큰 덕", strokes: 15 },
    { hanja: "悳", meaning: "덕 덕", strokes: 12 },
  ],
  "도": [
    { hanja: "道", meaning: "길 도", strokes: 12 },
    { hanja: "度", meaning: "법도 도", strokes: 9 },
    { hanja: "島", meaning: "섬 도", strokes: 10 },
    { hanja: "桃", meaning: "복숭아 도", strokes: 10 },
    { hanja: "都", meaning: "도읍 도", strokes: 11 },
    { hanja: "陶", meaning: "질그릇 도", strokes: 11 },
    { hanja: "導", meaning: "이끌 도", strokes: 15 },
  ],
  "돈": [
    { hanja: "敦", meaning: "도타울 돈", strokes: 12 },
    { hanja: "惇", meaning: "도타울 돈", strokes: 11 },
  ],
  "동": [
    { hanja: "東", meaning: "동쪽 동", strokes: 8 },
    { hanja: "棟", meaning: "마룻대 동", strokes: 12 },
    { hanja: "銅", meaning: "구리 동", strokes: 14 },
    { hanja: "童", meaning: "아이 동", strokes: 12 },
    { hanja: "洞", meaning: "골 동", strokes: 9 },
    { hanja: "彤", meaning: "붉을 동", strokes: 7 },
  ],
  "두": [
    { hanja: "斗", meaning: "말 두", strokes: 4 },
    { hanja: "杜", meaning: "막을 두", strokes: 7 },
    { hanja: "頭", meaning: "머리 두", strokes: 16 },
    { hanja: "斗", meaning: "별 두", strokes: 4 },
  ],
  "득": [
    { hanja: "得", meaning: "얻을 득", strokes: 11 },
  ],
  // ㄹ
  "란": [
    { hanja: "蘭", meaning: "난초 란", strokes: 21 },
    { hanja: "爛", meaning: "빛날 란", strokes: 21 },
    { hanja: "瀾", meaning: "물결 란", strokes: 20 },
  ],
  "래": [
    { hanja: "來", meaning: "올 래", strokes: 8 },
    { hanja: "萊", meaning: "명아주 래", strokes: 11 },
    { hanja: "賴", meaning: "힘입을 래", strokes: 16 },
  ],
  "량": [
    { hanja: "亮", meaning: "밝을 량", strokes: 9 },
    { hanja: "良", meaning: "어질 량", strokes: 7 },
    { hanja: "諒", meaning: "헤아릴 량", strokes: 15 },
    { hanja: "梁", meaning: "들보 량", strokes: 11 },
  ],
  "려": [
    { hanja: "麗", meaning: "고울 려", strokes: 19 },
    { hanja: "勵", meaning: "힘쓸 려", strokes: 17 },
    { hanja: "旅", meaning: "나그네 려", strokes: 10 },
  ],
  "력": [
    { hanja: "力", meaning: "힘 력", strokes: 2 },
    { hanja: "歷", meaning: "지날 력", strokes: 16 },
  ],
  "련": [
    { hanja: "蓮", meaning: "연꽃 련", strokes: 15 },
    { hanja: "鍊", meaning: "단련할 련", strokes: 17 },
    { hanja: "連", meaning: "잇닿을 련", strokes: 10 },
  ],
  "렬": [
    { hanja: "烈", meaning: "세찰 렬", strokes: 10 },
    { hanja: "列", meaning: "줄 렬", strokes: 6 },
  ],
  "령": [
    { hanja: "靈", meaning: "신령 령", strokes: 24 },
    { hanja: "嶺", meaning: "재 령", strokes: 17 },
    { hanja: "令", meaning: "하여금 령", strokes: 5 },
    { hanja: "玲", meaning: "옥소리 령", strokes: 9 },
  ],
  "로": [
    { hanja: "路", meaning: "길 로", strokes: 13 },
    { hanja: "露", meaning: "이슬 로", strokes: 20 },
    { hanja: "魯", meaning: "노나라 로", strokes: 15 },
    { hanja: "老", meaning: "늙을 로", strokes: 6 },
    { hanja: "盧", meaning: "그릇 로", strokes: 16 },
  ],
  "록": [
    { hanja: "祿", meaning: "복 록", strokes: 12 },
    { hanja: "錄", meaning: "기록할 록", strokes: 16 },
    { hanja: "綠", meaning: "초록 록", strokes: 14 },
  ],
  "론": [
    { hanja: "論", meaning: "논할 론", strokes: 15 },
  ],
  "룡": [
    { hanja: "龍", meaning: "용 룡", strokes: 16 },
  ],
  "류": [
    { hanja: "柳", meaning: "버들 류", strokes: 9 },
    { hanja: "劉", meaning: "죽일 류", strokes: 15 },
    { hanja: "琉", meaning: "유리 류", strokes: 11 },
    { hanja: "流", meaning: "흐를 류", strokes: 10 },
  ],
  "률": [
    { hanja: "律", meaning: "법칙 률", strokes: 9 },
    { hanja: "栗", meaning: "밤 률", strokes: 10 },
  ],
  "륜": [
    { hanja: "倫", meaning: "인륜 륜", strokes: 10 },
    { hanja: "輪", meaning: "바퀴 륜", strokes: 15 },
  ],
  "리": [
    { hanja: "利", meaning: "이로울 리", strokes: 7 },
    { hanja: "莉", meaning: "재스민 리", strokes: 10 },
    { hanja: "理", meaning: "다스릴 리", strokes: 11 },
    { hanja: "里", meaning: "마을 리", strokes: 7 },
    { hanja: "璃", meaning: "유리 리", strokes: 15 },
    { hanja: "梨", meaning: "배 리", strokes: 11 },
    { hanja: "李", meaning: "오얏 리", strokes: 7 },
  ],
  "림": [
    { hanja: "林", meaning: "수풀 림", strokes: 8 },
    { hanja: "琳", meaning: "옥 림", strokes: 12 },
    { hanja: "臨", meaning: "임할 림", strokes: 17 },
    { hanja: "霖", meaning: "장마 림", strokes: 15 },
  ],
  // ㅁ
  "만": [
    { hanja: "萬", meaning: "일만 만", strokes: 13 },
    { hanja: "滿", meaning: "가득찰 만", strokes: 14 },
    { hanja: "晩", meaning: "늦을 만", strokes: 11 },
    { hanja: "漫", meaning: "넘칠 만", strokes: 14 },
  ],
  "말": [
    { hanja: "末", meaning: "끝 말", strokes: 5 },
  ],
  "망": [
    { hanja: "望", meaning: "바랄 망", strokes: 11 },
  ],
  "매": [
    { hanja: "梅", meaning: "매화 매", strokes: 10 },
    { hanja: "玫", meaning: "장미 매", strokes: 8 },
  ],
  "맹": [
    { hanja: "孟", meaning: "맏 맹", strokes: 8 },
    { hanja: "猛", meaning: "사나울 맹", strokes: 11 },
    { hanja: "盟", meaning: "맹세할 맹", strokes: 13 },
  ],
  "면": [
    { hanja: "勉", meaning: "힘쓸 면", strokes: 9 },
    { hanja: "棉", meaning: "솜 면", strokes: 12 },
  ],
  "명": [
    { hanja: "明", meaning: "밝을 명", strokes: 8 },
    { hanja: "銘", meaning: "새길 명", strokes: 14 },
    { hanja: "命", meaning: "목숨 명", strokes: 8 },
    { hanja: "鳴", meaning: "울 명", strokes: 14 },
    { hanja: "茗", meaning: "차 명", strokes: 9 },
    { hanja: "溟", meaning: "바다 명", strokes: 13 },
  ],
  "모": [
    { hanja: "模", meaning: "본뜰 모", strokes: 15 },
    { hanja: "慕", meaning: "사모할 모", strokes: 14 },
    { hanja: "謨", meaning: "꾀 모", strokes: 17 },
    { hanja: "茅", meaning: "띠 모", strokes: 8 },
  ],
  "목": [
    { hanja: "睦", meaning: "화목할 목", strokes: 13 },
    { hanja: "牧", meaning: "기를 목", strokes: 8 },
    { hanja: "木", meaning: "나무 목", strokes: 4 },
    { hanja: "穆", meaning: "화목할 목", strokes: 16 },
  ],
  "몽": [
    { hanja: "夢", meaning: "꿈 몽", strokes: 13 },
  ],
  "묘": [
    { hanja: "妙", meaning: "묘할 묘", strokes: 7 },
    { hanja: "苗", meaning: "모 묘", strokes: 8 },
  ],
  "무": [
    { hanja: "武", meaning: "호반 무", strokes: 8 },
    { hanja: "茂", meaning: "무성할 무", strokes: 8 },
    { hanja: "舞", meaning: "춤출 무", strokes: 14 },
    { hanja: "懋", meaning: "힘쓸 무", strokes: 17 },
    { hanja: "戊", meaning: "다섯째 무", strokes: 5 },
    { hanja: "畝", meaning: "이랑 무", strokes: 7 },
  ],
  "묵": [
    { hanja: "默", meaning: "잠잠할 묵", strokes: 16 },
    { hanja: "墨", meaning: "먹 묵", strokes: 15 },
  ],
  "문": [
    { hanja: "文", meaning: "글월 문", strokes: 4 },
    { hanja: "紋", meaning: "무늬 문", strokes: 10 },
    { hanja: "聞", meaning: "들을 문", strokes: 14 },
  ],
  "미": [
    { hanja: "美", meaning: "아름다울 미", strokes: 9 },
    { hanja: "微", meaning: "작을 미", strokes: 13 },
    { hanja: "未", meaning: "아닐 미", strokes: 5 },
    { hanja: "敏", meaning: "민첩할 미", strokes: 11 },
    { hanja: "彌", meaning: "두루 미", strokes: 17 },
    { hanja: "眉", meaning: "눈썹 미", strokes: 9 },
  ],
  "민": [
    { hanja: "民", meaning: "백성 민", strokes: 5 },
    { hanja: "敏", meaning: "민첩할 민", strokes: 11 },
    { hanja: "旻", meaning: "하늘 민", strokes: 8 },
    { hanja: "珉", meaning: "옥돌 민", strokes: 9 },
    { hanja: "玟", meaning: "옥 민", strokes: 8 },
    { hanja: "閔", meaning: "근심할 민", strokes: 12 },
    { hanja: "泯", meaning: "없어질 민", strokes: 8 },
    { hanja: "憫", meaning: "근심할 민", strokes: 15 },
  ],
  // ㅂ
  "박": [
    { hanja: "朴", meaning: "순박할 박", strokes: 6 },
    { hanja: "博", meaning: "넓을 박", strokes: 12 },
    { hanja: "薄", meaning: "엷을 박", strokes: 16 },
  ],
  "반": [
    { hanja: "磐", meaning: "반석 반", strokes: 15 },
    { hanja: "班", meaning: "나눌 반", strokes: 10 },
    { hanja: "伴", meaning: "짝 반", strokes: 7 },
  ],
  "발": [
    { hanja: "發", meaning: "쏠 발", strokes: 12 },
    { hanja: "拔", meaning: "뽑을 발", strokes: 8 },
  ],
  "방": [
    { hanja: "邦", meaning: "나라 방", strokes: 7 },
    { hanja: "芳", meaning: "꽃다울 방", strokes: 7 },
    { hanja: "方", meaning: "모 방", strokes: 4 },
    { hanja: "房", meaning: "방 방", strokes: 8 },
    { hanja: "放", meaning: "놓을 방", strokes: 8 },
    { hanja: "邡", meaning: "고을 방", strokes: 6 },
  ],
  "배": [
    { hanja: "裴", meaning: "성씨 배", strokes: 14 },
    { hanja: "培", meaning: "북돋울 배", strokes: 11 },
    { hanja: "倍", meaning: "곱 배", strokes: 10 },
    { hanja: "拜", meaning: "절 배", strokes: 9 },
    { hanja: "杯", meaning: "잔 배", strokes: 8 },
  ],
  "백": [
    { hanja: "白", meaning: "흰 백", strokes: 5 },
    { hanja: "伯", meaning: "맏 백", strokes: 7 },
    { hanja: "百", meaning: "일백 백", strokes: 6 },
    { hanja: "栢", meaning: "잣나무 백", strokes: 9 },
    { hanja: "柏", meaning: "잣나무 백", strokes: 9 },
  ],
  "범": [
    { hanja: "範", meaning: "법 범", strokes: 15 },
    { hanja: "凡", meaning: "무릇 범", strokes: 3 },
    { hanja: "泛", meaning: "넘칠 범", strokes: 7 },
    { hanja: "梵", meaning: "우거질 범", strokes: 11 },
  ],
  "벽": [
    { hanja: "碧", meaning: "푸를 벽", strokes: 14 },
    { hanja: "璧", meaning: "구슬 벽", strokes: 18 },
  ],
  "변": [
    { hanja: "卞", meaning: "성씨 변", strokes: 4 },
    { hanja: "邊", meaning: "가 변", strokes: 18 },
  ],
  "별": [
    { hanja: "別", meaning: "나눌 별", strokes: 7 },
  ],
  "병": [
    { hanja: "炳", meaning: "밝을 병", strokes: 9 },
    { hanja: "秉", meaning: "잡을 병", strokes: 8 },
    { hanja: "丙", meaning: "남쪽 병", strokes: 5 },
    { hanja: "柄", meaning: "자루 병", strokes: 9 },
    { hanja: "屛", meaning: "병풍 병", strokes: 9 },
  ],
  "보": [
    { hanja: "寶", meaning: "보배 보", strokes: 20 },
    { hanja: "甫", meaning: "클 보", strokes: 7 },
    { hanja: "輔", meaning: "도울 보", strokes: 14 },
    { hanja: "普", meaning: "넓을 보", strokes: 12 },
    { hanja: "報", meaning: "알릴 보", strokes: 12 },
    { hanja: "步", meaning: "걸음 보", strokes: 7 },
    { hanja: "堡", meaning: "보루 보", strokes: 12 },
  ],
  "복": [
    { hanja: "福", meaning: "복 복", strokes: 13 },
    { hanja: "馥", meaning: "향기 복", strokes: 18 },
    { hanja: "復", meaning: "돌아올 복", strokes: 12 },
    { hanja: "伏", meaning: "엎드릴 복", strokes: 6 },
  ],
  "본": [
    { hanja: "本", meaning: "근본 본", strokes: 5 },
  ],
  "봉": [
    { hanja: "鳳", meaning: "봉새 봉", strokes: 14 },
    { hanja: "奉", meaning: "받들 봉", strokes: 8 },
    { hanja: "峯", meaning: "봉우리 봉", strokes: 10 },
    { hanja: "蓬", meaning: "쑥 봉", strokes: 13 },
    { hanja: "蜂", meaning: "벌 봉", strokes: 13 },
  ],
  "부": [
    { hanja: "富", meaning: "부유할 부", strokes: 12 },
    { hanja: "扶", meaning: "도울 부", strokes: 7 },
    { hanja: "府", meaning: "마을 부", strokes: 8 },
    { hanja: "芙", meaning: "연꽃 부", strokes: 7 },
    { hanja: "夫", meaning: "지아비 부", strokes: 4 },
  ],
  "북": [
    { hanja: "北", meaning: "북녘 북", strokes: 5 },
  ],
  "분": [
    { hanja: "芬", meaning: "향기 분", strokes: 7 },
    { hanja: "奔", meaning: "달릴 분", strokes: 8 },
  ],
  "빈": [
    { hanja: "彬", meaning: "빛날 빈", strokes: 11 },
    { hanja: "斌", meaning: "빛날 빈", strokes: 12 },
    { hanja: "賓", meaning: "손 빈", strokes: 15 },
    { hanja: "濱", meaning: "물가 빈", strokes: 17 },
    { hanja: "玭", meaning: "구슬 빈", strokes: 8 },
    { hanja: "嬪", meaning: "궁인 빈", strokes: 14 },
  ],
  // ㅅ
  "사": [
    { hanja: "思", meaning: "생각할 사", strokes: 9 },
    { hanja: "士", meaning: "선비 사", strokes: 3 },
    { hanja: "司", meaning: "맡을 사", strokes: 5 },
    { hanja: "斯", meaning: "이 사", strokes: 12 },
    { hanja: "師", meaning: "스승 사", strokes: 10 },
    { hanja: "史", meaning: "사기 사", strokes: 5 },
    { hanja: "嗣", meaning: "이을 사", strokes: 13 },
    { hanja: "沙", meaning: "모래 사", strokes: 7 },
    { hanja: "詞", meaning: "말씀 사", strokes: 12 },
  ],
  "산": [
    { hanja: "山", meaning: "뫼 산", strokes: 3 },
    { hanja: "産", meaning: "낳을 산", strokes: 11 },
    { hanja: "珊", meaning: "산호 산", strokes: 9 },
    { hanja: "燦", meaning: "빛날 산", strokes: 17 },
  ],
  "삼": [
    { hanja: "三", meaning: "석 삼", strokes: 3 },
    { hanja: "森", meaning: "수풀 삼", strokes: 12 },
    { hanja: "蔘", meaning: "인삼 삼", strokes: 14 },
  ],
  "상": [
    { hanja: "相", meaning: "서로 상", strokes: 9 },
    { hanja: "祥", meaning: "상서로울 상", strokes: 10 },
    { hanja: "尙", meaning: "오히려 상", strokes: 8 },
    { hanja: "翔", meaning: "날 상", strokes: 12 },
    { hanja: "常", meaning: "항상 상", strokes: 11 },
    { hanja: "象", meaning: "코끼리 상", strokes: 12 },
    { hanja: "尚", meaning: "오히려 상", strokes: 8 },
    { hanja: "桑", meaning: "뽕나무 상", strokes: 10 },
    { hanja: "霜", meaning: "서리 상", strokes: 17 },
  ],
  "새": [
    { hanja: "賽", meaning: "보답할 새", strokes: 17 },
  ],
  "서": [
    { hanja: "瑞", meaning: "상서로울 서", strokes: 13 },
    { hanja: "書", meaning: "글 서", strokes: 10 },
    { hanja: "序", meaning: "차례 서", strokes: 7 },
    { hanja: "徐", meaning: "천천히 서", strokes: 10 },
    { hanja: "緖", meaning: "실마리 서", strokes: 14 },
    { hanja: "抒", meaning: "펼 서", strokes: 7 },
    { hanja: "曙", meaning: "밝을 서", strokes: 18 },
    { hanja: "恕", meaning: "용서할 서", strokes: 10 },
    { hanja: "西", meaning: "서녘 서", strokes: 6 },
  ],
  "석": [
    { hanja: "碩", meaning: "큰 석", strokes: 14 },
    { hanja: "石", meaning: "돌 석", strokes: 5 },
    { hanja: "錫", meaning: "주석 석", strokes: 16 },
    { hanja: "昔", meaning: "옛 석", strokes: 8 },
    { hanja: "晳", meaning: "밝을 석", strokes: 12 },
    { hanja: "奭", meaning: "성할 석", strokes: 12 },
    { hanja: "釋", meaning: "풀 석", strokes: 20 },
  ],
  "선": [
    { hanja: "善", meaning: "착할 선", strokes: 12 },
    { hanja: "宣", meaning: "베풀 선", strokes: 9 },
    { hanja: "鮮", meaning: "고울 선", strokes: 17 },
    { hanja: "仙", meaning: "신선 선", strokes: 5 },
    { hanja: "先", meaning: "먼저 선", strokes: 6 },
    { hanja: "璇", meaning: "옥 선", strokes: 15 },
    { hanja: "禪", meaning: "선 선", strokes: 16 },
    { hanja: "瑄", meaning: "옥 선", strokes: 13 },
    { hanja: "嬋", meaning: "고울 선", strokes: 15 },
  ],
  "섭": [
    { hanja: "燮", meaning: "화할 섭", strokes: 17 },
    { hanja: "涉", meaning: "건널 섭", strokes: 10 },
    { hanja: "攝", meaning: "잡을 섭", strokes: 21 },
  ],
  "성": [
    { hanja: "聖", meaning: "거룩할 성", strokes: 13 },
    { hanja: "星", meaning: "별 성", strokes: 9 },
    { hanja: "成", meaning: "이룰 성", strokes: 6 },
    { hanja: "誠", meaning: "정성 성", strokes: 13 },
    { hanja: "盛", meaning: "성할 성", strokes: 11 },
    { hanja: "城", meaning: "재 성", strokes: 9 },
    { hanja: "晟", meaning: "밝을 성", strokes: 10 },
    { hanja: "性", meaning: "성품 성", strokes: 8 },
    { hanja: "瑆", meaning: "옥빛 성", strokes: 13 },
    { hanja: "惺", meaning: "깨달을 성", strokes: 12 },
  ],
  "세": [
    { hanja: "世", meaning: "세상 세", strokes: 5 },
    { hanja: "勢", meaning: "기세 세", strokes: 13 },
    { hanja: "細", meaning: "가늘 세", strokes: 11 },
    { hanja: "歲", meaning: "해 세", strokes: 13 },
    { hanja: "稅", meaning: "세금 세", strokes: 12 },
  ],
  "소": [
    { hanja: "素", meaning: "흰 소", strokes: 10 },
    { hanja: "昭", meaning: "밝을 소", strokes: 9 },
    { hanja: "紹", meaning: "이을 소", strokes: 11 },
    { hanja: "韶", meaning: "아름다울 소", strokes: 14 },
    { hanja: "蘇", meaning: "소생할 소", strokes: 19 },
    { hanja: "邵", meaning: "고을 소", strokes: 7 },
    { hanja: "召", meaning: "부를 소", strokes: 5 },
    { hanja: "嘯", meaning: "휘파람 소", strokes: 15 },
  ],
  "솔": [
    { hanja: "率", meaning: "거느릴 솔", strokes: 11 },
    { hanja: "松", meaning: "소나무 솔", strokes: 8 },
  ],
  "송": [
    { hanja: "宋", meaning: "나라 송", strokes: 7 },
    { hanja: "松", meaning: "소나무 송", strokes: 8 },
    { hanja: "頌", meaning: "칭송할 송", strokes: 13 },
    { hanja: "誦", meaning: "외울 송", strokes: 14 },
  ],
  "수": [
    { hanja: "秀", meaning: "빼어날 수", strokes: 7 },
    { hanja: "洙", meaning: "물이름 수", strokes: 9 },
    { hanja: "壽", meaning: "목숨 수", strokes: 14 },
    { hanja: "修", meaning: "닦을 수", strokes: 9 },
    { hanja: "樹", meaning: "나무 수", strokes: 16 },
    { hanja: "守", meaning: "지킬 수", strokes: 6 },
    { hanja: "殊", meaning: "다를 수", strokes: 10 },
    { hanja: "繡", meaning: "수놓을 수", strokes: 18 },
    { hanja: "受", meaning: "받을 수", strokes: 8 },
    { hanja: "秀", meaning: "빼어날 수", strokes: 7 },
    { hanja: "粹", meaning: "순수할 수", strokes: 14 },
    { hanja: "穗", meaning: "이삭 수", strokes: 15 },
    { hanja: "琇", meaning: "옥 수", strokes: 11 },
    { hanja: "水", meaning: "물 수", strokes: 4 },
  ],
  "숙": [
    { hanja: "淑", meaning: "맑을 숙", strokes: 11 },
    { hanja: "叔", meaning: "아저씨 숙", strokes: 8 },
    { hanja: "肅", meaning: "엄숙할 숙", strokes: 13 },
    { hanja: "宿", meaning: "잠잘 숙", strokes: 11 },
  ],
  "순": [
    { hanja: "淳", meaning: "순박할 순", strokes: 11 },
    { hanja: "純", meaning: "순수할 순", strokes: 10 },
    { hanja: "順", meaning: "순할 순", strokes: 12 },
    { hanja: "循", meaning: "돌 순", strokes: 12 },
    { hanja: "旬", meaning: "열흘 순", strokes: 6 },
    { hanja: "舜", meaning: "임금 순", strokes: 12 },
    { hanja: "筍", meaning: "죽순 순", strokes: 12 },
    { hanja: "恂", meaning: "진실할 순", strokes: 9 },
  ],
  "술": [
    { hanja: "述", meaning: "지을 술", strokes: 8 },
    { hanja: "術", meaning: "재주 술", strokes: 11 },
  ],
  "숭": [
    { hanja: "崇", meaning: "높을 숭", strokes: 11 },
  ],
  "승": [
    { hanja: "勝", meaning: "이길 승", strokes: 12 },
    { hanja: "承", meaning: "이을 승", strokes: 8 },
    { hanja: "昇", meaning: "오를 승", strokes: 8 },
    { hanja: "陞", meaning: "오를 승", strokes: 10 },
    { hanja: "丞", meaning: "도울 승", strokes: 6 },
    { hanja: "繩", meaning: "노끈 승", strokes: 19 },
  ],
  "시": [
    { hanja: "時", meaning: "때 시", strokes: 10 },
    { hanja: "詩", meaning: "시 시", strokes: 13 },
    { hanja: "施", meaning: "베풀 시", strokes: 9 },
    { hanja: "始", meaning: "비로소 시", strokes: 8 },
    { hanja: "示", meaning: "보일 시", strokes: 5 },
    { hanja: "矢", meaning: "화살 시", strokes: 5 },
  ],
  "식": [
    { hanja: "植", meaning: "심을 식", strokes: 12 },
    { hanja: "識", meaning: "알 식", strokes: 19 },
    { hanja: "式", meaning: "법 식", strokes: 6 },
  ],
  "신": [
    { hanja: "申", meaning: "펼 신", strokes: 5 },
    { hanja: "辛", meaning: "매울 신", strokes: 7 },
    { hanja: "愼", meaning: "삼갈 신", strokes: 13 },
    { hanja: "信", meaning: "믿을 신", strokes: 9 },
    { hanja: "新", meaning: "새로울 신", strokes: 13 },
    { hanja: "臣", meaning: "신하 신", strokes: 7 },
    { hanja: "神", meaning: "귀신 신", strokes: 9 },
    { hanja: "伸", meaning: "펼 신", strokes: 7 },
    { hanja: "紳", meaning: "띠 신", strokes: 11 },
  ],
  "심": [
    { hanja: "沈", meaning: "잠길 심", strokes: 7 },
    { hanja: "心", meaning: "마음 심", strokes: 4 },
    { hanja: "深", meaning: "깊을 심", strokes: 11 },
    { hanja: "審", meaning: "살필 심", strokes: 15 },
    { hanja: "尋", meaning: "찾을 심", strokes: 12 },
  ],
  "슬": [
    { hanja: "瑟", meaning: "비파 슬", strokes: 13 },
    { hanja: "膝", meaning: "무릎 슬", strokes: 15 },
    { hanja: "瑟", meaning: "거문고 슬", strokes: 13 },
  ],
  // ㅇ
  "아": [
    { hanja: "雅", meaning: "우아할 아", strokes: 12 },
    { hanja: "亞", meaning: "버금 아", strokes: 8 },
    { hanja: "娥", meaning: "아리따울 아", strokes: 10 },
    { hanja: "兒", meaning: "아이 아", strokes: 8 },
    { hanja: "牙", meaning: "어금니 아", strokes: 4 },
  ],
  "악": [
    { hanja: "岳", meaning: "큰산 악", strokes: 8 },
    { hanja: "樂", meaning: "풍류 악", strokes: 15 },
  ],
  "안": [
    { hanja: "安", meaning: "편안할 안", strokes: 6 },
    { hanja: "晏", meaning: "늦을 안", strokes: 10 },
    { hanja: "按", meaning: "살필 안", strokes: 9 },
    { hanja: "雁", meaning: "기러기 안", strokes: 12 },
    { hanja: "顔", meaning: "얼굴 안", strokes: 18 },
  ],
  "암": [
    { hanja: "巖", meaning: "바위 암", strokes: 20 },
    { hanja: "岩", meaning: "바위 암", strokes: 8 },
  ],
  "애": [
    { hanja: "愛", meaning: "사랑 애", strokes: 13 },
    { hanja: "曖", meaning: "따뜻할 애", strokes: 17 },
  ],
  "양": [
    { hanja: "梁", meaning: "들보 양", strokes: 11 },
    { hanja: "楊", meaning: "버들 양", strokes: 13 },
    { hanja: "陽", meaning: "볕 양", strokes: 12 },
    { hanja: "洋", meaning: "큰바다 양", strokes: 9 },
    { hanja: "讓", meaning: "사양할 양", strokes: 24 },
    { hanja: "養", meaning: "기를 양", strokes: 15 },
    { hanja: "良", meaning: "어질 양", strokes: 7 },
    { hanja: "壤", meaning: "흙 양", strokes: 20 },
  ],
  "어": [
    { hanja: "魚", meaning: "물고기 어", strokes: 11 },
    { hanja: "御", meaning: "거느릴 어", strokes: 12 },
  ],
  "억": [
    { hanja: "億", meaning: "억 억", strokes: 15 },
  ],
  "엄": [
    { hanja: "嚴", meaning: "엄할 엄", strokes: 20 },
    { hanja: "儼", meaning: "엄숙할 엄", strokes: 22 },
  ],
  "업": [
    { hanja: "業", meaning: "업 업", strokes: 13 },
  ],
  "여": [
    { hanja: "余", meaning: "나 여", strokes: 7 },
    { hanja: "如", meaning: "같을 여", strokes: 6 },
    { hanja: "汝", meaning: "너 여", strokes: 6 },
    { hanja: "呂", meaning: "성씨 여", strokes: 7 },
    { hanja: "璵", meaning: "옥 여", strokes: 16 },
  ],
  "역": [
    { hanja: "易", meaning: "바꿀 역", strokes: 8 },
    { hanja: "亦", meaning: "또 역", strokes: 6 },
    { hanja: "譯", meaning: "번역할 역", strokes: 20 },
    { hanja: "驛", meaning: "역참 역", strokes: 23 },
  ],
  "연": [
    { hanja: "淵", meaning: "못 연", strokes: 11 },
    { hanja: "延", meaning: "늘일 연", strokes: 7 },
    { hanja: "蓮", meaning: "연꽃 연", strokes: 15 },
    { hanja: "鍊", meaning: "단련할 연", strokes: 17 },
    { hanja: "姸", meaning: "고울 연", strokes: 9 },
    { hanja: "衍", meaning: "넘칠 연", strokes: 9 },
    { hanja: "鉛", meaning: "납 연", strokes: 13 },
    { hanja: "煙", meaning: "연기 연", strokes: 13 },
    { hanja: "然", meaning: "그러할 연", strokes: 12 },
    { hanja: "燕", meaning: "제비 연", strokes: 16 },
    { hanja: "演", meaning: "펼 연", strokes: 14 },
    { hanja: "緣", meaning: "인연 연", strokes: 15 },
    { hanja: "妍", meaning: "고울 연", strokes: 7 },
  ],
  "열": [
    { hanja: "悅", meaning: "기쁠 열", strokes: 10 },
    { hanja: "烈", meaning: "세찰 열", strokes: 10 },
    { hanja: "悅", meaning: "기쁠 열", strokes: 10 },
  ],
  "염": [
    { hanja: "廉", meaning: "청렴할 염", strokes: 13 },
    { hanja: "炎", meaning: "불꽃 염", strokes: 8 },
    { hanja: "焰", meaning: "불꽃 염", strokes: 12 },
    { hanja: "艶", meaning: "고울 염", strokes: 19 },
  ],
  "엽": [
    { hanja: "燁", meaning: "빛날 엽", strokes: 16 },
    { hanja: "葉", meaning: "잎 엽", strokes: 12 },
    { hanja: "曄", meaning: "빛날 엽", strokes: 16 },
  ],
  "영": [
    { hanja: "英", meaning: "꽃부리 영", strokes: 8 },
    { hanja: "永", meaning: "길 영", strokes: 5 },
    { hanja: "榮", meaning: "영화로울 영", strokes: 14 },
    { hanja: "映", meaning: "비칠 영", strokes: 9 },
    { hanja: "瑛", meaning: "옥빛 영", strokes: 12 },
    { hanja: "泳", meaning: "헤엄칠 영", strokes: 8 },
    { hanja: "瀛", meaning: "바다 영", strokes: 19 },
    { hanja: "詠", meaning: "읊을 영", strokes: 12 },
    { hanja: "盈", meaning: "찰 영", strokes: 9 },
    { hanja: "穎", meaning: "이삭 영", strokes: 15 },
    { hanja: "嶺", meaning: "고개 영", strokes: 17 },
    { hanja: "迎", meaning: "맞을 영", strokes: 7 },
    { hanja: "營", meaning: "경영할 영", strokes: 17 },
    { hanja: "影", meaning: "그림자 영", strokes: 15 },
  ],
  "예": [
    { hanja: "藝", meaning: "재주 예", strokes: 18 },
    { hanja: "禮", meaning: "예도 예", strokes: 18 },
    { hanja: "睿", meaning: "슬기로울 예", strokes: 14 },
    { hanja: "芮", meaning: "띠풀 예", strokes: 7 },
    { hanja: "譽", meaning: "기릴 예", strokes: 20 },
    { hanja: "銳", meaning: "날카로울 예", strokes: 15 },
    { hanja: "預", meaning: "미리 예", strokes: 13 },
    { hanja: "叡", meaning: "슬기 예", strokes: 16 },
    { hanja: "穢", meaning: "더러울 예", strokes: 18 },
    { hanja: "曳", meaning: "끌 예", strokes: 6 },
  ],
  "오": [
    { hanja: "吳", meaning: "나라 오", strokes: 7 },
    { hanja: "伍", meaning: "다섯 오", strokes: 6 },
    { hanja: "五", meaning: "다섯 오", strokes: 4 },
    { hanja: "悟", meaning: "깨달을 오", strokes: 10 },
    { hanja: "梧", meaning: "오동나무 오", strokes: 11 },
    { hanja: "旿", meaning: "밝을 오", strokes: 11 },
  ],
  "옥": [
    { hanja: "玉", meaning: "구슬 옥", strokes: 5 },
    { hanja: "沃", meaning: "기름질 옥", strokes: 7 },
  ],
  "온": [
    { hanja: "溫", meaning: "따뜻할 온", strokes: 13 },
    { hanja: "穩", meaning: "편안할 온", strokes: 19 },
  ],
  "완": [
    { hanja: "完", meaning: "완전할 완", strokes: 7 },
    { hanja: "琬", meaning: "아름다운옥 완", strokes: 12 },
    { hanja: "緩", meaning: "느릴 완", strokes: 15 },
    { hanja: "婉", meaning: "아름다울 완", strokes: 11 },
  ],
  "왕": [
    { hanja: "王", meaning: "임금 왕", strokes: 4 },
    { hanja: "旺", meaning: "왕성할 왕", strokes: 8 },
  ],
  "요": [
    { hanja: "堯", meaning: "높을 요", strokes: 12 },
    { hanja: "瑤", meaning: "아름다운옥 요", strokes: 14 },
    { hanja: "耀", meaning: "빛날 요", strokes: 20 },
    { hanja: "曜", meaning: "빛날 요", strokes: 18 },
  ],
  "용": [
    { hanja: "龍", meaning: "용 용", strokes: 16 },
    { hanja: "勇", meaning: "날랠 용", strokes: 9 },
    { hanja: "容", meaning: "얼굴 용", strokes: 10 },
    { hanja: "鎔", meaning: "녹일 용", strokes: 18 },
    { hanja: "庸", meaning: "쓸 용", strokes: 11 },
    { hanja: "瑢", meaning: "옥 용", strokes: 13 },
    { hanja: "用", meaning: "쓸 용", strokes: 5 },
  ],
  "우": [
    { hanja: "宇", meaning: "집 우", strokes: 6 },
    { hanja: "祐", meaning: "도울 우", strokes: 9 },
    { hanja: "友", meaning: "벗 우", strokes: 4 },
    { hanja: "雨", meaning: "비 우", strokes: 8 },
    { hanja: "又", meaning: "또 우", strokes: 2 },
    { hanja: "佑", meaning: "도울 우", strokes: 7 },
    { hanja: "右", meaning: "오른 우", strokes: 5 },
    { hanja: "愚", meaning: "어리석을 우", strokes: 13 },
    { hanja: "遇", meaning: "만날 우", strokes: 12 },
    { hanja: "瑀", meaning: "옥 우", strokes: 13 },
    { hanja: "羽", meaning: "깃 우", strokes: 6 },
    { hanja: "禹", meaning: "임금 우", strokes: 9 },
  ],
  "욱": [
    { hanja: "旭", meaning: "밝을 욱", strokes: 6 },
    { hanja: "昱", meaning: "밝을 욱", strokes: 9 },
    { hanja: "郁", meaning: "향기 욱", strokes: 9 },
    { hanja: "煜", meaning: "빛날 욱", strokes: 13 },
    { hanja: "頊", meaning: "밝을 욱", strokes: 13 },
  ],
  "운": [
    { hanja: "雲", meaning: "구름 운", strokes: 12 },
    { hanja: "云", meaning: "이를 운", strokes: 4 },
    { hanja: "韻", meaning: "운 운", strokes: 19 },
    { hanja: "芸", meaning: "풀 운", strokes: 7 },
  ],
  "웅": [
    { hanja: "雄", meaning: "수컷 웅", strokes: 12 },
    { hanja: "熊", meaning: "곰 웅", strokes: 14 },
  ],
  "원": [
    { hanja: "元", meaning: "으뜸 원", strokes: 4 },
    { hanja: "源", meaning: "근원 원", strokes: 13 },
    { hanja: "遠", meaning: "멀 원", strokes: 13 },
    { hanja: "園", meaning: "동산 원", strokes: 13 },
    { hanja: "願", meaning: "원할 원", strokes: 19 },
    { hanja: "院", meaning: "집 원", strokes: 10 },
    { hanja: "圓", meaning: "둥글 원", strokes: 13 },
    { hanja: "原", meaning: "근원 원", strokes: 10 },
    { hanja: "瑗", meaning: "옥 원", strokes: 13 },
    { hanja: "媛", meaning: "아름다울 원", strokes: 12 },
    { hanja: "援", meaning: "도울 원", strokes: 12 },
    { hanja: "垣", meaning: "담 원", strokes: 9 },
  ],
  "월": [
    { hanja: "月", meaning: "달 월", strokes: 4 },
    { hanja: "越", meaning: "넘을 월", strokes: 12 },
  ],
  "위": [
    { hanja: "偉", meaning: "클 위", strokes: 11 },
    { hanja: "韋", meaning: "가죽 위", strokes: 9 },
    { hanja: "威", meaning: "위엄 위", strokes: 9 },
    { hanja: "衛", meaning: "지킬 위", strokes: 15 },
    { hanja: "瑋", meaning: "옥 위", strokes: 13 },
    { hanja: "暐", meaning: "빛날 위", strokes: 13 },
    { hanja: "渭", meaning: "물이름 위", strokes: 12 },
  ],
  "유": [
    { hanja: "劉", meaning: "죽일 유", strokes: 15 },
    { hanja: "柳", meaning: "버들 유", strokes: 9 },
    { hanja: "兪", meaning: "성씨 유", strokes: 9 },
    { hanja: "裕", meaning: "넉넉할 유", strokes: 12 },
    { hanja: "有", meaning: "있을 유", strokes: 6 },
    { hanja: "惟", meaning: "생각할 유", strokes: 11 },
    { hanja: "由", meaning: "말미암을 유", strokes: 5 },
    { hanja: "唯", meaning: "오직 유", strokes: 11 },
    { hanja: "遊", meaning: "놀 유", strokes: 12 },
    { hanja: "悠", meaning: "멀 유", strokes: 11 },
    { hanja: "維", meaning: "벼리 유", strokes: 14 },
    { hanja: "愉", meaning: "기쁠 유", strokes: 12 },
    { hanja: "瑜", meaning: "아름다운옥 유", strokes: 13 },
    { hanja: "宥", meaning: "너그러울 유", strokes: 9 },
    { hanja: "油", meaning: "기름 유", strokes: 8 },
    { hanja: "幼", meaning: "어릴 유", strokes: 5 },
    { hanja: "儒", meaning: "선비 유", strokes: 16 },
  ],
  "육": [
    { hanja: "育", meaning: "기를 육", strokes: 8 },
    { hanja: "六", meaning: "여섯 육", strokes: 4 },
  ],
  "율": [
    { hanja: "律", meaning: "법률 율", strokes: 9 },
    { hanja: "栗", meaning: "밤 율", strokes: 10 },
    { hanja: "率", meaning: "비율 율", strokes: 11 },
    { hanja: "慄", meaning: "두려울 율", strokes: 13 },
  ],
  "융": [
    { hanja: "融", meaning: "녹을 융", strokes: 16 },
    { hanja: "隆", meaning: "높을 융", strokes: 12 },
    { hanja: "戎", meaning: "병장기 융", strokes: 6 },
  ],
  "윤": [
    { hanja: "潤", meaning: "윤택할 윤", strokes: 15 },
    { hanja: "允", meaning: "진실로 윤", strokes: 4 },
    { hanja: "倫", meaning: "인륜 윤", strokes: 10 },
    { hanja: "尹", meaning: "다스릴 윤", strokes: 4 },
    { hanja: "綸", meaning: "벼리 윤", strokes: 14 },
    { hanja: "胤", meaning: "후손 윤", strokes: 9 },
    { hanja: "玧", meaning: "옥 윤", strokes: 8 },
    { hanja: "鈗", meaning: "창 윤", strokes: 12 },
  ],
  "은": [
    { hanja: "恩", meaning: "은혜 은", strokes: 10 },
    { hanja: "銀", meaning: "은 은", strokes: 14 },
    { hanja: "隱", meaning: "숨을 은", strokes: 16 },
    { hanja: "慇", meaning: "정성 은", strokes: 14 },
    { hanja: "殷", meaning: "나라 은", strokes: 10 },
    { hanja: "垠", meaning: "끝 은", strokes: 9 },
  ],
  "을": [
    { hanja: "乙", meaning: "새 을", strokes: 1 },
  ],
  "응": [
    { hanja: "應", meaning: "응할 응", strokes: 17 },
    { hanja: "鷹", meaning: "매 응", strokes: 24 },
    { hanja: "凝", meaning: "엉길 응", strokes: 16 },
  ],
  "의": [
    { hanja: "義", meaning: "옳을 의", strokes: 13 },
    { hanja: "宜", meaning: "마땅할 의", strokes: 8 },
    { hanja: "毅", meaning: "굳셀 의", strokes: 15 },
    { hanja: "儀", meaning: "거동 의", strokes: 15 },
    { hanja: "意", meaning: "뜻 의", strokes: 13 },
    { hanja: "議", meaning: "의논할 의", strokes: 20 },
    { hanja: "醫", meaning: "의원 의", strokes: 18 },
  ],
  "이": [
    { hanja: "李", meaning: "오얏 이", strokes: 7 },
    { hanja: "理", meaning: "다스릴 리", strokes: 11 },
    { hanja: "二", meaning: "두 이", strokes: 2 },
    { hanja: "以", meaning: "써 이", strokes: 5 },
    { hanja: "異", meaning: "다를 이", strokes: 11 },
    { hanja: "怡", meaning: "기쁠 이", strokes: 8 },
    { hanja: "珥", meaning: "귀고리 이", strokes: 10 },
    { hanja: "頤", meaning: "턱 이", strokes: 15 },
  ],
  "익": [
    { hanja: "翼", meaning: "날개 익", strokes: 17 },
    { hanja: "益", meaning: "더할 익", strokes: 10 },
  ],
  "인": [
    { hanja: "仁", meaning: "어질 인", strokes: 4 },
    { hanja: "寅", meaning: "삼갈 인", strokes: 11 },
    { hanja: "印", meaning: "도장 인", strokes: 6 },
    { hanja: "忍", meaning: "참을 인", strokes: 7 },
    { hanja: "引", meaning: "끌 인", strokes: 4 },
    { hanja: "姻", meaning: "혼인할 인", strokes: 9 },
    { hanja: "因", meaning: "인할 인", strokes: 6 },
    { hanja: "認", meaning: "알 인", strokes: 14 },
    { hanja: "麟", meaning: "기린 인", strokes: 23 },
  ],
  "일": [
    { hanja: "一", meaning: "한 일", strokes: 1 },
    { hanja: "逸", meaning: "편안할 일", strokes: 11 },
    { hanja: "日", meaning: "날 일", strokes: 4 },
    { hanja: "溢", meaning: "넘칠 일", strokes: 13 },
  ],
  "임": [
    { hanja: "林", meaning: "수풀 임", strokes: 8 },
    { hanja: "任", meaning: "맡길 임", strokes: 6 },
    { hanja: "壬", meaning: "북방 임", strokes: 4 },
    { hanja: "臨", meaning: "임할 임", strokes: 17 },
  ],
  // ㅈ
  "자": [
    { hanja: "慈", meaning: "사랑 자", strokes: 13 },
    { hanja: "紫", meaning: "자주 자", strokes: 12 },
    { hanja: "子", meaning: "아들 자", strokes: 3 },
    { hanja: "資", meaning: "재물 자", strokes: 13 },
    { hanja: "姿", meaning: "모양 자", strokes: 9 },
    { hanja: "滋", meaning: "불을 자", strokes: 12 },
    { hanja: "玆", meaning: "이 자", strokes: 9 },
    { hanja: "字", meaning: "글자 자", strokes: 6 },
  ],
  "작": [
    { hanja: "爵", meaning: "벼슬 작", strokes: 17 },
  ],
  "잔": [
    { hanja: "棧", meaning: "선반 잔", strokes: 12 },
  ],
  "장": [
    { hanja: "張", meaning: "베풀 장", strokes: 11 },
    { hanja: "莊", meaning: "씩씩할 장", strokes: 13 },
    { hanja: "章", meaning: "글 장", strokes: 11 },
    { hanja: "璋", meaning: "옥 장", strokes: 15 },
    { hanja: "長", meaning: "긴 장", strokes: 8 },
    { hanja: "壯", meaning: "씩씩할 장", strokes: 7 },
    { hanja: "將", meaning: "장수 장", strokes: 11 },
    { hanja: "藏", meaning: "감출 장", strokes: 17 },
    { hanja: "奬", meaning: "장려할 장", strokes: 14 },
  ],
  "재": [
    { hanja: "在", meaning: "있을 재", strokes: 6 },
    { hanja: "才", meaning: "재주 재", strokes: 3 },
    { hanja: "宰", meaning: "재상 재", strokes: 10 },
    { hanja: "載", meaning: "실을 재", strokes: 13 },
    { hanja: "哉", meaning: "어조사 재", strokes: 9 },
    { hanja: "財", meaning: "재물 재", strokes: 10 },
    { hanja: "材", meaning: "재목 재", strokes: 7 },
    { hanja: "栽", meaning: "심을 재", strokes: 10 },
  ],
  "저": [
    { hanja: "貯", meaning: "쌓을 저", strokes: 12 },
    { hanja: "著", meaning: "나타날 저", strokes: 11 },
  ],
  "적": [
    { hanja: "績", meaning: "공적 적", strokes: 17 },
    { hanja: "積", meaning: "쌓을 적", strokes: 16 },
  ],
  "전": [
    { hanja: "全", meaning: "온전할 전", strokes: 6 },
    { hanja: "田", meaning: "밭 전", strokes: 5 },
    { hanja: "典", meaning: "법 전", strokes: 8 },
    { hanja: "展", meaning: "펼 전", strokes: 10 },
    { hanja: "殿", meaning: "큰집 전", strokes: 13 },
    { hanja: "傳", meaning: "전할 전", strokes: 13 },
    { hanja: "銓", meaning: "저울 전", strokes: 14 },
  ],
  "정": [
    { hanja: "正", meaning: "바를 정", strokes: 5 },
    { hanja: "貞", meaning: "곧을 정", strokes: 9 },
    { hanja: "靖", meaning: "편안할 정", strokes: 13 },
    { hanja: "晶", meaning: "밝을 정", strokes: 12 },
    { hanja: "廷", meaning: "조정 정", strokes: 7 },
    { hanja: "鄭", meaning: "성씨 정", strokes: 19 },
    { hanja: "定", meaning: "정할 정", strokes: 8 },
    { hanja: "情", meaning: "뜻 정", strokes: 11 },
    { hanja: "精", meaning: "정할 정", strokes: 14 },
    { hanja: "政", meaning: "정사 정", strokes: 8 },
    { hanja: "楨", meaning: "나무 정", strokes: 13 },
    { hanja: "禎", meaning: "상서로울 정", strokes: 13 },
    { hanja: "庭", meaning: "뜰 정", strokes: 10 },
    { hanja: "丁", meaning: "고무래 정", strokes: 2 },
    { hanja: "淨", meaning: "깨끗할 정", strokes: 11 },
    { hanja: "幀", meaning: "그림 정", strokes: 12 },
  ],
  "제": [
    { hanja: "濟", meaning: "건널 제", strokes: 17 },
    { hanja: "帝", meaning: "임금 제", strokes: 9 },
    { hanja: "齊", meaning: "가지런할 제", strokes: 14 },
    { hanja: "制", meaning: "지을 제", strokes: 8 },
    { hanja: "諸", meaning: "모든 제", strokes: 15 },
    { hanja: "際", meaning: "사이 제", strokes: 14 },
  ],
  "조": [
    { hanja: "趙", meaning: "나라 조", strokes: 14 },
    { hanja: "曺", meaning: "무리 조", strokes: 11 },
    { hanja: "祖", meaning: "조상 조", strokes: 9 },
    { hanja: "兆", meaning: "조짐 조", strokes: 6 },
    { hanja: "朝", meaning: "아침 조", strokes: 12 },
    { hanja: "照", meaning: "비출 조", strokes: 13 },
    { hanja: "造", meaning: "지을 조", strokes: 10 },
    { hanja: "棗", meaning: "대추 조", strokes: 12 },
  ],
  "종": [
    { hanja: "宗", meaning: "으뜸 종", strokes: 8 },
    { hanja: "鐘", meaning: "쇠북 종", strokes: 20 },
    { hanja: "種", meaning: "씨 종", strokes: 14 },
    { hanja: "鍾", meaning: "쇠북 종", strokes: 17 },
    { hanja: "從", meaning: "좇을 종", strokes: 11 },
    { hanja: "縱", meaning: "세로 종", strokes: 17 },
  ],
  "주": [
    { hanja: "柱", meaning: "기둥 주", strokes: 9 },
    { hanja: "周", meaning: "두루 주", strokes: 8 },
    { hanja: "珠", meaning: "구슬 주", strokes: 10 },
    { hanja: "朱", meaning: "붉을 주", strokes: 6 },
    { hanja: "胄", meaning: "후손 주", strokes: 9 },
    { hanja: "住", meaning: "살 주", strokes: 7 },
    { hanja: "主", meaning: "주인 주", strokes: 5 },
    { hanja: "注", meaning: "부을 주", strokes: 8 },
    { hanja: "州", meaning: "고을 주", strokes: 6 },
    { hanja: "做", meaning: "지을 주", strokes: 11 },
  ],
  "준": [
    { hanja: "俊", meaning: "준걸 준", strokes: 9 },
    { hanja: "準", meaning: "준할 준", strokes: 13 },
    { hanja: "峻", meaning: "높을 준", strokes: 10 },
    { hanja: "浚", meaning: "깊을 준", strokes: 10 },
    { hanja: "駿", meaning: "준마 준", strokes: 17 },
    { hanja: "遵", meaning: "좇을 준", strokes: 15 },
    { hanja: "濬", meaning: "깊을 준", strokes: 17 },
    { hanja: "竣", meaning: "마칠 준", strokes: 12 },
    { hanja: "雋", meaning: "뛰어날 준", strokes: 12 },
    { hanja: "畯", meaning: "농사 준", strokes: 13 },
    { hanja: "儁", meaning: "준걸 준", strokes: 15 },
  ],
  "중": [
    { hanja: "中", meaning: "가운데 중", strokes: 4 },
    { hanja: "重", meaning: "무거울 중", strokes: 9 },
    { hanja: "仲", meaning: "버금 중", strokes: 6 },
    { hanja: "衆", meaning: "무리 중", strokes: 12 },
  ],
  "지": [
    { hanja: "智", meaning: "슬기 지", strokes: 12 },
    { hanja: "志", meaning: "뜻 지", strokes: 7 },
    { hanja: "知", meaning: "알 지", strokes: 8 },
    { hanja: "芝", meaning: "지초 지", strokes: 6 },
    { hanja: "枝", meaning: "가지 지", strokes: 8 },
    { hanja: "地", meaning: "땅 지", strokes: 6 },
    { hanja: "池", meaning: "못 지", strokes: 6 },
    { hanja: "至", meaning: "이를 지", strokes: 6 },
    { hanja: "止", meaning: "그칠 지", strokes: 4 },
    { hanja: "持", meaning: "가질 지", strokes: 9 },
    { hanja: "指", meaning: "가리킬 지", strokes: 9 },
    { hanja: "祉", meaning: "복 지", strokes: 8 },
    { hanja: "之", meaning: "갈 지", strokes: 4 },
    { hanja: "紙", meaning: "종이 지", strokes: 10 },
    { hanja: "址", meaning: "터 지", strokes: 7 },
  ],
  "직": [
    { hanja: "直", meaning: "곧을 직", strokes: 8 },
    { hanja: "稷", meaning: "기장 직", strokes: 15 },
  ],
  "진": [
    { hanja: "眞", meaning: "참 진", strokes: 10 },
    { hanja: "鎭", meaning: "진압할 진", strokes: 18 },
    { hanja: "晉", meaning: "나아갈 진", strokes: 10 },
    { hanja: "珍", meaning: "보배 진", strokes: 9 },
    { hanja: "振", meaning: "떨칠 진", strokes: 10 },
    { hanja: "陳", meaning: "진칠 진", strokes: 11 },
    { hanja: "進", meaning: "나아갈 진", strokes: 11 },
    { hanja: "津", meaning: "나루 진", strokes: 9 },
    { hanja: "秦", meaning: "나라 진", strokes: 10 },
    { hanja: "辰", meaning: "별 진", strokes: 7 },
    { hanja: "瑨", meaning: "옥 진", strokes: 14 },
    { hanja: "璡", meaning: "옥 진", strokes: 16 },
  ],
  // ㅊ
  "차": [
    { hanja: "車", meaning: "수레 차", strokes: 7 },
    { hanja: "次", meaning: "버금 차", strokes: 6 },
    { hanja: "差", meaning: "다를 차", strokes: 10 },
  ],
  "찬": [
    { hanja: "燦", meaning: "빛날 찬", strokes: 17 },
    { hanja: "贊", meaning: "도울 찬", strokes: 19 },
    { hanja: "粲", meaning: "빛날 찬", strokes: 13 },
    { hanja: "璨", meaning: "옥빛 찬", strokes: 17 },
    { hanja: "餐", meaning: "먹을 찬", strokes: 16 },
    { hanja: "瓚", meaning: "제기 찬", strokes: 22 },
  ],
  "창": [
    { hanja: "昌", meaning: "창성할 창", strokes: 8 },
    { hanja: "彰", meaning: "밝을 창", strokes: 14 },
    { hanja: "蒼", meaning: "푸를 창", strokes: 13 },
    { hanja: "窓", meaning: "창 창", strokes: 11 },
    { hanja: "倉", meaning: "곳집 창", strokes: 10 },
    { hanja: "暢", meaning: "펼 창", strokes: 14 },
    { hanja: "唱", meaning: "부를 창", strokes: 11 },
    { hanja: "滄", meaning: "푸를 창", strokes: 13 },
    { hanja: "菖", meaning: "창포 창", strokes: 11 },
  ],
  "채": [
    { hanja: "采", meaning: "캘 채", strokes: 8 },
    { hanja: "彩", meaning: "빛 채", strokes: 11 },
    { hanja: "蔡", meaning: "성씨 채", strokes: 14 },
    { hanja: "採", meaning: "캘 채", strokes: 11 },
    { hanja: "菜", meaning: "나물 채", strokes: 11 },
    { hanja: "債", meaning: "빚 채", strokes: 13 },
  ],
  "천": [
    { hanja: "天", meaning: "하늘 천", strokes: 4 },
    { hanja: "千", meaning: "일천 천", strokes: 3 },
    { hanja: "泉", meaning: "샘 천", strokes: 9 },
    { hanja: "川", meaning: "내 천", strokes: 3 },
    { hanja: "淺", meaning: "얕을 천", strokes: 11 },
    { hanja: "賤", meaning: "천할 천", strokes: 15 },
    { hanja: "薦", meaning: "천거할 천", strokes: 16 },
    { hanja: "踐", meaning: "밟을 천", strokes: 15 },
  ],
  "철": [
    { hanja: "哲", meaning: "밝을 철", strokes: 10 },
    { hanja: "徹", meaning: "통할 철", strokes: 15 },
    { hanja: "鐵", meaning: "쇠 철", strokes: 21 },
    { hanja: "喆", meaning: "밝을 철", strokes: 12 },
    { hanja: "澈", meaning: "맑을 철", strokes: 15 },
  ],
  "첨": [
    { hanja: "瞻", meaning: "볼 첨", strokes: 18 },
    { hanja: "添", meaning: "더할 첨", strokes: 11 },
  ],
  "청": [
    { hanja: "淸", meaning: "맑을 청", strokes: 11 },
    { hanja: "靑", meaning: "푸를 청", strokes: 8 },
    { hanja: "請", meaning: "청할 청", strokes: 15 },
    { hanja: "聽", meaning: "들을 청", strokes: 22 },
  ],
  "초": [
    { hanja: "初", meaning: "처음 초", strokes: 7 },
    { hanja: "超", meaning: "뛰어넘을 초", strokes: 12 },
    { hanja: "草", meaning: "풀 초", strokes: 9 },
    { hanja: "礎", meaning: "주춧돌 초", strokes: 18 },
    { hanja: "肖", meaning: "닮을 초", strokes: 7 },
    { hanja: "楚", meaning: "나라 초", strokes: 13 },
  ],
  "촌": [
    { hanja: "村", meaning: "마을 촌", strokes: 7 },
  ],
  "총": [
    { hanja: "聰", meaning: "귀밝을 총", strokes: 17 },
    { hanja: "寵", meaning: "사랑할 총", strokes: 19 },
  ],
  "추": [
    { hanja: "秋", meaning: "가을 추", strokes: 9 },
    { hanja: "秀", meaning: "빼어날 추", strokes: 7 },
    { hanja: "追", meaning: "쫓을 추", strokes: 9 },
    { hanja: "樞", meaning: "지도리 추", strokes: 15 },
  ],
  "축": [
    { hanja: "祝", meaning: "빌 축", strokes: 9 },
    { hanja: "築", meaning: "쌓을 축", strokes: 16 },
  ],
  "춘": [
    { hanja: "春", meaning: "봄 춘", strokes: 9 },
    { hanja: "椿", meaning: "참죽나무 춘", strokes: 13 },
  ],
  "충": [
    { hanja: "忠", meaning: "충성 충", strokes: 8 },
    { hanja: "沖", meaning: "화할 충", strokes: 7 },
    { hanja: "冲", meaning: "빌 충", strokes: 6 },
    { hanja: "衝", meaning: "찌를 충", strokes: 15 },
  ],
  "취": [
    { hanja: "翠", meaning: "푸를 취", strokes: 14 },
    { hanja: "取", meaning: "가질 취", strokes: 8 },
    { hanja: "吹", meaning: "불 취", strokes: 7 },
  ],
  "치": [
    { hanja: "致", meaning: "이를 치", strokes: 10 },
    { hanja: "治", meaning: "다스릴 치", strokes: 8 },
    { hanja: "値", meaning: "값 치", strokes: 10 },
  ],
  // ㅌ
  "탁": [
    { hanja: "卓", meaning: "높을 탁", strokes: 8 },
    { hanja: "拓", meaning: "넓힐 탁", strokes: 8 },
    { hanja: "濯", meaning: "씻을 탁", strokes: 17 },
    { hanja: "琢", meaning: "쪼을 탁", strokes: 12 },
    { hanja: "度", meaning: "헤아릴 탁", strokes: 9 },
    { hanja: "鐸", meaning: "방울 탁", strokes: 21 },
  ],
  "탄": [
    { hanja: "坦", meaning: "평평할 탄", strokes: 8 },
    { hanja: "誕", meaning: "태어날 탄", strokes: 15 },
  ],
  "태": [
    { hanja: "泰", meaning: "클 태", strokes: 10 },
    { hanja: "太", meaning: "클 태", strokes: 4 },
    { hanja: "汰", meaning: "일 태", strokes: 7 },
    { hanja: "台", meaning: "별 태", strokes: 5 },
    { hanja: "胎", meaning: "아이밸 태", strokes: 9 },
    { hanja: "態", meaning: "모양 태", strokes: 14 },
    { hanja: "苔", meaning: "이끼 태", strokes: 8 },
  ],
  "택": [
    { hanja: "澤", meaning: "못 택", strokes: 16 },
    { hanja: "擇", meaning: "가릴 택", strokes: 16 },
    { hanja: "宅", meaning: "집 택", strokes: 6 },
    { hanja: "翟", meaning: "꿩 택", strokes: 14 },
  ],
  "토": [
    { hanja: "土", meaning: "흙 토", strokes: 3 },
    { hanja: "兎", meaning: "토끼 토", strokes: 7 },
  ],
  "통": [
    { hanja: "通", meaning: "통할 통", strokes: 10 },
    { hanja: "統", meaning: "거느릴 통", strokes: 12 },
  ],
  // ㅍ
  "판": [
    { hanja: "判", meaning: "판단할 판", strokes: 7 },
    { hanja: "版", meaning: "판목 판", strokes: 8 },
  ],
  "팔": [
    { hanja: "八", meaning: "여덟 팔", strokes: 2 },
  ],
  "패": [
    { hanja: "覇", meaning: "으뜸 패", strokes: 19 },
  ],
  "평": [
    { hanja: "平", meaning: "평평할 평", strokes: 5 },
    { hanja: "坪", meaning: "평 평", strokes: 8 },
    { hanja: "評", meaning: "평할 평", strokes: 12 },
  ],
  "포": [
    { hanja: "浦", meaning: "개 포", strokes: 10 },
    { hanja: "抱", meaning: "안을 포", strokes: 8 },
    { hanja: "包", meaning: "쌀 포", strokes: 5 },
    { hanja: "飽", meaning: "배부를 포", strokes: 13 },
    { hanja: "布", meaning: "베 포", strokes: 5 },
  ],
  "표": [
    { hanja: "表", meaning: "겉 표", strokes: 8 },
    { hanja: "彪", meaning: "범무늬 표", strokes: 11 },
    { hanja: "漂", meaning: "떠다닐 표", strokes: 14 },
    { hanja: "標", meaning: "표할 표", strokes: 15 },
  ],
  "풍": [
    { hanja: "豊", meaning: "풍년 풍", strokes: 13 },
    { hanja: "楓", meaning: "단풍 풍", strokes: 13 },
    { hanja: "風", meaning: "바람 풍", strokes: 9 },
    { hanja: "豐", meaning: "풍성할 풍", strokes: 18 },
  ],
  "피": [
    { hanja: "彼", meaning: "저 피", strokes: 8 },
    { hanja: "皮", meaning: "가죽 피", strokes: 5 },
  ],
  "필": [
    { hanja: "弼", meaning: "도울 필", strokes: 12 },
    { hanja: "筆", meaning: "붓 필", strokes: 12 },
    { hanja: "必", meaning: "반드시 필", strokes: 5 },
    { hanja: "珌", meaning: "옥 필", strokes: 9 },
  ],
  // ㅎ
  "하": [
    { hanja: "夏", meaning: "여름 하", strokes: 10 },
    { hanja: "河", meaning: "물 하", strokes: 8 },
    { hanja: "荷", meaning: "연꽃 하", strokes: 10 },
    { hanja: "賀", meaning: "하례 하", strokes: 12 },
    { hanja: "霞", meaning: "놀 하", strokes: 17 },
    { hanja: "瑕", meaning: "흠 하", strokes: 13 },
    { hanja: "廈", meaning: "큰집 하", strokes: 13 },
  ],
  "학": [
    { hanja: "學", meaning: "배울 학", strokes: 16 },
    { hanja: "鶴", meaning: "학 학", strokes: 21 },
    { hanja: "壑", meaning: "골짜기 학", strokes: 17 },
  ],
  "한": [
    { hanja: "漢", meaning: "한수 한", strokes: 14 },
    { hanja: "翰", meaning: "깃 한", strokes: 16 },
    { hanja: "韓", meaning: "나라 한", strokes: 17 },
    { hanja: "閑", meaning: "한가할 한", strokes: 12 },
    { hanja: "寒", meaning: "찰 한", strokes: 12 },
    { hanja: "恨", meaning: "한 한", strokes: 9 },
    { hanja: "漢", meaning: "한나라 한", strokes: 14 },
  ],
  "함": [
    { hanja: "咸", meaning: "다 함", strokes: 9 },
    { hanja: "涵", meaning: "잠길 함", strokes: 11 },
    { hanja: "函", meaning: "함 함", strokes: 8 },
  ],
  "합": [
    { hanja: "合", meaning: "합할 합", strokes: 6 },
  ],
  "항": [
    { hanja: "恒", meaning: "항상 항", strokes: 9 },
    { hanja: "航", meaning: "배 항", strokes: 10 },
    { hanja: "港", meaning: "항구 항", strokes: 12 },
    { hanja: "抗", meaning: "막을 항", strokes: 7 },
    { hanja: "恒", meaning: "늘 항", strokes: 9 },
  ],
  "해": [
    { hanja: "海", meaning: "바다 해", strokes: 10 },
    { hanja: "奚", meaning: "어찌 해", strokes: 10 },
    { hanja: "亥", meaning: "돼지 해", strokes: 6 },
    { hanja: "諧", meaning: "화할 해", strokes: 16 },
    { hanja: "解", meaning: "풀 해", strokes: 13 },
    { hanja: "害", meaning: "해칠 해", strokes: 10 },
  ],
  "향": [
    { hanja: "香", meaning: "향기 향", strokes: 9 },
    { hanja: "鄕", meaning: "시골 향", strokes: 13 },
    { hanja: "享", meaning: "누릴 향", strokes: 8 },
    { hanja: "響", meaning: "울릴 향", strokes: 20 },
    { hanja: "向", meaning: "향할 향", strokes: 6 },
    { hanja: "饗", meaning: "잔치 향", strokes: 22 },
  ],
  "허": [
    { hanja: "許", meaning: "허락할 허", strokes: 11 },
    { hanja: "虛", meaning: "빌 허", strokes: 12 },
  ],
  "헌": [
    { hanja: "憲", meaning: "법 헌", strokes: 16 },
    { hanja: "獻", meaning: "드릴 헌", strokes: 20 },
    { hanja: "軒", meaning: "집 헌", strokes: 10 },
    { hanja: "瑄", meaning: "옥 헌", strokes: 13 },
  ],
  "혁": [
    { hanja: "赫", meaning: "빛날 혁", strokes: 14 },
    { hanja: "革", meaning: "가죽 혁", strokes: 9 },
    { hanja: "奕", meaning: "빛날 혁", strokes: 9 },
    { hanja: "爀", meaning: "빛날 혁", strokes: 20 },
    { hanja: "赤", meaning: "붉을 혁", strokes: 7 },
    { hanja: "奕", meaning: "크고빛날 혁", strokes: 9 },
  ],
  "현": [
    { hanja: "賢", meaning: "어질 현", strokes: 15 },
    { hanja: "現", meaning: "나타날 현", strokes: 11 },
    { hanja: "玄", meaning: "검을 현", strokes: 5 },
    { hanja: "炫", meaning: "빛날 현", strokes: 9 },
    { hanja: "絃", meaning: "줄 현", strokes: 11 },
    { hanja: "鉉", meaning: "솥귀 현", strokes: 13 },
    { hanja: "顯", meaning: "나타날 현", strokes: 23 },
    { hanja: "晛", meaning: "밝을 현", strokes: 11 },
    { hanja: "弦", meaning: "줄 현", strokes: 8 },
    { hanja: "眩", meaning: "어지러울 현", strokes: 10 },
    { hanja: "暄", meaning: "따뜻할 현", strokes: 13 },
    { hanja: "峴", meaning: "재 현", strokes: 9 },
    { hanja: "泫", meaning: "눈물 현", strokes: 8 },
  ],
  "혜": [
    { hanja: "惠", meaning: "은혜 혜", strokes: 12 },
    { hanja: "慧", meaning: "슬기로울 혜", strokes: 15 },
    { hanja: "蕙", meaning: "난초 혜", strokes: 15 },
    { hanja: "兮", meaning: "어조사 혜", strokes: 4 },
    { hanja: "穗", meaning: "이삭 혜", strokes: 15 },
  ],
  "형": [
    { hanja: "亨", meaning: "형통할 형", strokes: 7 },
    { hanja: "炯", meaning: "밝을 형", strokes: 9 },
    { hanja: "衡", meaning: "저울 형", strokes: 16 },
    { hanja: "形", meaning: "형상 형", strokes: 7 },
    { hanja: "螢", meaning: "반딧불 형", strokes: 16 },
    { hanja: "馨", meaning: "향기로울 형", strokes: 20 },
  ],
  "호": [
    { hanja: "浩", meaning: "넓을 호", strokes: 10 },
    { hanja: "昊", meaning: "하늘 호", strokes: 8 },
    { hanja: "皓", meaning: "밝을 호", strokes: 12 },
    { hanja: "虎", meaning: "범 호", strokes: 8 },
    { hanja: "鎬", meaning: "호경 호", strokes: 18 },
    { hanja: "湖", meaning: "호수 호", strokes: 12 },
    { hanja: "豪", meaning: "호걸 호", strokes: 14 },
    { hanja: "好", meaning: "좋을 호", strokes: 6 },
    { hanja: "呼", meaning: "부를 호", strokes: 8 },
    { hanja: "弧", meaning: "활 호", strokes: 8 },
    { hanja: "琥", meaning: "호박 호", strokes: 12 },
    { hanja: "護", meaning: "보호할 호", strokes: 20 },
    { hanja: "壕", meaning: "해자 호", strokes: 17 },
    { hanja: "鑊", meaning: "가마솥 호", strokes: 22 },
  ],
  "홍": [
    { hanja: "弘", meaning: "넓을 홍", strokes: 5 },
    { hanja: "洪", meaning: "넓을 홍", strokes: 9 },
    { hanja: "泓", meaning: "깊을 홍", strokes: 8 },
    { hanja: "紅", meaning: "붉을 홍", strokes: 9 },
    { hanja: "鴻", meaning: "기러기 홍", strokes: 17 },
    { hanja: "虹", meaning: "무지개 홍", strokes: 9 },
  ],
  "화": [
    { hanja: "華", meaning: "빛날 화", strokes: 10 },
    { hanja: "和", meaning: "화할 화", strokes: 8 },
    { hanja: "花", meaning: "꽃 화", strokes: 7 },
    { hanja: "火", meaning: "불 화", strokes: 4 },
    { hanja: "化", meaning: "될 화", strokes: 4 },
    { hanja: "畵", meaning: "그림 화", strokes: 12 },
    { hanja: "禾", meaning: "벼 화", strokes: 5 },
    { hanja: "樺", meaning: "자작나무 화", strokes: 14 },
  ],
  "환": [
    { hanja: "煥", meaning: "빛날 환", strokes: 13 },
    { hanja: "桓", meaning: "나무 환", strokes: 10 },
    { hanja: "歡", meaning: "기쁠 환", strokes: 21 },
    { hanja: "還", meaning: "돌아올 환", strokes: 16 },
    { hanja: "幻", meaning: "허깨비 환", strokes: 4 },
    { hanja: "煥", meaning: "밝을 환", strokes: 13 },
    { hanja: "喚", meaning: "부를 환", strokes: 12 },
    { hanja: "渙", meaning: "흩어질 환", strokes: 12 },
    { hanja: "寰", meaning: "넓을 환", strokes: 16 },
    { hanja: "丸", meaning: "둥글 환", strokes: 3 },
  ],
  "활": [
    { hanja: "活", meaning: "살 활", strokes: 9 },
    { hanja: "闊", meaning: "넓을 활", strokes: 17 },
  ],
  "황": [
    { hanja: "黃", meaning: "누를 황", strokes: 12 },
    { hanja: "皇", meaning: "임금 황", strokes: 9 },
    { hanja: "凰", meaning: "봉황 황", strokes: 11 },
    { hanja: "晃", meaning: "밝을 황", strokes: 10 },
    { hanja: "煌", meaning: "빛날 황", strokes: 13 },
    { hanja: "潢", meaning: "큰못 황", strokes: 15 },
  ],
  "회": [
    { hanja: "會", meaning: "모일 회", strokes: 13 },
    { hanja: "懷", meaning: "품을 회", strokes: 19 },
    { hanja: "回", meaning: "돌 회", strokes: 6 },
    { hanja: "晦", meaning: "그믐 회", strokes: 11 },
  ],
  "효": [
    { hanja: "孝", meaning: "효도 효", strokes: 7 },
    { hanja: "曉", meaning: "새벽 효", strokes: 16 },
    { hanja: "效", meaning: "본받을 효", strokes: 10 },
    { hanja: "虓", meaning: "범소리 효", strokes: 10 },
  ],
  "후": [
    { hanja: "厚", meaning: "두터울 후", strokes: 9 },
    { hanja: "后", meaning: "뒤 후", strokes: 6 },
    { hanja: "侯", meaning: "제후 후", strokes: 9 },
    { hanja: "候", meaning: "기후 후", strokes: 10 },
  ],
  "훈": [
    { hanja: "勳", meaning: "공 훈", strokes: 16 },
    { hanja: "薰", meaning: "향기 훈", strokes: 17 },
    { hanja: "訓", meaning: "가르칠 훈", strokes: 10 },
    { hanja: "塤", meaning: "질그릇 훈", strokes: 13 },
    { hanja: "暈", meaning: "빛무리 훈", strokes: 13 },
    { hanja: "燻", meaning: "그슬릴 훈", strokes: 18 },
  ],
  "훤": [
    { hanja: "暄", meaning: "따뜻할 훤", strokes: 13 },
    { hanja: "萱", meaning: "원추리 훤", strokes: 12 },
  ],
  "휘": [
    { hanja: "輝", meaning: "빛날 휘", strokes: 15 },
    { hanja: "暉", meaning: "빛 휘", strokes: 13 },
    { hanja: "徽", meaning: "아름다울 휘", strokes: 17 },
    { hanja: "揮", meaning: "휘두를 휘", strokes: 12 },
    { hanja: "煇", meaning: "빛날 휘", strokes: 13 },
    { hanja: "彙", meaning: "모을 휘", strokes: 13 },
  ],
  "흠": [
    { hanja: "欽", meaning: "공경할 흠", strokes: 12 },
  ],
  "흥": [
    { hanja: "興", meaning: "일어날 흥", strokes: 16 },
  ],
  "희": [
    { hanja: "熙", meaning: "빛날 희", strokes: 13 },
    { hanja: "喜", meaning: "기쁠 희", strokes: 12 },
    { hanja: "禧", meaning: "복 희", strokes: 17 },
    { hanja: "僖", meaning: "기쁠 희", strokes: 14 },
    { hanja: "姬", meaning: "성씨 희", strokes: 10 },
    { hanja: "曦", meaning: "아침 해 희", strokes: 20 },
    { hanja: "稀", meaning: "드물 희", strokes: 12 },
    { hanja: "羲", meaning: "기 희", strokes: 16 },
    { hanja: "犧", meaning: "희생 희", strokes: 20 },
    { hanja: "戲", meaning: "놀 희", strokes: 17 },
    { hanja: "嬉", meaning: "기쁠 희", strokes: 15 },
    { hanja: "煕", meaning: "빛날 희", strokes: 13 },
  ],
  // ── 추가 성씨 ──
  "갑": [
    { hanja: "甲", meaning: "갑옷 갑", strokes: 5 },
  ],
  "겸": [
    { hanja: "謙", meaning: "겸손할 겸", strokes: 17 },
    { hanja: "兼", meaning: "겸할 겸", strokes: 10 },
    { hanja: "鎌", meaning: "낫 겸", strokes: 18 },
    { hanja: "謙", meaning: "겸허할 겸", strokes: 17 },
  ],
  "고": [
    { hanja: "高", meaning: "높을 고", strokes: 10 },
    { hanja: "古", meaning: "예 고", strokes: 5 },
    { hanja: "顧", meaning: "돌아볼 고", strokes: 21 },
    { hanja: "孤", meaning: "외로울 고", strokes: 8 },
    { hanja: "固", meaning: "굳을 고", strokes: 8 },
    { hanja: "苦", meaning: "쓸 고", strokes: 8 },
  ],
  "곤": [
    { hanja: "坤", meaning: "땅 곤", strokes: 8 },
    { hanja: "崑", meaning: "산이름 곤", strokes: 11 },
    { hanja: "昆", meaning: "형 곤", strokes: 8 },
  ],
  "곽": [
    { hanja: "郭", meaning: "성곽 곽", strokes: 11 },
    { hanja: "霍", meaning: "빠를 곽", strokes: 16 },
  ],
  "관": [
    { hanja: "冠", meaning: "갓 관", strokes: 9 },
    { hanja: "寬", meaning: "너그러울 관", strokes: 15 },
    { hanja: "觀", meaning: "볼 관", strokes: 25 },
    { hanja: "官", meaning: "벼슬 관", strokes: 8 },
    { hanja: "貫", meaning: "꿸 관", strokes: 11 },
    { hanja: "管", meaning: "대롱 관", strokes: 14 },
    { hanja: "灌", meaning: "물댈 관", strokes: 20 },
  ],
  "공": [
    { hanja: "公", meaning: "공변될 공", strokes: 4 },
    { hanja: "孔", meaning: "구멍 공", strokes: 4 },
    { hanja: "功", meaning: "공 공", strokes: 5 },
    { hanja: "空", meaning: "빌 공", strokes: 8 },
    { hanja: "恭", meaning: "공손할 공", strokes: 10 },
    { hanja: "貢", meaning: "바칠 공", strokes: 10 },
  ],
  "권": [
    { hanja: "權", meaning: "권세 권", strokes: 22 },
    { hanja: "勸", meaning: "권할 권", strokes: 20 },
    { hanja: "券", meaning: "문서 권", strokes: 8 },
    { hanja: "拳", meaning: "주먹 권", strokes: 10 },
  ],
  "김": [
    { hanja: "金", meaning: "쇠 김", strokes: 8 },
  ],
  "노": [
    { hanja: "魯", meaning: "노나라 노", strokes: 15 },
    { hanja: "盧", meaning: "그릇 노", strokes: 16 },
    { hanja: "努", meaning: "힘쓸 노", strokes: 7 },
    { hanja: "怒", meaning: "성낼 노", strokes: 9 },
  ],
  "마": [
    { hanja: "馬", meaning: "말 마", strokes: 10 },
    { hanja: "磨", meaning: "갈 마", strokes: 16 },
    { hanja: "麻", meaning: "삼 마", strokes: 11 },
  ],
  "손": [
    { hanja: "孫", meaning: "손자 손", strokes: 10 },
    { hanja: "遜", meaning: "겸손할 손", strokes: 13 },
  ],
  "최": [
    { hanja: "崔", meaning: "높을 최", strokes: 11 },
    { hanja: "催", meaning: "재촉할 최", strokes: 13 },
  ],
  // ── 추가 확장: ㄱ ──
  "감": [
    { hanja: "甘", meaning: "달 감", strokes: 5 },
    { hanja: "感", meaning: "느낄 감", strokes: 13 },
    { hanja: "鑑", meaning: "거울 감", strokes: 22 },
    { hanja: "監", meaning: "볼 감", strokes: 14 },
    { hanja: "減", meaning: "덜 감", strokes: 12 },
    { hanja: "紺", meaning: "감색 감", strokes: 11 },
    { hanja: "敢", meaning: "감히 감", strokes: 12 },
    { hanja: "柑", meaning: "감나무 감", strokes: 9 },
  ],
  "개": [
    { hanja: "開", meaning: "열 개", strokes: 12 },
    { hanja: "凱", meaning: "개선할 개", strokes: 12 },
    { hanja: "愷", meaning: "즐거울 개", strokes: 13 },
    { hanja: "蓋", meaning: "덮을 개", strokes: 13 },
    { hanja: "慨", meaning: "분개할 개", strokes: 13 },
  ],
  "거": [
    { hanja: "巨", meaning: "클 거", strokes: 5 },
    { hanja: "居", meaning: "살 거", strokes: 8 },
    { hanja: "擧", meaning: "들 거", strokes: 17 },
    { hanja: "鉅", meaning: "클 거", strokes: 13 },
    { hanja: "渠", meaning: "도랑 거", strokes: 11 },
  ],
  "격": [
    { hanja: "格", meaning: "격식 격", strokes: 10 },
    { hanja: "激", meaning: "격할 격", strokes: 16 },
    { hanja: "擊", meaning: "칠 격", strokes: 17 },
  ],
  "견": [
    { hanja: "堅", meaning: "굳을 견", strokes: 12 },
    { hanja: "絹", meaning: "비단 견", strokes: 13 },
    { hanja: "甄", meaning: "살필 견", strokes: 13 },
    { hanja: "繭", meaning: "고치 견", strokes: 18 },
    { hanja: "鵑", meaning: "두견 견", strokes: 18 },
    { hanja: "肩", meaning: "어깨 견", strokes: 8 },
  ],
  "결": [
    { hanja: "潔", meaning: "깨끗할 결", strokes: 15 },
    { hanja: "結", meaning: "맺을 결", strokes: 12 },
    { hanja: "決", meaning: "결단할 결", strokes: 7 },
  ],
  "곡": [
    { hanja: "谷", meaning: "골 곡", strokes: 7 },
    { hanja: "曲", meaning: "굽을 곡", strokes: 6 },
  ],
  "골": [
    { hanja: "骨", meaning: "뼈 골", strokes: 10 },
  ],
  "괄": [
    { hanja: "括", meaning: "묶을 괄", strokes: 9 },
  ],
  "괴": [
    { hanja: "槐", meaning: "회화나무 괴", strokes: 14 },
    { hanja: "魁", meaning: "우두머리 괴", strokes: 14 },
  ],
  // ── 추가 확장: ㄴ ──
  "납": [
    { hanja: "納", meaning: "들일 납", strokes: 10 },
  ],
  "내": [
    { hanja: "乃", meaning: "이에 내", strokes: 2 },
    { hanja: "奈", meaning: "어찌 내", strokes: 8 },
    { hanja: "耐", meaning: "견딜 내", strokes: 9 },
  ],
  "녀": [
    { hanja: "女", meaning: "여자 녀", strokes: 3 },
  ],
  "년": [
    { hanja: "年", meaning: "해 년", strokes: 6 },
  ],
  "념": [
    { hanja: "念", meaning: "생각할 념", strokes: 8 },
  ],
  "농": [
    { hanja: "農", meaning: "농사 농", strokes: 13 },
    { hanja: "濃", meaning: "짙을 농", strokes: 16 },
  ],
  "뇌": [
    { hanja: "雷", meaning: "우레 뇌", strokes: 13 },
  ],
  "누": [
    { hanja: "樓", meaning: "다락 누", strokes: 15 },
  ],
  // ── 추가 확장: ㄷ ──
  "독": [
    { hanja: "獨", meaning: "홀로 독", strokes: 16 },
    { hanja: "篤", meaning: "도타울 독", strokes: 16 },
    { hanja: "讀", meaning: "읽을 독", strokes: 22 },
  ],
  "돌": [
    { hanja: "突", meaning: "갑자기 돌", strokes: 9 },
  ],
  // ── 추가 확장: ㅁ ~ ㅎ ──
  "맥": [
    { hanja: "脈", meaning: "핏줄 맥", strokes: 10 },
    { hanja: "麥", meaning: "보리 맥", strokes: 11 },
  ],
  "멱": [
    { hanja: "冪", meaning: "거듭제곱 멱", strokes: 14 },
  ],
  "번": [
    { hanja: "繁", meaning: "번성할 번", strokes: 17 },
    { hanja: "燔", meaning: "불사를 번", strokes: 16 },
    { hanja: "蕃", meaning: "번성할 번", strokes: 15 },
    { hanja: "番", meaning: "차례 번", strokes: 12 },
    { hanja: "飜", meaning: "뒤집을 번", strokes: 18 },
  ],
  "벌": [
    { hanja: "伐", meaning: "칠 벌", strokes: 6 },
    { hanja: "罰", meaning: "벌할 벌", strokes: 14 },
  ],
  "봄": [
    { hanja: "春", meaning: "봄 봄", strokes: 9 },
  ],
  "비": [
    { hanja: "飛", meaning: "날 비", strokes: 9 },
    { hanja: "比", meaning: "견줄 비", strokes: 4 },
    { hanja: "妃", meaning: "왕비 비", strokes: 6 },
    { hanja: "琵", meaning: "비파 비", strokes: 12 },
    { hanja: "碑", meaning: "비석 비", strokes: 13 },
    { hanja: "秘", meaning: "숨길 비", strokes: 10 },
    { hanja: "丕", meaning: "클 비", strokes: 5 },
    { hanja: "備", meaning: "갖출 비", strokes: 12 },
  ],
  "빛": [
    { hanja: "光", meaning: "빛 빛", strokes: 6 },
  ],
  "삭": [
    { hanja: "朔", meaning: "초하루 삭", strokes: 10 },
  ],
  "생": [
    { hanja: "生", meaning: "날 생", strokes: 5 },
    { hanja: "甥", meaning: "생질 생", strokes: 12 },
  ],
  "섬": [
    { hanja: "纖", meaning: "가늘 섬", strokes: 17 },
  ],
  "설": [
    { hanja: "雪", meaning: "눈 설", strokes: 11 },
    { hanja: "薛", meaning: "성씨 설", strokes: 16 },
    { hanja: "設", meaning: "베풀 설", strokes: 11 },
    { hanja: "說", meaning: "말씀 설", strokes: 14 },
    { hanja: "屑", meaning: "부스러기 설", strokes: 10 },
  ],
  "솜": [
    { hanja: "綿", meaning: "솜 솜", strokes: 14 },
  ],
  "실": [
    { hanja: "實", meaning: "열매 실", strokes: 14 },
    { hanja: "室", meaning: "집 실", strokes: 9 },
  ],
  "쌍": [
    { hanja: "雙", meaning: "쌍 쌍", strokes: 18 },
  ],
  "앙": [
    { hanja: "央", meaning: "가운데 앙", strokes: 5 },
    { hanja: "昻", meaning: "우뚝 앙", strokes: 8 },
    { hanja: "仰", meaning: "우러를 앙", strokes: 6 },
  ],
  "액": [
    { hanja: "額", meaning: "이마 액", strokes: 18 },
  ],
  "야": [
    { hanja: "也", meaning: "어조사 야", strokes: 3 },
    { hanja: "野", meaning: "들 야", strokes: 11 },
    { hanja: "夜", meaning: "밤 야", strokes: 8 },
    { hanja: "耶", meaning: "어조사 야", strokes: 9 },
  ],
  "약": [
    { hanja: "若", meaning: "같을 약", strokes: 8 },
    { hanja: "約", meaning: "약속할 약", strokes: 9 },
    { hanja: "躍", meaning: "뛸 약", strokes: 21 },
    { hanja: "藥", meaning: "약 약", strokes: 18 },
  ],
  "언": [
    { hanja: "彦", meaning: "선비 언", strokes: 9 },
    { hanja: "言", meaning: "말씀 언", strokes: 7 },
    { hanja: "彥", meaning: "선비 언", strokes: 9 },
  ],
  // ── 대규모 확장 2차: 신규 음절 ──
  "갈": [
    { hanja: "葛", meaning: "칡 갈", strokes: 12 },
    { hanja: "渴", meaning: "목마를 갈", strokes: 12 },
    { hanja: "褐", meaning: "갈색 갈", strokes: 14 },
    { hanja: "竭", meaning: "다할 갈", strokes: 14 },
  ],
  "검": [
    { hanja: "劍", meaning: "칼 검", strokes: 15 },
    { hanja: "儉", meaning: "검소할 검", strokes: 15 },
    { hanja: "檢", meaning: "검사할 검", strokes: 17 },
    { hanja: "黔", meaning: "검을 검", strokes: 16 },
  ],
  "괘": [
    { hanja: "卦", meaning: "괘 괘", strokes: 8 },
    { hanja: "掛", meaning: "걸 괘", strokes: 11 },
  ],
  "굴": [
    { hanja: "屈", meaning: "굽을 굴", strokes: 8 },
    { hanja: "窟", meaning: "굴 굴", strokes: 13 },
    { hanja: "掘", meaning: "팔 굴", strokes: 11 },
  ],
  "궁": [
    { hanja: "宮", meaning: "집 궁", strokes: 10 },
    { hanja: "弓", meaning: "활 궁", strokes: 3 },
    { hanja: "窮", meaning: "다할 궁", strokes: 15 },
    { hanja: "穹", meaning: "하늘 궁", strokes: 8 },
  ],
  "긍": [
    { hanja: "肯", meaning: "즐길 긍", strokes: 8 },
    { hanja: "矜", meaning: "자긍할 긍", strokes: 9 },
  ],
  "급": [
    { hanja: "及", meaning: "미칠 급", strokes: 4 },
    { hanja: "急", meaning: "급할 급", strokes: 9 },
    { hanja: "給", meaning: "줄 급", strokes: 12 },
    { hanja: "級", meaning: "등급 급", strokes: 9 },
  ],
  "긴": [
    { hanja: "緊", meaning: "긴할 긴", strokes: 15 },
  ],
  "렴": [
    { hanja: "斂", meaning: "거둘 렴", strokes: 17 },
    { hanja: "簾", meaning: "발 렴", strokes: 19 },
  ],
};

/**
 * 한국 성씨 (2글자 성씨 먼저 체크)
 */
export const COMMON_FAMILY_NAMES = [
  // 2글자 성씨
  "남궁", "독고", "동방", "사공", "서문", "선우", "제갈", "황보",
  // 1글자 성씨 (빈도순)
  "김", "이", "박", "최", "정", "강", "조", "윤", "장", "임",
  "한", "오", "서", "신", "권", "황", "안", "송", "류", "전",
  "홍", "고", "문", "양", "손", "배", "백", "허", "유", "남",
  "심", "노", "하", "곽", "성", "차", "주", "우", "구", "민",
  "나", "진", "지", "엄", "채", "원", "천", "방", "공", "변",
  "염", "석", "추", "도", "탁", "마", "피", "연", "위", "표",
];

/**
 * 한글 이름을 성 + 이름 음절로 분리
 */
export function splitKoreanName(fullName: string): {
  familyName: string;
  givenNameSyllables: string[];
} | null {
  if (!fullName || fullName.length < 2) return null;

  // 2글자 성씨 먼저 체크
  for (const surname of COMMON_FAMILY_NAMES) {
    if (surname.length === 2 && fullName.startsWith(surname) && fullName.length > 2) {
      return {
        familyName: surname,
        givenNameSyllables: fullName.slice(2).split(""),
      };
    }
  }

  // 1글자 성씨
  const firstChar = fullName[0];
  if (COMMON_FAMILY_NAMES.includes(firstChar)) {
    return {
      familyName: firstChar,
      givenNameSyllables: fullName.slice(1).split(""),
    };
  }

  // 기본값: 첫 글자를 성으로 간주
  return {
    familyName: firstChar,
    givenNameSyllables: fullName.slice(1).split(""),
  };
}
